/**
 * report.mjs - the only module in the loop that writes anything.
 *
 * It writes reports, and it refuses any path that is not under a reports
 * directory. That refusal is not belt and braces: it is the single choke point
 * that makes "this stage cannot touch a content record" a property of the code
 * rather than a promise in a comment. Everything else in this directory reads.
 *
 * The Markdown is written for one reader doing one thing: deciding what to
 * work on this morning, and later deciding whether this loop can be trusted
 * with write access. So it opens with what the loop refused to do, not with
 * what it found. 298 expired rows is a shape, not a to-do list, and it is
 * reported as one.
 */

import { appendFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

/** Report roots this module is allowed to write into. */
const ALLOWED = ['ops/reports/', 'reports/'];

/**
 * The one place a path is checked, so there is only one place to get it wrong.
 * Both writers below go through it, and so does every future one.
 */
function guardedPath(target) {
  const normalised = path.resolve(target).replace(/\\/g, '/');
  if (!ALLOWED.some((root) => normalised.includes(`/${root}`))) {
    throw new Error(`refusing to write outside a reports directory: ${target}`);
  }
  return normalised;
}

export async function writeReport(target, body) {
  const normalised = guardedPath(target);
  await mkdir(path.dirname(normalised), { recursive: true });
  await writeFile(normalised, body, 'utf8');
  return normalised;
}

/**
 * Append to a ledger, under the same refusal.
 *
 * Separate from writeReport rather than a flag on it, because the two have
 * different failure modes and only one of them is recoverable. A report
 * rewritten wrongly can be regenerated from the corpus. A ledger line lost to
 * an accidental overwrite is a decision a person took that the record no
 * longer holds, and nothing regenerates that.
 */
export async function appendReport(target, line) {
  const normalised = guardedPath(target);
  await mkdir(path.dirname(normalised), { recursive: true });
  await appendFile(normalised, line, 'utf8');
  return normalised;
}

const table = (headers, rows) => {
  if (rows.length === 0) return '_Nothing to report._\n';
  const head = `| ${headers.join(' | ')} |`;
  const rule = `|${headers.map(() => '---').join('|')}|`;
  return [head, rule, ...rows.map((row) => `| ${row.join(' | ')} |`)].join('\n') + '\n';
};

const pairs = (object) =>
  Object.entries(object ?? {})
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([key, value]) => [key, String(value)]);

const pct = (part, whole) => (whole ? `${Math.round((part / whole) * 100)}%` : '0%');

export function renderMarkdown(run, checks) {
  const lines = [];
  const push = (text = '') => lines.push(text);

  push('# PI-006 verification loop: proposal-only run');
  push();
  push(
    `Generated by \`${run.generator}\` as at ${run.asAt}. Mode: **${run.mode}**. ` +
      'Nothing in this run wrote to a content record, and no component in the loop can: the ' +
      'only writer in the directory refuses any path outside a reports tree, and the run ' +
      'hashes every content and data file before and after itself to prove it.'
  );
  push();

  push('## Whether this run can be trusted');
  push();
  push(
    'These checks are the point of the proposal-only stage. They are the properties a write stage ' +
      'would have to keep, measured against the real corpus, so the write-scope decision has ' +
      'evidence rather than assurances.'
  );
  push();
  push(
    table(
      ['Check', 'Result', 'What it means'],
      (checks ?? []).map((check) => [check.id, check.pass ? 'pass' : 'FAIL', check.why])
    )
  );

  push('## What the loop refused to do');
  push();
  push(
    'A refusal is the loop declining to compose a change it cannot support. This count matters ' +
      'more than the findings: a loop that never refuses anything is a loop with no guard, and ' +
      'the guard is the component a write stage has to trust.'
  );
  push();
  if ((run.refusals ?? []).length === 0) {
    push(
      'None this run, and on a production run that is the expected reading rather than a clean ' +
        'bill of health. The researcher in this stage is a deterministic detector set, and it ' +
        'proposes only what a page can establish, so it rarely offers the guard anything to ' +
        'refuse. The guard is exercised instead by the seeded fixtures in ' +
        '`scripts/verification-loop/fixtures/seeded-failures`, where a simulated model-backed ' +
        'researcher proposes a bumped check date, a licence read off a credit line and a ' +
        'first-person visit, and `scripts/verification-loop.test.mjs` asserts that all three are ' +
        'refused. That is where a write stage should look for evidence, because that is the ' +
        'traffic a write stage would actually carry.'
    );
  } else {
    push(
      table(
        ['Rule', 'Field', 'Why'],
        run.refusals.map((item) => [item.rule, item.field ?? '', item.why])
      )
    );
  }

  push('## The registry');
  push();
  push(
    `${run.registry.claims} claims, ${run.registry.evidence} evidence rows. State is derived, ` +
      'never stored, so these numbers move with the calendar and not with a migration.'
  );
  push();
  push(table(['Claim state', 'Claims'], pairs(run.registry.byState)));
  push(table(['Reader consequence', 'Claims'], pairs(run.registry.byConsequence)));

  push('## The backlog, as a shape');
  push();
  push(
    `${run.backlog.expiredRows} evidence rows are expired, across ` +
      `${run.backlog.claimsWithExpiredEvidence} claims. That is the corpus arriving with a ` +
      'history, not a list of defects introduced this week, and working it as a queue would be ' +
      'a mistake. What matters is the shape: which classes, how overdue, and whether anybody ' +
      'can still reach the page the claim sits on.'
  );
  push();
  push(table(['Claim class', 'Expired rows'], pairs(run.backlog.byClaimClass)));
  push(table(['How overdue', 'Expired rows'], pairs(run.backlog.byAgeBand)));
  push(table(['Reader consequence', 'Expired rows'], pairs(run.backlog.byConsequence)));
  push();
  push(
    `${run.backlog.unreachableSubjects} claims sit behind a record no reader can reach: an ` +
      'archived event, a lapsed note, a date that has passed. They stay counted here and stay ' +
      'out of the worklist, because re-fetching an organiser page for a festival that already ' +
      'ran is work with nobody on the other end of it. ' +
      `${run.backlog.unresearchableClaims} more cite no fetchable URL at all and can never be ` +
      'checked from their own record.'
  );
  push();

  push('## Blind spots');
  push();
  if ((run.blindSpots ?? []).length === 0) {
    push('Every claim class the precedence table defines has at least one evidence row.');
  } else {
    push(
      'Claim classes the precedence table defines and the corpus has no evidence for. The loop ' +
        'reports nothing about these, and that silence is an absence of looking rather than an ' +
        'all-clear. Naming them is the only honest thing to do with a gap.'
    );
    push();
    push(
      table(
        ['Claim class', 'What it covers', 'Claims', 'Evidence'],
        run.blindSpots.map((item) => [item.claimClass, item.label, String(item.claims), '0'])
      )
    );
  }
  push();

  push('## This run');
  push();
  push(
    `${run.worklist.selected} claims were selected from ${run.worklist.eligible} eligible, ` +
      `ranked by reader consequence and how far past expiry they are, capped at ` +
      `${run.worklist.limit}. Selection is deterministic: two runs over an unchanged corpus ` +
      'pick the same batch, which is what makes comparing the loop against a human possible.'
  );
  push();
  push(table(['Adjudication', 'Claims'], pairs(run.adjudication)));
  push(table(['Source reachability', 'Claims'], pairs(run.sourceHealth)));
  push(table(['Critic verdict on proposed changes', 'Ops'], pairs(run.verdictCounts)));
  push();
  const unread =
    (run.sourceHealth.blocked ?? 0) + (run.sourceHealth.dead ?? 0) + (run.sourceHealth.error ?? 0);
  push(
    `${unread} of ${run.worklist.selected} sources (${pct(unread, run.worklist.selected)}) could ` +
      'not be read. That is a fact about the citations, not about the claims, and it is kept out ' +
      'of the findings for exactly that reason: a checker that files "I could not look" as ' +
      '"this is wrong" produces a report nobody reads twice.'
  );
  push();

  push('## The queue');
  push();
  push(
    'Every row states a specific decision and what happens if nobody takes it. A finding that ' +
      'cannot be written that way is a finding the loop has not thought through, and the ' +
      'deterministic gate fails the run over it.'
  );
  push();
  push(
    table(
      ['Kind', 'Subject', 'Consequence', 'Decision', 'If no answer'],
      (run.escalations ?? [])
        .slice(0, 60)
        .map((item) => [
          item.kind,
          item.subject ?? '',
          item.consequence,
          `${item.why}. ${item.question}`,
          item.defaultIfNoAnswer,
        ])
    )
  );
  if ((run.escalations ?? []).length > 60) {
    push();
    push(`_${run.escalations.length - 60} further rows are in the JSON report._`);
  }
  push();

  push('## Proposed changes');
  push();
  if ((run.proposedOps ?? []).length === 0) {
    push('None. The loop composed no field-level change this run.');
  } else {
    push(
      'Field-level, each citing the fetched artifact it came from. **Nothing applies these.** ' +
        'In proposal-only the patch is the output, and a person is the only thing that can act on it. ' +
        'The verdict column is the critic reading the source itself rather than the proposal: ' +
        '`rejected` means the loop proposed a change the page does not support, and those rows ' +
        'are the most useful thing in this report, because they are the measured error rate a ' +
        'write-scope decision needs.'
    );
    push();
    push(
      table(
        ['Claim', 'Field', 'To', 'Critic', 'Why', 'Source digest'],
        run.proposedOps.map((op) => [
          op.claimId,
          op.path,
          JSON.stringify(op.to),
          op.verdict ?? 'unreviewed',
          op.reason,
          op.sources?.[0]?.digest ?? '',
        ])
      )
    );
  }
  push();

  push('## The review queue');
  push();
  const proposals = run.proposals ?? [];
  const decidable = proposals.filter((item) => item.acceptability?.acceptable);
  push(
    `${proposals.length} of those changes were written up as proposals, of which ` +
      `${decidable.length} are decidable. A proposal carries the seven things a reviewer needs ` +
      'and a patch table does not: the claim, what the record says now, what is proposed, the ' +
      'URL read, when it was read, what kind of publisher that is, and where that kind sits in ' +
      'precedence for this class of claim. The rest are shown with the reason they cannot be ' +
      'decided here, which is usually that the critic threw the change out. The loop will not ' +
      'carry a change its own second reading rejected, and a person who disagrees edits the ' +
      'record by hand with their own name on it.'
  );
  push();
  push(
    table(
      ['Proposal', 'Claim', 'Field', 'Source kind', 'Rank', 'Critic', 'Decidable'],
      proposals.map((item) => [
        item.proposalId,
        item.claim.claimId,
        item.change.field,
        item.read.publisherKind,
        `${item.read.precedence.rank ?? 'unlisted'} of ${item.read.precedence.of}`,
        item.critic.verdict,
        item.acceptability?.acceptable ? 'yes' : `no: ${item.acceptability?.code}`,
      ])
    )
  );
  push();
  push(
    'Review them with `npm run verify:review -- --list`. Accepting one records a decision in ' +
      '`ops/reports/verification/decisions.jsonl` and changes no page. Preparing the edit is a ' +
      'separate command, `npm run verify:apply`, and it writes a patch file rather than a ' +
      'record.'
  );
  push();

  push('## What a write stage would still need');
  push();
  push(
    '- A run of this loop against human decisions on the same batch, so the critic has a ' +
      'measured false-positive and false-negative rate rather than an assumed one.'
  );
  push(
    '- A decision on write scope (D5). Nothing here presumes one, and the guard list in ' +
      '`compose.mjs` is the narrowest defensible starting point, not a proposal.'
  );
  push(
    '- Evidence coverage for the three blind-spot classes. A write stage that cannot see ' +
      'opening hours, accessibility or rate changes would be writing with a third of the ' +
      'reader-facing surface out of view.'
  );
  push(
    '- An owner for the dead and blocked citations. Roughly a third of this corpus cannot be ' +
      'checked from its own recorded source, and no amount of loop improves that number.'
  );
  push();

  return lines.join('\n');
}
