import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {pathToFileURL} from 'node:url';import path from 'node:path';import {verifyCandidate} from './verify.mjs';
import {createRequire} from 'node:module';import {writeFile} from 'node:fs/promises';
const require=createRequire(new URL('../../next/package.json',import.meta.url));const puppeteer=require('puppeteer');const browser=await puppeteer.launch({headless:true,executablePath:process.env.PI_BROWSER_EXECUTABLE});const report=[];
try{const page=await browser.newPage();for(const width of [1440,390]){await page.setViewport({width,height:1000});await page.goto('http://127.0.0.1:4322/whats-on/',{waitUntil:'networkidle0'});const result=await page.evaluate(()=>({title:document.title,overflow:document.documentElement.scrollWidth>innerWidth+1,heading:document.querySelector('h1')?.textContent}));if(result.overflow)throw new Error('Calendar horizontal overflow '+width);report.push({width,...result});await page.screenshot({path:'ops/reports/events/intelligence/calendar-'+width+'.png',fullPage:false});}
for(const slug of ['bass-flinders-gin-masterclass','sorrento-writers-festival-2026']){await page.goto('http://127.0.0.1:4322/whats-on/'+slug+'/',{waitUntil:'networkidle0'});const result=await page.evaluate(()=>({title:document.title,text:document.body.innerText.slice(0,4000),eventSchema:[...document.querySelectorAll('script[type="application/ld+json"]')].some(script=>/"@type"\s*:\s*"Event"/.test(script.textContent)),calendar:[...document.querySelectorAll('a,button')].some(node=>/add to calendar|download calendar/i.test(node.textContent))}));assert.equal(result.eventSchema,false);assert.equal(result.calendar,false);if(slug==='bass-flinders-gin-masterclass')assert.ok(result.text.includes('Experience'));else assert.ok(result.text.includes('has ended'));report.push({slug,...result});}
const packet=JSON.parse(await readFile('ops/reports/events/intelligence/review-packet.json','utf8'));const expected=packet.candidates.filter(c=>!verifyCandidate(c,packet.evidence).errors.some(e=>['past-event','past-offer'].includes(e))).length;
const review=await browser.newPage(),external=[];review.on('request',request=>{if(/^https?:/.test(request.url()))external.push(request.url());});await review.goto(pathToFileURL(path.resolve('ops/reports/events/intelligence/review.html')).href);
const count=()=>review.evaluate(()=>({total:document.querySelectorAll('article').length,visible:[...document.querySelectorAll('article')].filter(a=>!a.hidden).length}));const initial=await count();assert.equal(initial.total,packet.candidates.length);assert.equal(initial.visible,expected);await review.click('#history');assert.equal((await count()).visible,packet.candidates.length);await review.select('#kind','offer');assert.equal((await count()).visible,packet.candidates.filter(c=>c.kind==='offer').length);assert.equal(external.length,0);await writeFile('ops/reports/events/intelligence/review-browser.json',JSON.stringify({...initial,externalRequests:external.length,filtersPassed:true},null,2));
await writeFile('ops/reports/events/intelligence/browser-smoke.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.map(({text,...result})=>({...result,experienceLabel:text?.includes('Experience'),endedNotice:text?.includes('has ended')})),null,2));}finally{await browser.close();}
