import {safeUrl,hash} from './data.mjs';
import {verifyCandidate} from './verify.mjs';
import {assessShireLocation} from './geography.mjs';
export function sourceCoverage({venues=[],sources=[],candidates=[],evidence=[],boundaryEvidence=null,boundaryReview=null},{now=new Date()}={}){
 const seedByHost=new Map(),towns=new Map(),categories=new Map(),audiences=new Map();
 for(const locality of boundaryReview?.localities??[]){const town=locality.name.toLowerCase().replace(/\s+/g,'-');towns.set(town,{town,geographicState:locality.state,venues:0,sourceLeads:0,confirmedCandidates:0,unconfirmedCandidates:0});}
 for(const venue of venues){const town=typeof venue.place==='string'?venue.place:venue.place?.id??'unknown';const row=towns.get(town)??{town,venues:0,sourceLeads:0,confirmedCandidates:0,unconfirmedCandidates:0};row.venues++;towns.set(town,row);
  let url;try{url=safeUrl(venue.website);}catch{continue;}row.sourceLeads++;
  const lead=seedByHost.get(url.hostname)??{id:'venue-'+hash(url.hostname).slice(0,16),url:url.href,host:url.hostname,venueIds:[],towns:[],categories:[],state:'seeded-from-cms',authority:'unverified',retrievalAllowed:false,reviewRequired:true,queries:[`site:${url.hostname} events`,`site:${url.hostname} whats on`,`site:${url.hostname} workshops`]};let assessment={state:'coordinates-or-boundary-evidence-missing',humanReviewRequired:true};if(boundaryEvidence&&Number.isFinite(venue.coordinates?.lat)&&Number.isFinite(venue.coordinates?.lng)){try{assessment=assessShireLocation(boundaryEvidence,[venue.coordinates.lng,venue.coordinates.lat],{now});}catch(error){assessment={state:'review',error:error.message,humanReviewRequired:true};}}lead.venueAssessments??=[];lead.venueAssessments.push({venueId:venue.slug??venue.id,...assessment,coordinateEvidence:'existing CMS coordinates; provenance needs review'});lead.venueIds.push(venue.slug??venue.id);if(!lead.towns.includes(town))lead.towns.push(town);if(venue.type&&!lead.categories.includes(venue.type))lead.categories.push(venue.type);seedByHost.set(url.hostname,lead);
 }
 for(const candidate of candidates){const town=candidate.fields?.suburb?.toLowerCase().replace(/\s+/g,'-')??'unknown';const row=towns.get(town)??{town,venues:0,sourceLeads:0,confirmedCandidates:0,unconfirmedCandidates:0};const scopeErrors=verifyCandidate(candidate,evidence,{now}).errors.filter(error=>/^(?:scope-|shire-)/.test(error));if(candidate.geography?.shireConfirmed===true&&scopeErrors.length===0)row.confirmedCandidates++;else row.unconfirmedCandidates++;towns.set(town,row);const cat=candidate.category??'unclassified';categories.set(cat,(categories.get(cat)??0)+1);const segments=Object.keys(candidate.audienceAssessments??{});if(!segments.length)audiences.set('unassessed',(audiences.get('unassessed')??0)+1);for(const segment of segments)audiences.set(segment,(audiences.get(segment)??0)+1);}
 const registeredHosts=new Set(sources.map(source=>new URL(source.url).hostname));
 return {scope:'PI content-seeded coverage; geographic confirmation is required before source or listing admission.',completeness:'not-established',boundaryAssessment:boundaryReview?{state:boundaryReview.geographicCompleteness,evidenceId:boundaryReview.boundaryEvidenceId,method:boundaryReview.method}:null,towns:[...towns.values()].sort((a,b)=>a.town.localeCompare(b.town)),categories:Object.fromEntries(categories),audiences:Object.fromEntries(audiences),sourceTypes:{official:sources.filter(s=>s.authority==='official').length,aggregator:sources.filter(s=>s.authority==='aggregator').length,unverifiedVenueHosts:seedByHost.size},sourceLeads:[...seedByHost.values()].map(lead=>({...lead,registered:registeredHosts.has(lead.host)})),gaps:[...towns.values()].filter(row=>row.confirmedCandidates===0).map(row=>({town:row.town,reason:'no-confirmed-candidate-in-current-packet'})),unknowns:['Full Shire town denominator and boundary coverage','Independent organiser coverage outside existing PI venues','Audience analytics and demand evidence','Current rights and source extraction permissions']};
}
