import test from 'node:test'; import assert from 'node:assert/strict';
import {safeUrl,isPublicAddress,structuredEvents,extractCandidates,validateCandidate,duplicateSignals,fetchEvidence} from './data.mjs';
import {gradeStage,gradeSequence,validateEvidenceRefs} from './grade.mjs';
test('private URLs and redirect hosts are rejected',()=>{for(const url of ['http://example.com','https://127.0.0.1','https://user:secret@example.com','https://localhost'])assert.throws(()=>safeUrl(url));assert.throws(()=>safeUrl('https://other.com',['example.com']));});
test('reserved network addresses are rejected',()=>{for(const ip of ['127.0.0.1','10.0.0.4','169.254.169.254','172.20.0.1','192.168.1.1','100.64.0.1','::1','::ffff:127.0.0.1','fc00::1'])assert.equal(isPublicAddress(ip),false);assert.equal(isPublicAddress('8.8.8.8'),true);});
test('JSONLD traversal preserves separate sessions and quarantines extraction',()=>{const body='<script type="application/ld+json">'+JSON.stringify({'@graph':[{'@type':'Event',name:'Talk',startDate:'2026-10-10T10:00:00+11:00'},{'@type':'Event',name:'Talk',startDate:'2026-10-10T14:00:00+11:00'}]})+'</script>';assert.equal(structuredEvents(body).length,2);const records=extractCandidates({body,id:'proof',sourceId:'official',url:'https://example.com'});assert.notEqual(records[0].id,records[1].id);assert.equal(records[0].reviewStatus,'review');assert.ok(validateCandidate(records[0]).includes('shire-evidence-required'));assert.deepEqual(duplicateSignals(records[0],records[1]),[]);});
test('source redirects are not followed',async()=>{await assert.rejects(fetchEvidence({url:'https://example.com',hosts:['example.com']},{resolver:async()=>[{address:'8.8.8.8'}],fetcher:async()=>new Response('',{status:302})}),/HTTP 302/);});
test('empty and malformed source scripts never imply successful events',()=>{assert.deepEqual(structuredEvents('<script type="application/ld+json">bad</script>'),[]);});
test('9/10 cannot compensate for critical failure or undocumented pass',()=>{const rubric={id:'test',checks:['a','b','c','d','e','f','g','h','i','j'],critical:['a']};const checks=Object.fromEntries(rubric.checks.map(id=>[id,{passed:true,evidence:'test receipt'}]));checks.a.passed=false;assert.equal(gradeStage(rubric,{checks}).passed,false);checks.a.passed=true;checks.j.evidence='';assert.equal(gradeStage(rubric,{checks}).score,9);assert.equal(gradeSequence({stages:[rubric]},[]).passed,false);});

test('explicit source identity survives reschedule; distinct unkeyed sessions remain separate',()=>{const evidence={id:'e',sourceId:'official',url:'https://example.com/event',body:JSON.stringify({'@type':'Event','@id':'https://example.com/id/art',name:'Art',startDate:'2026-10-10'})};const original=extractCandidates(evidence)[0];evidence.body=JSON.stringify({'@type':'Event','@id':'https://example.com/id/art',name:'Art',startDate:'2026-10-11',previousStartDate:'2026-10-10'});assert.equal(extractCandidates(evidence)[0].id,original.id);evidence.body=JSON.stringify([{'@type':'Event',name:'Art',startDate:'2026-10-10T10:00:00+11:00'},{'@type':'Event',name:'Art',startDate:'2026-10-10T14:00:00+11:00'}]);const sessions=extractCandidates(evidence);assert.notEqual(sessions[0].id,sessions[1].id);});

test('PDF retrieval is opt-in, bounded and signature-checked with raw-byte provenance',async()=>{const source={id:'programme',url:'https://example.com/programme.pdf',hosts:['example.com'],authority:'official'};const options={resolver:async()=>[{address:'93.184.216.34'}],fetcher:async()=>new Response('%PDF-1.4\nreview',{headers:{'content-type':'application/pdf'}})};await assert.rejects(fetchEvidence(source,options),/Unsupported/);const evidence=await fetchEvidence({...source,allowPdf:true},options);assert.equal(Buffer.from(evidence.base64,'base64').toString(),'%PDF-1.4\nreview');assert.equal(evidence.body,undefined);assert.ok(evidence.hash);await assert.rejects(fetchEvidence({...source,allowPdf:true},{...options,fetcher:async()=>new Response('not pdf',{headers:{'content-type':'application/pdf'}})}),/signature/);await assert.rejects(fetchEvidence({...source,allowPdf:true},{...options,maxBytes:4}),/too large/);});

test('hashed grading references cannot pass missing, changed or outside-workspace evidence',()=>{assert.equal(validateEvidenceRefs([]),false);assert.equal(validateEvidenceRefs([{path:'../outside',sha256:'a'.repeat(64)}]),false);const rubric={id:'strict',checks:['proof'],critical:['proof'],requireHashedEvidence:true};assert.equal(gradeStage(rubric,{checks:{proof:{passed:true,evidence:'claim without receipt'}}}).passed,false);});

test('hash-bound evidence passes the exact saved bytes and fails after mutation',async()=>{const {mkdtemp,writeFile,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const path=await import('node:path');const {createHash}=await import('node:crypto');const root=await mkdtemp(path.join(tmpdir(),'pi-grade-'));try{await writeFile(path.join(root,'receipt.txt'),'verified result');const refs=[{path:'receipt.txt',sha256:createHash('sha256').update('verified result').digest('hex')}];assert.equal(validateEvidenceRefs(refs,root),true);await writeFile(path.join(root,'receipt.txt'),'changed result');assert.equal(validateEvidenceRefs(refs,root),false);}finally{await rm(root,{recursive:true,force:true});}});

test('explicit schema status is normalised while retaining the raw source claim and unverified extraction',()=>{const body=JSON.stringify({'@type':'Event',name:'Status fixture',startDate:'2026-10-10',eventStatus:'https://schema.org/EventCancelled'});const candidate=extractCandidates({id:'e',sourceId:'source',url:'https://example.org',body})[0];assert.equal(candidate.fields.status,'cancelled');assert.equal(candidate.sourceStatus,'https://schema.org/EventCancelled');assert.equal(candidate.extractionOnly,true);assert.notEqual(candidate.proofs.status.verified,true);});
