import {execFileSync} from 'node:child_process';import {fstatSync} from 'node:fs';
import path from 'node:path';import os from 'node:os';import {randomUUID,createHash} from 'node:crypto';import {realpath,lstat,open,rename,mkdir,readFile} from 'node:fs/promises';import {readBoundedServiceBytes} from './editorial-service.mjs';import {prepareEditorialTransaction} from './editorial-transaction.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
async function syncDir(dir){const h=await open(dir,'r');try{await h.sync();}finally{await h.close();}}
async function durable(file,value){const h=await open(file,'wx');try{await h.writeFile(JSON.stringify(value,null,2));await h.sync();}finally{await h.close();}await syncDir(path.dirname(file));}
async function bytesOrAbsent(file){try{return await readBoundedServiceBytes(file,2*1024**2);}catch(e){if(e.code==='ENOENT')return null;throw e;}}
async function fixtureRoot(root,expectedRoot){const resolved=await realpath(root),temp=await realpath(os.tmpdir()),rel=path.relative(temp,resolved);if(resolved!==await realpath(expectedRoot)||!rel||rel.startsWith('..')||path.isAbsolute(rel)||(await lstat(root)).isSymbolicLink())throw Error('Disposable temporary fixture root required');const marker=JSON.parse(await readBoundedServiceBytes(path.join(resolved,'fixture-only.json'),16384));if(marker.schemaVersion!==1||marker.fixtureOnly!==true||marker.root!==resolved)throw Error('Explicit fixture marker required');return resolved;}
async function requireFixtureKernelLock(root,lock){if(process.platform!=='linux')throw Error('Fixture application requires Linux kernel lock');if(!lock?.pythonPath||!lock.pythonHash)throw Error('Pinned fixture kernel verifier required');const python=await realpath(lock.pythonPath),bytes=await readBoundedServiceBytes(python,150*1024**2);if(sha(bytes)!==lock.pythonHash||(await lstat(lock.pythonPath)).isSymbolicLink())throw Error('Fixture Python pin mismatch');const fd=Number(process.env.PI_EDITORIAL_KERNEL_FD);if(!Number.isSafeInteger(fd)||fd<3)throw Error('Inherited fixture lock required');const own=fstatSync(fd),named=await lstat(path.join(root,'kernel-advisory.lock'));if(named.isSymbolicLink()||own.dev!==named.dev||own.ino!==named.ino)throw Error('Fixture lock identity mismatch');execFileSync(python,['-c',"import fcntl,os,sys;fcntl.flock(3,fcntl.LOCK_EX|fcntl.LOCK_NB);f=os.open(sys.argv[1],os.O_RDWR|os.O_NOFOLLOW);\ntry: fcntl.flock(f,fcntl.LOCK_EX|fcntl.LOCK_NB);sys.exit(9)\nexcept BlockingIOError: pass",path.join(root,'kernel-advisory.lock')],{stdio:['ignore','ignore','pipe',fd],timeout:5000});}
function held(data){return !!(data?.reviewHold||data?.factualReviewHold||data?.cancelled||data?.postponed||data?.sourceReview?.required||['rejected','held','hold','archived','withdrawn'].includes(data?.reviewStatus));}
async function verifyPatch(root,patch){if(!/^[a-z0-9-]{8,80}$/.test(patch.eventId)||path.basename(patch.file)!==patch.file||!patch.file.endsWith('.json'))throw Error('Unsafe patch target');const file=path.join(root,patch.file),before=await bytesOrAbsent(file);if(patch.expected?.state==='absent'){if(before)throw Error('Absent target CAS mismatch');}else if(patch.expected?.state==='existing'){if(!before||sha(before)!==patch.expected.sha256)throw Error('Existing target CAS mismatch');const data=JSON.parse(before);if(held(data)||data.eventId!==patch.eventId||data.intelligence?.approvalMode!=='automated'||data.intelligence?.approvedBy!=='PI editorial policy')throw Error('Human/legacy target protected');}else throw Error('Patch CAS expectation required');return {file,before};}
async function checkProofPins(args,plan){if(sha(await readBoundedServiceBytes(args.packetPath,64*1024**2))!==plan.packetHash||sha(await readBoundedServiceBytes(args.registryPath,256*1024))!==plan.registryHash)throw Error('Human/source proof inputs changed before apply');const root=await realpath(args.serviceRoot),serviceBytes=await readBoundedServiceBytes(path.join(root,args.serviceRunId,'service-receipt.json'),64*1024**2);if(sha(serviceBytes)!==args.serviceReceiptHash)throw Error('Service proof changed before apply');const service=JSON.parse(serviceBytes),head=JSON.parse(await readBoundedServiceBytes(path.join(root,'latest.json'),1024**2));if(head.runId!==args.serviceRunId||head.hash!==args.serviceReceiptHash||sha(await readBoundedServiceBytes(path.join(root,args.serviceRunId,'episode-ledger.json'),1024**2))!==service.ledgerHash)throw Error('Committed proof head/ledger changed before apply');const producerBytes=await readBoundedServiceBytes(path.join(root,service.producerRunId,'receipt.json'),64*1024**2);if(sha(producerBytes)!==args.producerReceiptHash)throw Error('Producer proof changed before apply');const producer=JSON.parse(producerBytes);for(const capture of producer.captures){if(path.basename(capture.file)!==capture.file||sha(await readBoundedServiceBytes(path.join(root,service.producerRunId,capture.file),12*1024**2))!==capture.fileHash)throw Error('Capture proof changed before apply');}}
/** Disposable fixtures ONLY. No canonical source application or deployment API. */
export async function applyEditorialFixture({enabled=false,fixtureContentRoot,expectedFixtureRoot,journalRoot,expectedJournalRoot,kernelLock,planPath,planHash,transactionArguments,now=new Date(),checkpoint=async()=>{}}={}){
 if(enabled!==true)return {state:'disabled'};const root=await fixtureRoot(fixtureContentRoot,expectedFixtureRoot);await requireFixtureKernelLock(root,kernelLock);const journalBase=await fixtureRoot(journalRoot,expectedJournalRoot);if(journalBase!==await realpath(expectedJournalRoot)||path.relative(root,journalBase)===''||!path.relative(root,journalBase).startsWith('..')||!path.relative(journalBase,root).startsWith('..'))throw Error('Disjoint pinned fixture journal root required');const planBytes=await readBoundedServiceBytes(planPath,2*1024**2),plan=JSON.parse(planBytes);if(sha(planBytes)!==planHash||plan.state!=='prepared'||plan.applied!==false||!Array.isArray(plan.patches)||plan.patches.length>5)throw Error('Pinned prepared plan required');await fixtureRoot(transactionArguments.outputRoot,transactionArguments.expectedOutputRoot);if(transactionArguments.contentRoot!==root||transactionArguments.expectedContentRoot!==root)throw Error('Revalidation content root mismatch');
 const original=await prepareEditorialTransaction({...transactionArguments,now:new Date(plan.checkedAt)});if(JSON.stringify(original.patches)!==JSON.stringify(plan.patches))throw Error('Original plan revalidation mismatch');await prepareEditorialTransaction({...transactionArguments,now});
 const planDir=path.dirname(planPath),targets=[];for(const patch of plan.patches){const target=await verifyPatch(root,patch),after=await readBoundedServiceBytes(path.join(planDir,patch.eventId+'-proposed.json'),2*1024**2);if(sha(after)!==patch.afterHash)throw Error('Proposed bytes changed');targets.push({...target,patch,after});}if(new Set(targets.map(t=>t.file)).size!==targets.length)throw Error('Duplicate fixture target');const id=randomUUID(),journalDir=path.join(journalBase,id);await mkdir(journalDir,{recursive:true});await syncDir(journalBase);await durable(path.join(journalDir,'intent.json'),{schemaVersion:1,id,state:'pending',planHash,planPath,checkedAt:now.toISOString(),targets:targets.map(t=>({file:t.patch.file,eventId:t.patch.eventId,beforeHash:t.before?sha(t.before):null,afterHash:sha(t.after)}))});
 for(let index=0;index<targets.length;index++){const target=targets[index];if(target.before){const h=await open(path.join(journalDir,index+'-before.bin'),'wx');try{await h.writeFile(target.before);await h.sync();}finally{await h.close();}}await durable(path.join(journalDir,index+'-ready.json'),{beforeHash:target.before?sha(target.before):null,afterHash:sha(target.after)});await checkpoint('before-write',index);await checkProofPins(transactionArguments,plan);await requireFixtureKernelLock(root,kernelLock);await verifyPatch(root,target.patch);const temp=target.file+'.'+id+'.tmp',h=await open(temp,'wx');try{await h.writeFile(target.after);await h.sync();}finally{await h.close();}await verifyPatch(root,target.patch);await rename(temp,target.file);await syncDir(root);await checkpoint('after-write',index);await durable(path.join(journalDir,index+'-applied.json'),{afterHash:sha(target.after)});}
 await durable(path.join(journalDir,'complete.json'),{state:'complete',id,fixtureOnly:true});return {state:'complete',id,journalDir,fixtureOnly:true};
}
export async function rollbackEditorialFixture({enabled=false,fixtureContentRoot,expectedFixtureRoot,journalRoot,expectedJournalRoot,kernelLock,journalDir,expectedIntentHash,checkpoint=async()=>{}}={}){
 if(enabled!==true)return {state:'disabled'};const root=await fixtureRoot(fixtureContentRoot,expectedFixtureRoot);await requireFixtureKernelLock(root,kernelLock);const journalBase=await fixtureRoot(journalRoot,expectedJournalRoot);if(journalBase!==await realpath(expectedJournalRoot)||!path.relative(root,journalBase).startsWith('..')||!path.relative(journalBase,root).startsWith('..'))throw Error('Disjoint pinned fixture journal root required');const journal=await realpath(journalDir),rel=path.relative(journalBase,journal);if(!rel||rel.startsWith('..')||path.isAbsolute(rel))throw Error('Fixture journal root required');const bytes=await readBoundedServiceBytes(path.join(journal,'intent.json'),2*1024**2);if(sha(bytes)!==expectedIntentHash)throw Error('Pinned rollback intent required');const intent=JSON.parse(bytes);if(!Array.isArray(intent.targets)||intent.targets.length>5)throw Error('Bounded rollback targets required');
 const actions=[];for(const [index,target] of intent.targets.entries()){if(path.basename(target.file)!==target.file||!target.file.endsWith('.json'))throw Error('Unsafe rollback target');const file=path.join(root,target.file),current=await bytesOrAbsent(file);if(current&&sha(current)===target.beforeHash)continue;if(!current&&target.beforeHash===null)continue;if(!current||sha(current)!==target.afterHash)throw Error('Rollback refuses later edits');const before=target.beforeHash?await readBoundedServiceBytes(path.join(journal,index+'-before.bin'),2*1024**2):null;if(before&&sha(before)!==target.beforeHash)throw Error('Rollback backup mismatch');actions.push({file,currentHash:sha(current),before,index});}
 // Absent-original rollback preserves the applied file as a quarantined fixture artifact instead of deleting it.
 for(const action of actions){await checkpoint('before-rollback',action.index);await requireFixtureKernelLock(root,kernelLock);const current=await bytesOrAbsent(action.file);if(!current||sha(current)!==action.currentHash)throw Error('Rollback concurrent edit');if(action.before){const temp=action.file+'.rollback-'+randomUUID()+'.tmp',h=await open(temp,'wx');try{await h.writeFile(action.before);await h.sync();}finally{await h.close();}const last=await bytesOrAbsent(action.file);if(!last||sha(last)!==action.currentHash)throw Error('Rollback concurrent edit');await rename(temp,action.file);}else await rename(action.file,path.join(journal,action.index+'-withdrawn-fixture.json'));await syncDir(root);await syncDir(journal);await durable(path.join(journal,action.index+'-rolled-back.json'),{state:'rolled-back'});}
 return {state:'rolled-back',fixtureOnly:true,actions:actions.length};
}
