import {execFileSync} from 'node:child_process';import {fstatSync} from 'node:fs';
import path from 'node:path';import os from 'node:os';import {randomUUID,createHash} from 'node:crypto';
import {open,readFile,rename,unlink,lstat,realpath,mkdir,readdir,statfs} from 'node:fs/promises';
import {hash} from './data.mjs';import {runEditorialProducer} from './editorial-producer.mjs';import {captureEventInventory,assertInventoryUnchanged} from '../../next/scripts/event-editorial-inventory.mjs';
export const SERVICE_VERSION='pi-editorial-service-1.0';
async function syncDirectory(dir){if(process.platform==='win32')return false;const handle=await open(dir,'r');try{await handle.sync();return true;}finally{await handle.close();}}
async function durable(file,value,{exclusive=false}={}){const target=exclusive?file:file+'.'+randomUUID()+'.tmp',handle=await open(target,'wx');try{await handle.writeFile(JSON.stringify(value,null,2));await handle.sync();}finally{await handle.close();}if(!exclusive)await rename(target,file);return syncDirectory(path.dirname(file));}
async function durableRaw(file,bytes){const handle=await open(file,'wx');try{await handle.writeFile(bytes);await handle.sync();}finally{await handle.close();}await syncDirectory(path.dirname(file));}
export async function readBoundedServiceBytes(file,max,{checkpoint=async()=>{}}={}){const before=await lstat(file);if(before.isSymbolicLink()||!before.isFile()||before.size>max)throw Error('Unsafe service input');const handle=await open(file,'r');try{const opened=await handle.stat();if(opened.dev!==before.dev||opened.ino!==before.ino||opened.size!==before.size)throw Error('Service input changed before read');await checkpoint();const chunks=[];let total=0;while(true){const chunk=Buffer.alloc(Math.min(65536,max+1-total));const {bytesRead}=await handle.read(chunk,0,chunk.length,null);if(!bytesRead)break;total+=bytesRead;if(total>max)throw Error('Service input byte budget');chunks.push(chunk.subarray(0,bytesRead));}const after=await handle.stat(),named=await lstat(file);if(named.isSymbolicLink()||after.dev!==before.dev||after.ino!==before.ino||named.dev!==before.dev||named.ino!==before.ino||after.size!==before.size||total!==before.size||after.mtimeMs!==before.mtimeMs||after.ctimeMs!==before.ctimeMs)throw Error('Service input changed during read');return Buffer.concat(chunks,total);}finally{await handle.close();}}
async function checkedRead(file,max=1024**2){const bytes=await readBoundedServiceBytes(file,max);return {value:JSON.parse(bytes),hash:hash(bytes.toString())};}
async function optionalRead(file){try{return await checkedRead(file);}catch(error){if(error.code==='ENOENT')return null;throw error;}}
async function processIdentity(){if(process.platform==='linux'){const raw=await readFile('/proc/self/stat','utf8');return {platform:'linux',pid:process.pid,host:os.hostname(),bootId:(await readFile('/proc/sys/kernel/random/boot_id','utf8')).trim(),startTicks:raw.slice(raw.lastIndexOf(')')+2).split(' ')[19]};}return {platform:process.platform,pid:process.pid,host:os.hostname(),processStartedAt:new Date(Date.now()-process.uptime()*1000).toISOString()};}
async function capacity(root,budget){if(!budget||!Number.isSafeInteger(budget.maxBytes)||budget.maxBytes<256*1024**2||budget.maxBytes>1024**3||!Number.isSafeInteger(budget.reserveBytes)||budget.reserveBytes<192*1024**2||budget.reserveBytes>budget.maxBytes||!Number.isSafeInteger(budget.maxRuns)||budget.maxRuns<2||budget.maxRuns>10000)throw Error('Explicit bounded service storage budget required');let bytes=0,runs=0,visited=0;async function walk(dir,depth=0){if(depth>8)throw Error('Service storage depth budget');for(const entry of await readdir(dir,{withFileTypes:true})){if(++visited>50000)throw Error('Service storage traversal budget');const file=path.join(dir,entry.name),info=await lstat(file);if(info.isSymbolicLink())throw Error('Service storage symlink refused');if(info.isDirectory()){if(depth===0&&/^[a-f0-9-]{36}$/.test(entry.name))runs++;await walk(file,depth+1);}else if(info.isFile())bytes+=Math.max(info.size,typeof info.blocks==='number'?info.blocks*512:Math.ceil(info.size/4096)*4096);else throw Error('Unknown service storage object');}}await walk(root);const fs=await statfs(root),diskFreeBytes=Number(fs.bavail)*Number(fs.bsize);return {bytes,runs,diskFreeBytes,measurement:'conservative max logical/allocated bytes; Windows allocation estimated at4KiB',available:diskFreeBytes>=budget.reserveBytes+64*1024**2&&bytes+budget.reserveBytes<=budget.maxBytes&&runs+2<=budget.maxRuns,budget};}
async function kernelGuard(root,config){if(process.platform!=='linux')throw Error('Kernel mode Linux only');if(await optionalRead(path.join(root,'service.lock')))throw Error('Legacy lock retained; busy');const marker=await checkedRead(path.join(root,'kernel-root.json'),16384);if(marker.hash!==config.kernelRootHash||JSON.stringify(marker.value)!==JSON.stringify({schemaVersion:1,mode:'linux-kernel-v1',root}))throw Error('Pinned clean kernel root required');const python=await realpath(config.kernelPythonPath);if((await lstat(config.kernelPythonPath)).isSymbolicLink()||createHash('sha256').update(await readBoundedServiceBytes(python,150*1024**2)).digest('hex')!==config.kernelPythonHash)throw Error('Pinned kernel Python required');const fd=Number(process.env.PI_EDITORIAL_KERNEL_FD);if(!Number.isSafeInteger(fd)||fd<3)throw Error('Inherited kernel lock FD required');const owned=fstatSync(fd),persistent=await lstat(path.join(root,'kernel-advisory.lock'));if(persistent.isSymbolicLink()||owned.dev!==persistent.dev||owned.ino!==persistent.ino)throw Error('Kernel lock file identity mismatch');execFileSync(python,['-c',"import fcntl,os,sys;fcntl.flock(3,fcntl.LOCK_EX|fcntl.LOCK_NB);f=os.open(sys.argv[1],os.O_RDWR|os.O_NOFOLLOW);\ntry: fcntl.flock(f,fcntl.LOCK_EX|fcntl.LOCK_NB);sys.exit(9)\nexcept BlockingIOError: pass",path.join(root,'kernel-advisory.lock')],{stdio:['ignore','ignore','pipe',fd],timeout:5000});return {fd,identity:owned};}
/** Trusted caller opt-in only; no scheduler installation, live publication or human acknowledgements. */
export async function runEditorialService({enabled=false,configPath,configHash,expectedRoot,now=new Date(),producer=runEditorialProducer,checkpoint=async()=>{}}={}){
 if(enabled!==true)return {version:SERVICE_VERSION,state:'disabled'};
 if(!/^[a-f0-9]{64}$/.test(configHash??'')||!expectedRoot||!Number.isFinite(+now))throw Error('Pinned service configuration/root/clock required');
 const input=await checkedRead(configPath,16384),config=input.value;if(input.hash!==configHash||config.schemaVersion!==1||config.enabled!==true)throw Error('Service configuration pin/enablement mismatch');
 const root=await realpath(config.root);if(root!==await realpath(expectedRoot)||(await lstat(config.root)).isSymbolicLink())throw Error('Canonical service root mismatch');
 const registryInput=await checkedRead(config.registryPath,256*1024);if(registryInput.hash!==config.registryHash)throw Error('Service registry pin mismatch');const registry=registryInput.value.sources??registryInput.value;
 if(!Array.isArray(registry)||config.producer?.registryHash!==hash(registry))throw Error('Producer registry contract mismatch');
 const identity=await processIdentity(),lockPath=path.join(root,'service.lock'),token=randomUUID();let lock,lockIdentity,serviceDirectory=null,serviceBase=null;
 const kernelMode=config.lockMode==='linux-kernel-v1';let kernelOwnership;if(kernelMode){kernelOwnership=await kernelGuard(root,config);lock={close:async()=>{}};}
 try{if(!kernelMode)lock=await open(lockPath,'wx');}catch(error){if(error.code==='EEXIST'){const blocked={version:SERVICE_VERSION,state:'busy',checkedAt:now.toISOString(),configHash,reason:'Existing lock retained; operator identity review required',humanAcknowledged:false,delivered:false};try{await durable(path.join(root,'lock-blocked.json'),blocked,{exclusive:true});}catch(persistenceError){if(persistenceError.code!=='EEXIST')blocked.persistenceFailure=persistenceError.message;}return blocked;}throw error;}
 try{
 if(!kernelMode){await lock.writeFile(JSON.stringify({token,identity,checkedAt:now.toISOString(),configHash}));await lock.sync();lockIdentity=await lock.stat();await syncDirectory(root);}else await kernelGuard(root,config);await checkpoint('locked');
 const storage=await capacity(root,config.storage);if(!storage.available){const held={version:SERVICE_VERSION,state:'capacity-held',storage,humanAcknowledged:false,delivered:false,reason:'Storage reserve exhausted; history retained'};try{await durable(path.join(root,'capacity-held.json'),held,{exclusive:true});}catch(error){if(error.code!=='EEXIST')held.persistenceFailure=error.message;}return held;}
 const packetBytes=await readBoundedServiceBytes(config.packetPath,64*1024**2),packet={value:JSON.parse(packetBytes),hash:hash(packetBytes.toString())},packetPhysicalBytes=Math.ceil(packetBytes.length/4096)*4096+65536;if(storage.bytes+config.storage.reserveBytes+packetPhysicalBytes>config.storage.maxBytes||storage.diskFreeBytes<config.storage.reserveBytes+64*1024**2+packetPhysicalBytes)throw Error('Frozen review snapshot storage reserve unavailable');const inventory=await captureEventInventory();
 const pointer=await optionalRead(path.join(root,'latest.json'));let previous=null,previousEpisodes={schemaVersion:1,episodes:[]};
 if(pointer){if(!/^[a-f0-9-]{36}$/.test(pointer.value.runId??''))throw Error('Invalid durable receipt identity');const prior=await checkedRead(path.join(root,pointer.value.runId,'service-receipt.json'),64*1024**2);if(prior.hash!==pointer.value.hash||prior.value.runId!==pointer.value.runId)throw Error('Durable receipt pin mismatch');previous=prior.value;const ledger=await checkedRead(path.join(root,pointer.value.runId,'episode-ledger.json'));if(ledger.hash!==pointer.value.ledgerHash||ledger.hash!==prior.value.ledgerHash)throw Error('Durable episode ledger pin mismatch');previousEpisodes=ledger.value;}
 const same=previous?.state==='complete'&&previous.version===SERVICE_VERSION&&previous.configHash===configHash&&previous.packetHash===packet.hash&&previous.registryHash===config.registryHash&&previous.inventoryFingerprint===inventory.fingerprint;
 const checked=Date.parse(previous?.checkedAt),priorDeadline=Date.parse(previous?.deadline);if(same&&Number.isFinite(checked)&&checked<=+now&&priorDeadline>+now&&priorDeadline<=checked+12*3600000)return {version:SERVICE_VERSION,state:'not-due',deadline:previous.deadline};
 if(kernelMode)await kernelGuard(root,config);const runId=randomUUID(),dir=path.join(root,runId);serviceDirectory=dir;await mkdir(dir);const base={version:SERVICE_VERSION,runId,actor:'PI editorial policy',checkedAt:now.toISOString(),configPath:await realpath(configPath),configHash,registryHash:config.registryHash,packetHash:packet.hash,inventoryFingerprint:inventory.fingerprint,productionInstalled:false,directorySyncSupported:process.platform!=='win32'};
 serviceBase=base;if(kernelMode)await durable(path.join(dir,'kernel-ownership.json'),{token,identity,fdDev:kernelOwnership.identity.dev,fdIno:kernelOwnership.identity.ino},{exclusive:true});await durable(path.join(dir,'pending.json'),{...base,state:'incomplete',storage},{exclusive:true});await checkpoint('pending');
 const packetSnapshotPath=path.join(dir,'review-packet.snapshot.json'),packetSnapshotBytes=await readBoundedServiceBytes(config.packetPath,64*1024**2);if(hash(packetSnapshotBytes.toString())!==packet.hash)throw Error('Review packet changed before snapshot');await durableRaw(packetSnapshotPath,packetSnapshotBytes);
 let result,errorMessage=null;try{result=await producer({enabled:true,config:config.producer,registry,packetPath:packetSnapshotPath,outputRoot:root,expectedOutputRoot:root,publicInventory:inventory,now});}catch(error){errorMessage=error.message;result=error.producerReceipt??{alerts:[{type:'editorial-service-failed',reason:error.message}],proposals:[]};}
 // Stabilise producer files on disk before durable service admission; no byte modifications.
 if(result.runId&&/^[a-f0-9-]{36}$/.test(result.runId)){for(const file of ['pending.json','receipt.json',...(result.captures??[]).map(c=>c.file)]){if(!/^[a-zA-Z0-9-]+\.json$/.test(file))throw Error('Unsafe producer file binding');const producerFile=path.join(root,result.runId,file);if((await lstat(producerFile)).isSymbolicLink())throw Error('Producer receipt symlink refused');const handle=await open(producerFile,'r+');try{await handle.sync();}finally{await handle.close();}}await syncDirectory(path.join(root,result.runId));}
 if((await checkedRead(configPath,16384)).hash!==configHash||(await checkedRead(config.registryPath,256*1024)).hash!==config.registryHash||(await checkedRead(config.packetPath,64*1024**2)).hash!==packet.hash)throw Error('Service inputs changed during preparation');await assertInventoryUnchanged(inventory);
 const episodes=structuredClone(previousEpisodes);if(!Array.isArray(episodes.episodes)||episodes.episodes.length>2000)throw Error('Episode budget/shape');
 const active=new Set(),outboxProposals=[];for(const alert of result.alerts??[]){const key=hash({candidateId:alert.candidateId??null,type:alert.type,reason:alert.reason??null,reasons:alert.reasons??null});active.add(key);let episode=episodes.episodes.find(e=>e.key===key&&e.state==='open');if(!episode){episode={key,id:randomUUID(),state:'open',firstSeenAt:now.toISOString(),lastSeenAt:now.toISOString(),alert,humanAcknowledged:false};episodes.episodes.push(episode);outboxProposals.push({episodeId:episode.id,key,kind:'actionable',alert,humanAcknowledged:false});}else episode.lastSeenAt=now.toISOString();}
 for(const episode of episodes.episodes.filter(e=>e.state==='open'))if(!active.has(episode.key)&&!errorMessage){episode.state='resolved';episode.resolvedAt=now.toISOString();outboxProposals.push({episodeId:episode.id,key:episode.key,kind:'recovery',humanAcknowledged:false});}
 if(episodes.episodes.length>2000)throw Error('Episode budget exhausted; no history deletion');
 const expiries=(result.proposals??[]).filter(p=>p.action==='review-content-patch').map(p=>Date.parse(p.record?.expiresAt)).filter(Number.isFinite);const deadline=Math.max(+now,Math.min(+now+(errorMessage||result.alerts?.length?15*60000:12*3600000),...expiries.map(expiry=>expiry-15*60000)));
 const ledgerHash=hash(JSON.stringify(episodes,null,2));
 const receipt={...base,ledgerHash,previousHead:pointer?.value??null,state:errorMessage?'failed':'complete',deadline:new Date(deadline).toISOString(),producerRunId:result.runId??null,proposals:errorMessage?[]:result.proposals??[],alerts:result.alerts??[],outboxProposals,error:errorMessage};
 if(kernelMode)await kernelGuard(root,config);await durable(path.join(dir,'episode-ledger.json'),episodes,{exclusive:true});await checkpoint('ledger');await durable(path.join(dir,'service-receipt.json'),receipt,{exclusive:true});await checkpoint('receipt');const currentHead=await optionalRead(path.join(root,'latest.json'));if((currentHead?.hash??null)!==(pointer?.hash??null))throw Error('Service head changed during preparation');const afterStorage=await capacity(root,config.storage);if(afterStorage.bytes>config.storage.maxBytes||afterStorage.runs>config.storage.maxRuns)throw Error('Service storage budget exceeded before commit');if(kernelMode)await kernelGuard(root,config);await durable(path.join(root,'latest.json'),{runId,hash:hash(JSON.stringify(receipt,null,2)),ledgerHash});await checkpoint('head');return receipt;
 }catch(error){if(serviceDirectory&&serviceBase){const failed={...serviceBase,state:'failed',proposals:[],alerts:[{type:'editorial-service-preparation-failed',reason:error.message}],outboxProposals:[],error:error.message};try{await durable(path.join(serviceDirectory,'failure.json'),failed,{exclusive:true});error.serviceReceipt=failed;}catch(persistenceError){error.persistenceFailure=persistenceError.message;}}throw error;}finally{await lock.close();if(!kernelMode){const owner=await optionalRead(lockPath);const currentLock=owner?await lstat(lockPath):null;if(owner?.value.token===token&&currentLock.dev===lockIdentity?.dev&&currentLock.ino===lockIdentity?.ino&&JSON.stringify(owner.value.identity)===JSON.stringify(identity)){await unlink(lockPath);await syncDirectory(root);}}}
}
