import test from 'node:test';import assert from 'node:assert/strict';import {hash} from './data.mjs';import {evaluateEditorial,editorialDecisionCurrent} from './editorial-policy.mjs';
const now=new Date('2026-10-06T00:00:00Z');
function fixture(){const fields={title:'Official fixture workshop',venueName:'Fixture venue',officialEventUrl:'https://official.example/event',startDate:'2026-10-08T10:00:00+11:00',endDate:'2026-10-08T11:00:00+11:00',status:'scheduled'};const body=JSON.stringify({...fields,kind:'event',shire:{shire:'MORNINGTON PENINSULA SHIRE',venueName:fields.venueName}});const evidence=[{id:'e1',sourceId:'official',authority:'official',url:fields.officialEventUrl,body,hash:hash(body),retrievedAt:now.toISOString()}];const candidate={id:'fixture-event-001',kind:'event',timezone:'Australia/Melbourne',fields,geography:{shireConfirmed:true,evidenceId:'e1'},proofs:Object.fromEntries(Object.entries({...fields,kind:'event',shire:{shire:'MORNINGTON PENINSULA SHIRE',venueName:fields.venueName}}).map(([k,value])=>[k,{evidenceId:'e1',pointer:'/'+k,value}]))};const options={now,registry:[{id:'official',authority:'official',url:fields.officialEventUrl,hosts:['official.example']}],catalogue:[candidate],catalogueComplete:true};return {candidate,evidence,options};}
test('full evidence-bound automated evaluation is10, no personal approval or prominence',()=>{const f=fixture(),d=evaluateEditorial(f.candidate,f.evidence,f.options);assert.equal(d.score,10);assert.equal(d.decision,'publish-eligible');assert.equal(d.personalApproval,null);assert.equal(d.prominenceEligible,false);assert.equal(editorialDecisionCurrent(d,f.candidate,f.evidence,f.options),true);});
test('score alone, authority flag, bogus pointer and hash changes cannot publish',()=>{for(const change of [f=>f.evidence[0].hash='a'.repeat(64),f=>f.options.registry=[],f=>f.candidate.proofs.title.pointer='/venueName',f=>f.evidence[0].url='https://official.example/not-admitted']){const f=fixture();change(f);assert.equal(evaluateEditorial(f.candidate,f.evidence,f.options).decision,'hold');}});
test('freshness24h near and72h later, expiry/revision/source mutation withdraw',()=>{const f=fixture(),d=evaluateEditorial(f.candidate,f.evidence,f.options);assert.equal(d.maxAgeHours,24);assert.equal(editorialDecisionCurrent(d,f.candidate,f.evidence,{...f.options,now:new Date(+now+24*3600000)}),false);f.candidate.fields.title='Changed';assert.equal(editorialDecisionCurrent(d,f.candidate,f.evidence,f.options),false);const later=fixture();later.candidate.fields.startDate='2026-11-08T10:00:00+11:00';assert.equal(evaluateEditorial(later.candidate,later.evidence,later.options).maxAgeHours,72);});
test('critical unknowns and unresolved existing holds remain held',()=>{const f=fixture();delete f.candidate.proofs.shire;const d=evaluateEditorial(f.candidate,f.evidence,f.options);assert.equal(d.decision,'hold');assert.equal(d.score,8.5);const p=fixture();assert.equal(evaluateEditorial(p.candidate,p.evidence,{...p.options,priorHold:{id:'hold1'}}).decision,'hold');});
test('missing optional price/image permitted; unsupported supplied price/image cannot gain points',()=>{const f=fixture();f.candidate.price={label:'Free',checkedAt:now.toISOString(),validUntil:'2026-10-07T00:00:00Z'};assert.equal(evaluateEditorial(f.candidate,f.evidence,f.options).decision,'hold');const m=fixture();m.candidate.media={url:'https://official.example/photo'};const d=evaluateEditorial(m.candidate,m.evidence,m.options);assert.equal(d.score,9.5);assert.equal(d.decision,'hold');});
test('duplicate canonical catalogue and unknown kind are held',()=>{const f=fixture();f.options.catalogue.push({...f.candidate,id:'second-event-001'});assert.equal(evaluateEditorial(f.candidate,f.evidence,f.options).decision,'hold');const k=fixture();k.candidate.kind='unknown';assert.equal(evaluateEditorial(k.candidate,k.evidence,k.options).decision,'hold');});
test('forged decision score and candidate personal-review booleans cannot grant eligibility',()=>{const f=fixture();delete f.candidate.proofs.title.pointer;Object.assign(f.candidate.proofs.title,{verifiedBy:'James',verified:true,quote:'Official fixture workshop'});assert.equal(evaluateEditorial(f.candidate,f.evidence,f.options).decision,'hold');const good=fixture(),d=evaluateEditorial(good.candidate,good.evidence,good.options);const forged={...d,score:100};assert.equal(editorialDecisionCurrent(forged,good.candidate,good.evidence,good.options),false);});
test('impossible civil date with exact source value is held; unrelated stale source has no effect',()=>{const f=fixture();f.candidate.fields.startDate='2026-02-30';f.candidate.proofs.startDate.value='2026-02-30';const raw=JSON.parse(f.evidence[0].body);raw.startDate='2026-02-30';f.evidence[0].body=JSON.stringify(raw);f.evidence[0].hash=hash(f.evidence[0].body);assert.equal(evaluateEditorial(f.candidate,f.evidence,f.options).decision,'hold');const g=fixture();g.evidence.push({...g.evidence[0],id:'unrelated',retrievedAt:'2020-01-01T00:00:00Z'});assert.equal(evaluateEditorial(g.candidate,g.evidence,g.options).decision,'publish-eligible');});
test('candidate-level prose and assets cannot bypass copy/media checks',()=>{const f=fixture();f.candidate.summary='Free tickets guaranteed';assert.equal(evaluateEditorial(f.candidate,f.evidence,f.options).decision,'hold');const a=fixture();a.candidate.assets=[{url:'https://official.example/photo'}];assert.equal(evaluateEditorial(a.candidate,a.evidence,a.options).decision,'hold');});
test('distinct dated sessions may share canonical URL',()=>{const f=fixture();f.options.catalogue.push({...f.candidate,id:'different-session',fields:{...f.candidate.fields,startDate:'2026-11-08T10:00:00+11:00'}});assert.equal(evaluateEditorial(f.candidate,f.evidence,f.options).decision,'publish-eligible');});
test('every advertised receipt field is bound, including expiry checks score evidence and authority',()=>{const f=fixture(),d=evaluateEditorial(f.candidate,f.evidence,f.options);for(const [key,value] of Object.entries({expiresAt:'2030-01-01T00:00:00Z',checks:{},score:9,evidence:[],authority:'James',personalApproval:{by:'James'},prominenceEligible:true,policyVersion:'future',checkedAt:'2026-10-05T00:00:00Z',revision:'forged',decisionHash:'forged'})){assert.equal(editorialDecisionCurrent({...d,[key]:value},f.candidate,f.evidence,f.options),false,key);}});
