import {conflictsWithInventory} from '../../next/scripts/event-editorial-inventory.mjs';
import path from 'node:path';import {readFile,lstat,realpath} from 'node:fs/promises';import {hash} from './data.mjs';import {buildEditorialManifest} from './editorial-automation.mjs';
/** Proposed prebuild adapter. Arguments are trusted build config, never HTTP/CMS candidate inputs. */
export async function validateEditorialBuild({enabled=false,storeRoot,expectedStoreRoot,planPath,registryPath,expectedRegistryHash,now=new Date(),maxCaptureBytes=32*1024**2,publicInventory}={}){
 if(enabled!==true)return buildEditorialManifest([],{now,enabled:false});
 if(!Array.isArray(publicInventory?.entries)||!/^([a-f0-9]{64})$/.test(publicInventory?.fingerprint??''))throw Error('Complete public inventory required');
 const root=await realpath(storeRoot),expected=await realpath(expectedStoreRoot);if(root!==expected)throw Error('Expected private capture-store root mismatch');
 async function readBounded(file,max){if((await lstat(file)).isSymbolicLink())throw Error('Build input symlink refused');const resolved=await realpath(file),rel=path.relative(root,resolved);if(rel.startsWith('..')||path.isAbsolute(rel))throw Error('Build input escapes private capture store');const info=await lstat(resolved);if(!info.isFile()||info.size>max)throw Error('Build input byte budget');const bytes=await readFile(resolved);if(bytes.length!==info.size)throw Error('Build input changed while reading');return {value:JSON.parse(bytes),hash:hash(bytes.toString())};}
 const planInput=await readBounded(planPath,256*1024),plan=planInput.value;if(plan.schemaVersion!==1||!Array.isArray(plan.items)||plan.items.length>1000||!plan.packet?.hash)throw Error('Malformed trusted editorial build plan');
 const registryResolved=await realpath(registryPath);if((await lstat(registryPath)).isSymbolicLink()||(await lstat(registryResolved)).size>256*1024||!/^([a-f0-9]{64})$/.test(expectedRegistryHash??''))throw Error('Pinned trusted registry required');const registryBytes=await readFile(registryResolved);if(hash(registryBytes.toString())!==expectedRegistryHash)throw Error('Registry pin changed');const registryDocument=JSON.parse(registryBytes),registry=registryDocument.sources??registryDocument;if(!Array.isArray(registry))throw Error('Registry array required');
 const packetInput=await readBounded(path.join(root,plan.packet.file),64*1024**2);if(packetInput.hash!==plan.packet.hash||!Array.isArray(packetInput.value.candidates)||packetInput.value.candidates.length>5000)throw Error('Review packet pin/shape changed');const catalogue=packetInput.value.candidates,items=[],captureReads=[],captureCache=new Map();let captureBytes=0;if(!Number.isSafeInteger(maxCaptureBytes)||maxCaptureBytes<1||maxCaptureBytes>32*1024**2)throw Error("Aggregate capture budget invalid");
 for(const item of plan.items){const matches=catalogue.filter(c=>c.id===item.candidateId);if(matches.length!==1)throw Error('Candidate catalogue identity ambiguous');const evidence=[],bundle={schemaVersion:1,candidateId:item.candidateId,revision:item.revision,optionalOmissions:item.optionalOmissions??[]};for(const role of ['primary','registration','boundary']){const ref=item[role];if(!ref?.file)throw Error('Capture reference required');const capturePath=path.join(root,ref.file),resolvedCapture=await realpath(capturePath);if((await lstat(capturePath)).isSymbolicLink())throw Error('Build input symlink refused');const captureRel=path.relative(root,resolvedCapture);if(captureRel.startsWith('..')||path.isAbsolute(captureRel))throw Error('Build input escapes private capture store');let read=captureCache.get(resolvedCapture);if(read&&read.hash!==ref.fileHash)throw Error('Shared capture pin mismatch');if(!read){const info=await lstat(resolvedCapture);captureBytes+=info.size;if(captureBytes>maxCaptureBytes)throw Error('Aggregate capture byte budget');read=await readBounded(capturePath,3*1024**2);captureCache.set(resolvedCapture,read);captureReads.push({file:capturePath,hash:read.hash});}const capture=read.value;if(!/^([a-f0-9]{64})$/.test(ref.fileHash??'')||read.hash!==ref.fileHash)throw Error('Capture metadata pin changed');if(capture.id!==ref.id||capture.hash!==ref.hash||typeof capture.body!=='string'||hash(capture.body)!==ref.hash)throw Error('Capture pin changed');evidence.push(capture);bundle[role]={id:ref.id,hash:ref.hash};}items.push({candidate:matches[0],evidence,bundle});}
 for(const read of captureReads)if((await readBounded(read.file,3*1024**2)).hash!==read.hash)throw Error('Capture changed during validation');
 // Re-read all mutable inputs after loading; refuse TOCTOU plan/packet/registry drift.
 if((await readBounded(planPath,256*1024)).hash!==planInput.hash||(await readBounded(path.join(root,plan.packet.file),64*1024**2)).hash!==packetInput.hash||hash((await readFile(registryResolved)).toString())!==expectedRegistryHash)throw Error('Trusted build inputs changed during validation');
 const manifest=buildEditorialManifest(items,{enabled:true,now,registry,catalogue,catalogueComplete:true});const conflicts=manifest.records.flatMap(record=>conflictsWithInventory(record,publicInventory).map(reason=>({eventId:record.eventId,reason})));if(conflicts.length)throw Error('Public canonical inventory conflict');
 return {...manifest,inputBinding:{publicInventoryFingerprint:publicInventory.fingerprint,planHash:planInput.hash,packetHash:packetInput.hash,registryHash:expectedRegistryHash,uniqueCaptureCount:captureCache.size,uniqueCaptureBytes:captureBytes}};
}
