import {createHash} from 'node:crypto';
import {parse} from '../../next/node_modules/parse5/dist/index.js';
import {hash,safeUrl} from './data.mjs';
import {editorialDecisionCurrent} from './editorial-policy.mjs';
export const IMAGE_POLICY_VERSION='pi-image-1.0';
/** Trusted registry is deployment configuration, never metadata extracted from the page. No network calls. */
export function discoverImageCandidates(capture,{registry=[],maxRefs=100,maxBytes=2_000_000,maxNodes=25000}={}){
 if(!Number.isInteger(maxRefs)||maxRefs<1||maxRefs>500||!Number.isInteger(maxBytes)||maxBytes<1||maxBytes>2_000_000||!Number.isInteger(maxNodes)||maxNodes<1||maxNodes>50000)throw Error('Invalid discovery bounds');
 const registered=registry.find(s=>s.id===capture.sourceId&&s.authority==='official');if(!registered||capture.authority!=='official'||typeof capture.body!=='string'||Buffer.byteLength(capture.body)>maxBytes||hash(capture.body)!==capture.hash)throw Error('Trusted captured official bytes required');
 safeUrl(capture.url,registered.hosts);if(capture.url!==registered.url&&!registered.admittedUrls?.includes(capture.url))throw Error('Unadmitted source URL');
 const refs=[],seen=new Set(),rejected=[];let nodes=0,incomplete=false;const assetHosts=registered.assetHosts??registered.hosts;
 function add(value,kind,locator,alt=null){if(typeof value!=='string'||!value.trim())return;try{const u=safeUrl(new URL(value,capture.url).href,assetHosts);u.hash='';if(seen.has(u.href))return;seen.add(u.href);if(refs.length>=maxRefs){incomplete=true;return;}refs.push({url:u.href,kind,locator,alt:typeof alt==='string'?alt:null,sourceId:capture.sourceId,sourceUrl:capture.url,captureHash:capture.hash,retrievedAt:capture.retrievedAt,reusePermission:'unknown',eventRelevance:'unreviewed',downloaded:false});}catch{if(rejected.length<maxRefs)rejected.push({reason:'unsafe-or-unadmitted-asset-reference'});}}
 function json(v,loc,depth=0){if(depth>20){incomplete=true;return;}if(++nodes>maxNodes){incomplete=true;return;}if(Array.isArray(v)){v.forEach((x,i)=>json(x,loc+'/'+i,depth+1));return;}if(v&&typeof v==='object'){for(const [k,x] of Object.entries(v)){if(k==='image'||k==='thumbnailUrl'){const items=Array.isArray(x)?x:[x];for(const image of items){if(typeof image==='string')add(image,'jsonld',loc+'/'+k);else if(image&&typeof image==='object')add(image.contentUrl??image.url,'jsonld',loc+'/'+k);}}if(x&&typeof x==='object')json(x,loc+'/'+k,depth+1);}}}
 function walk(node,loc,depth=0){if(depth>128){incomplete=true;return;}if(++nodes>maxNodes){incomplete=true;return;}const a=Object.fromEntries((node.attrs??[]).map(x=>[x.name,x.value]));if(node.tagName==='img'||node.tagName==='source'){if(node.tagName==='img')add(a.src,'img',loc+'/src',a.alt);for(const item of String(a.srcset??'').split(','))add(item.trim().split(/\s+/)[0],'srcset',loc+'/srcset',a.alt);}if(node.tagName==='meta'&&['og:image','og:image:url','twitter:image'].includes((a.property??a.name??'').toLowerCase()))add(a.content,'social-meta',loc+'/content');if(node.tagName==='script'&&(a.type??'').toLowerCase()==='application/ld+json'){try{json(JSON.parse((node.childNodes??[]).map(n=>n.value??'').join('')),loc+'/jsonld');}catch{rejected.push({reason:'invalid-jsonld'});}}for(const [i,child] of (node.childNodes??[]).entries())walk(child,loc+'/'+i,depth+1);}
 walk(parse(capture.body),'document');return {policyVersion:IMAGE_POLICY_VERSION,sourceUrl:capture.url,captureHash:capture.hash,refs,rejected,incomplete,discoveredCount:refs.length,permissionGranted:false};
}
const stamp=v=>typeof v==='string'&&/T.*(?:Z|[+-]\d\d:\d\d)$/.test(v)&&Number.isFinite(Date.parse(v));
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
/** assetRecords/inspection/licence receipts must come from trusted private review state, never page metadata. */
export function evaluateImageAsset(asset,{listing,listingDecision,listingEvidence=[],editorialOptions={},assetBytes,assetRecords=[],now=new Date(),channel='web',humanHold=null}={}){
 const time=+now;if(!Number.isFinite(time))throw Error('Valid clock required');const reasons=[],checks={};const record=assetRecords.find(r=>r.assetHash===asset.hash&&r.sourceUrl===asset.sourceUrl);
 const listingCurrent=listing&&editorialDecisionCurrent(listingDecision,listing,listingEvidence,{...editorialOptions,now});checks.listing=Boolean(listingCurrent);
 checks.source=Buffer.isBuffer(assetBytes)&&assetBytes.length<=15*1024**2&&createHash('sha256').update(assetBytes).digest('hex')===asset.hash&&Boolean(record)&&['organiser','press','local','branded'].includes(record?.origin); // Standard SHA256 of raw bytes, never a URL identity.
 const fresh=record&&stamp(record.checkedAt)&&stamp(record.expiresAt)&&Date.parse(record.checkedAt)<=time&&time<Date.parse(record.expiresAt)&&Date.parse(record.expiresAt)-Date.parse(record.checkedAt)<=72*3600000;
 checks.edition=Boolean(fresh)&&record.eventId===listing?.id&&record.edition===asset.edition&&record.listingRevision===listingDecision?.revision;
 const licence=record?.licence;let safeSources=true;try{if(typeof asset.sourceUrl!=='string')throw Error('Source required');if(asset.sourceUrl.startsWith('/images/')){if(!/^\/images\/[A-Za-z0-9_/-]+\.(?:png|jpe?g|webp|avif|svg)$/.test(asset.sourceUrl)||asset.sourceUrl.includes('..'))throw Error('Unsafe local reference');}else safeUrl(asset.sourceUrl);if(record?.origin==='local'||record?.origin==='branded'){const own=record.localOwnership;if(!own?.registryId||!/^([a-f0-9]{64})$/.test(own.registryHash??'')||!/^([a-f0-9]{64})$/.test(own.sourceCaptureHash??''))throw Error('Local ownership lineage required');safeUrl(own.sourceEvidenceUrl);}safeUrl(licence?.evidenceUrl);}catch{safeSources=false;}checks.rights=safeSources&&Boolean(licence)&&licence.grantState==='active'&&licence.revoked===false&&stamp(licence.grantedAt)&&Date.parse(licence.grantedAt)<=time&&typeof licence.permissionBody==='string'&&licence.permissionBody.length>=10&&hash(licence.permissionBody)===licence.permissionHash&&licence.channels?.includes(channel)&&stamp(licence.expiresAt)&&time<Date.parse(licence.expiresAt)&&(!licence.creditRequired||Boolean(record.credit?.trim()));
 const inspection=record?.inspection;checks.relevance=Boolean(inspection)&&inspection.assetHash===asset.hash&&inspection.listingRevision===listingDecision?.revision&&['exact-event','venue-context','original-graphic'].includes(inspection.subject)&&inspection.reviewedAt===record.checkedAt;
 if(inspection?.subject==='original-graphic'&&(record?.origin!=='branded'||record.localOwnership?.creationKind!=='original-pi-graphic'))checks.relevance=false;
 if(inspection?.subject==='venue-context'&&(!record.caption?.includes('Venue context')||inspection.venueName!==listing?.fields?.venueName))checks.relevance=false;
 if(inspection?.subject==='exact-event'&&(inspection.eventId!==listing?.id||inspection.edition!==asset.edition))checks.relevance=false;
 const ocr=inspection?.ocr;checks.ocr=Boolean(ocr)&&['no-text','reviewed-text'].includes(ocr.state)&&!ocr.conflicts?.length&&Object.entries(ocr.facts??{}).every(([k,v])=>same(listing?.fields?.[k],v));if(ocr?.state==='reviewed-text'&&!Object.keys(ocr.facts??{}).length)checks.ocr=false;
 checks.privacy=inspection?.privacy?.state==='cleared'&&(!inspection.privacy.sensitive||Boolean(inspection.privacy.permissionHash&&inspection.privacy.permissionBody&&hash(inspection.privacy.permissionBody)===inspection.privacy.permissionHash));
 const width=inspection?.width,height=inspection?.height;checks.quality=Number.isInteger(width)&&Number.isInteger(height)&&width>=600&&height>=315&&inspection.cropReviewed===true&&licence?.cropAllowed===true;
 checks.accessibility=typeof record?.alt==='string'&&record.alt.trim().length>=8&&!/<[^>]*>/.test(record.alt)&&(!record.credit||typeof record.credit==='string');
 if(humanHold)reasons.push('explicit-human-hold');for(const [k,v] of Object.entries(checks))if(!v)reasons.push('critical:'+k);
 const score=(checks.rights?3:0)+(checks.relevance?3:0)+(checks.edition?1:0)+(checks.ocr?1:0)+(checks.accessibility?1:0)+(checks.quality?(width>=1200&&height>=630?1:0.5):0);
 const decision=score>=9&&!reasons.length?'asset-eligible':'omit';const expiry=record?Math.min(Date.parse(record.expiresAt),Date.parse(licence?.expiresAt),Date.parse(listingDecision?.expiresAt)):time;const result={policyVersion:IMAGE_POLICY_VERSION,decision,score,checks,reasons,assetHash:asset.hash,sourceUrl:asset.sourceUrl,listingRevision:listingDecision?.revision??null,checkedAt:now.toISOString(),expiresAt:Number.isFinite(expiry)?new Date(expiry).toISOString():now.toISOString(),contextHash:record?hash(record):null,personalApproval:null};return {...result,decisionHash:hash(result)};
}
export function imageDecisionCurrent(decision,asset,context){try{const original=evaluateImageAsset(asset,{...context,now:new Date(decision.checkedAt)}),current=evaluateImageAsset(asset,context);return decision.decision==='asset-eligible'&&original.decision==='asset-eligible'&&same(original,decision)&&current.decision==='asset-eligible'&&+(context.now??new Date())>=Date.parse(decision.checkedAt)&&+(context.now??new Date())<Date.parse(decision.expiresAt);}catch{return false;}}
export function imageFallback({listing,listingDecision,listingEvidence=[],editorialOptions={},now=new Date()}={}){const current=listing&&editorialDecisionCurrent(listingDecision,listing,listingEvidence,{...editorialOptions,now});return {choice:current?'original-factual-branded-graphic':'text-only',factsPermitted:current,photographFabricationPermitted:false,publicationAuthorityGranted:false};}
