import {materializeSeries} from './series.mjs';
import {candidateRevision,htmlEscape} from './data.mjs';
import {verifyCandidate} from './verify.mjs';
import {productionDecision} from './editorial.mjs';
export function approvalReady(candidate,evidence,now=new Date()) {
 const verification=verifyCandidate(candidate,evidence,{now});
 const decision=productionDecision(candidate,verification);
 const approval=candidate.approval;
 const ready=verification.ready&&decision.path!=='review'&&approval?.by==='James'&&approval.revision===candidateRevision(candidate)&&new Date(approval.at)<=now;
 return {ready,verification,decision};
}
export function astroRecord(candidate,evidence,{now=new Date()}={}) {
 const series = candidate.series ? materializeSeries(candidate) : null;
 const checked=approvalReady(candidate,evidence,now);
 if(!checked.ready)throw new Error('Current revision requires James approval and verified essential evidence');
 if(!candidate.fields.startDate)throw new Error('Undated experience requires existing experiences adapter; do not invent a date');
 const f=candidate.fields;const start=f.startDate.slice(0,10);const end=f.endDate?.slice(0,10);
 const slug=candidate.slug??candidate.id;if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw new Error('Invalid slug');
 return {slug,eventId:candidate.id,contentKind:candidate.kind,title:f.title,summary:candidate.summary,category:candidate.category,startDate:start,...(end?{endDate:end}:{}),...(f.startDate.includes('T')?{startTime:f.startDate.slice(11,16)}:{}),...(f.endDate?.includes('T')?{endTime:f.endDate.slice(11,16)}:{}),venueName:f.venueName,suburb:f.suburb,streetAddress:f.streetAddress,officialEventUrl:f.officialEventUrl,primarySourceUrl:f.officialEventUrl,bookingUrl:f.bookingUrl,bookingStatus:f.bookingStatus??'unknown',timezone:'Australia/Melbourne',recurrence:series?.contract.recurrence??'one-off',...(series?{startDate:candidate.series.validFrom,endDate:candidate.series.validUntil,recurrenceNote:series.contract.recurrenceNote,seriesOccurrences:series.occurrences.map(({id,originalDate,date,status,startTime,endTime,venueName,sourceUrl,note})=>({id,originalDate,date,status,startTime,endTime,venueName,sourceUrl,...(note?{note}:{})})),...(f.startTime?{startTime:f.startTime}:{}),...(f.endTime?{endTime:f.endTime}:{})}:{}),status:'review',publishedAt:now.toISOString(),lastCheckedDate:now.toISOString(),lastVerifiedAt:now.toISOString(),...(candidate.price?{verifiedPrice:{...candidate.price,sourceUrl:evidence.find(e=>e.id===candidate.proofs.price.evidenceId).url}}:{}),intelligence:{revision:candidateRevision(candidate),approvedBy:'James',approvedAt:candidate.approval.at,reviewedAt:checked.verification.checkedAt,factScore:checked.verification.factScore,evidenceIds:[...new Set(Object.values(candidate.proofs).map(p=>p.evidenceId))]}};
}
const reviewReasons={'shire-evidence-required':'Confirm that the venue is within Mornington Peninsula Shire.','scope-source-required':'Add an authoritative source for the location.','scope-not-verified':'Check and confirm the location evidence.','not-scheduled':'Confirm the current event status.','invalid-date':'Check the date, time and timezone supplied by the source.','event-date-required':'Add a confirmed event date.','source-change-needs-review':'Compare changed source details with the previous review.','unresolved-conflict':'Resolve conflicting source details.','past-event':'This occurrence has ended.','past-offer':'This offer has expired.'};
function reviewReason(code){if(reviewReasons[code])return reviewReasons[code];if(code.startsWith('missing-'))return 'Confirm '+code.slice(8).replace(/([a-z])([A-Z])/g,'$1 $2').toLowerCase()+'.';if(code.startsWith('scope-moved'))return 'Confirm the changed venue is within the Shire.';return code.replace(/-/g,' ').replace(/^./,char=>char.toUpperCase())+'.';}
const fieldLabels={title:'Name',startDate:'Start date supplied by source',endDate:'End date supplied by source',venueName:'Venue',streetAddress:'Address',suburb:'Town',officialEventUrl:'Source page',organiser:'Organiser',status:'Status supplied by source'};
export function reviewHtml(candidates,evidence,health={}) {
 const cards=candidates.map(c=>{const v=verifyCandidate(c,evidence);const past=v.errors.some(e=>['past-event','past-offer'].includes(e));return `<article data-kind="${htmlEscape(c.kind)}" data-past="${past}" ${past?'hidden':''}><h2>${htmlEscape(c.fields.title??c.id)}</h2><p>Proposed ${htmlEscape(c.kind)} · ${htmlEscape(c.fields.suburb??'Location needs review')} · ${v.factScore===0?'Awaiting fact checks':v.factScore+'/100 required fields confirmed'}</p><p>${htmlEscape(v.ready?'Verified fields; human publication approval required':[...new Set(v.errors.map(reviewReason))].join(' ')||'Field verification required')}</p><dl>${Object.entries(c.fields).map(([k,value])=>`<dt>${htmlEscape(fieldLabels[k]??k.replace(/([a-z])([A-Z])/g,'$1 $2'))}</dt><dd>${htmlEscape(typeof value==='object'?JSON.stringify(value):value)}</dd>`).join('')}</dl><details><summary>Captured evidence and missing verification</summary>${Object.entries(v.fields).map(([field,check])=>`<p><strong>${htmlEscape(field)}</strong>: ${htmlEscape(check.reasons.join(', ')||'verified')}<br>${htmlEscape(evidence.find(e=>e.id===check.evidenceId)?.url??'No captured evidence')}<br>${htmlEscape(c.proofs?.[field]?.quote??'No located quote')}</p>`).join('')}</details><p>Revision ${htmlEscape(candidateRevision(c))}</p></article>`;}).join('');
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PI event review</title><style>body{font:16px/1.6 system-ui;color:#14202A;background:#F2EFEA;max-width:1000px;margin:auto;padding:24px}article{background:white;padding:24px;margin:20px 0;border-left:5px solid #173C50}dt{font-weight:600}article[hidden]{display:none}details{background:#f5f4f0;padding:12px}pre{white-space:pre-wrap}dd{margin:0 0 12px;overflow-wrap:anywhere}</style><h1>Peninsula Insider event review</h1><p>Private review. Nothing on this page is a publication approval.</p><p>${candidates.length} candidates. Historical occurrences are hidden initially.</p><label><input id="history" type="checkbox"> Show historical occurrences</label> <label>Kind <select id="kind"><option value="all">All</option><option value="event">Events</option><option value="experience">Experiences</option><option value="offer">Offers</option></select></label><details><summary>Source health and coverage</summary><pre>${htmlEscape(JSON.stringify(health,null,2))}</pre></details>${cards}<script>function filter(){const history=document.getElementById('history').checked,kind=document.getElementById('kind').value;for(const article of document.querySelectorAll('article'))article.hidden=(!history&&article.dataset.past==='true')||(kind!=='all'&&article.dataset.kind!==kind);}document.getElementById('history').addEventListener('change',filter);document.getElementById('kind').addEventListener('change',filter);</script></html>`;
}
