import {fileDigest,snapshotPacket} from './packet-io.mjs';
import {mkdir,open,unlink,readFile,writeFile,rename,cp,stat,readdir,readlink,realpath} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {collect,readJson,atomicJson} from './collect.mjs';
import {createReviewedEvidenceFetcher} from './reviewed-redirect-fetch.mjs';
import {loadRedirectConfig} from './redirect-config.mjs';
import {collectDetails,extractDetail} from './details.mjs';
import {buildPacket} from './packet.mjs';
import {operationalReport} from './operations.mjs';
import {hash,safeUrl} from './data.mjs';
import {sourceNavigation} from './source-discovery.mjs';
import {reviewHtml,approvalReady} from './publication.mjs';
import {sourceCoverage} from './coverage.mjs';
import {isPublicEventRecord,currentVerifiedPrice} from '../../next/src/lib/event-publication.mjs';
import {nextSeriesData,hasExplicitSeries} from '../../next/src/lib/intelligence-series.mjs';
import {recordDisposition,dayIsoOf} from '../../next/src/lib/event-occurrence.mjs';
import {refreshPublishedFeed,recheckCatalog} from './catalog-rechecks.mjs';
import {loadOutbox,reconcileAlerts,deliverAlerts} from './outbox.mjs';
const exists=async file=>{try{await stat(file);return true;}catch(e){if(e.code==='ENOENT')return false;throw e;}};
const alive=pid=>{try{process.kill(pid,0);return true;}catch(e){return e.code!=='ESRCH';}};
export async function processIdentity(pid=process.pid){if(process.platform!=='linux')return {platform:process.platform,pid,startedAt:pid===process.pid?new Date(Date.now()-process.uptime()*1000).toISOString():null};try{const line=await readFile(`/proc/${pid}/stat`,'utf8');return {platform:'linux',pid,bootId:(await readFile('/proc/sys/kernel/random/boot_id','utf8')).trim(),namespace:await readlink(`/proc/${pid}/ns/pid`),startTicks:line.slice(line.lastIndexOf(')')+2).split(' ')[19]};}catch(e){if(e.code==='ENOENT')return null;throw e;}}
async function ownerAlive(owner){if(!alive(owner.pid))return false;if(owner.identity?.platform==='linux'){const current=await processIdentity(owner.pid);return !!current&&current.bootId===owner.identity.bootId&&current.namespace===owner.identity.namespace&&current.startTicks===owner.identity.startTicks;}if(owner.pid===process.pid&&owner.identity?.startedAt)return Math.abs(new Date(owner.identity.startedAt)-(Date.now()-process.uptime()*1000))<2000;return true;}
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function assertRuntimePath(directory,root=process.env.PI_EVENT_RUNTIME_ROOT??path.resolve('ops/reports/events/intelligence')){
 const target=path.resolve(directory),relative=path.relative(path.resolve(root),target);
 if(relative.startsWith('..')||path.isAbsolute(relative))throw new Error('Runtime must remain inside private event intelligence reports');return target;
}
export async function acquireRunLock(directory,{now=new Date(),staleMs=30*60*1000,isAlive}={}){
 await mkdir(directory,{recursive:true});const file=path.join(directory,'runner.lock'),token=randomUUID();let recovered=null;
 const identity=await processIdentity();const check=old=>isAlive?isAlive(old.pid):ownerAlive(old);
 try{const handle=await open(file,'wx');await handle.writeFile(JSON.stringify({token,pid:process.pid,identity,startedAt:now.toISOString()}));await handle.close();}
 catch(e){if(e.code!=='EEXIST')throw e;const old=await readJson(file);const age=now-new Date(old.startedAt);
  if(!Number.isInteger(old.pid)||!Number.isFinite(age)||(age<staleMs&&!old.identity)||await check(old))throw new Error('Event cycle already active or lock ownership cannot be safely recovered');
  // Rename preserves the abandoned lock as a recovery receipt; an active PID is never reclaimed.
  const recoveryFile=path.join(directory,'runner-recovery.lock'),recovery=await open(recoveryFile,'wx');
  try{const current=await readJson(file);if(current.token!==old.token||current.pid!==old.pid||current.startedAt!==old.startedAt||await check(current))throw new Error('Lock owner changed during recovery');
   const abandoned=path.join(directory,`abandoned-lock-${randomUUID()}.json`);await rename(file,abandoned);recovered={...old,receipt:abandoned};
   const handle=await open(file,'wx');await handle.writeFile(JSON.stringify({token,pid:process.pid,identity,startedAt:now.toISOString()}));await handle.close();
  }finally{await recovery.close();await unlink(recoveryFile);}
 }
 return {recovered,release:async()=>{const current=await readJson(file);if(current.token!==token)throw new Error('Cycle lock ownership changed');await unlink(file);}};
}
export function cycleAlerts(report,packet){const alerts=[...report.alerts];for(const change of packet.sourceChanges??[]){const c=packet.candidates.find(x=>x.id===change.id);if(c?.approval||c?.reviewStatus==='published')alerts.push({id:change.id,priority:'urgent',reason:'approved-source-changed',action:'reverify-and-withdrawal-check'});}return alerts;}
export function publishedAlerts(events,{now=new Date()}={}){
 const today=dayIsoOf(now),alerts=[];
 for(const event of events){if(!isPublicEventRecord(event,now)||event.status!=='published')continue;const id=event.slug??event.eventId;const effective=hasExplicitSeries(event)?nextSeriesData(event,now):event;const end=dayIsoOf(event.endDate??event.startDate);const next=dayIsoOf(effective?.nextOccurrence);const future=next&&next>=today;if(end&&end<today&&!future)alerts.push({id,priority:'urgent',reason:'published-expiry',action:'check-archive-and-discovery-removal'});
  if(['cancelled','postponed'].includes(recordDisposition(effective??event,now).status))alerts.push({id,priority:'urgent',reason:'published-cancellation',action:'check-public-status-and-booking-actions'});
  if(event.verifiedPrice&&!currentVerifiedPrice(event,now))alerts.push({id,priority:'urgent',reason:'published-price-expired',action:'renew-evidence-and-check-price-hidden'});
  const checked=event.lastVerifiedAt??event.lastCheckedDate;if(!checked||!Number.isFinite(new Date(checked).getTime())||now-new Date(checked)>7*86400000)alerts.push({id,priority:'normal',reason:'published-source-review-due',action:'recheck-source-facts'});
 }return alerts;
}
export function liveFeedAlerts(feed,{now=new Date()}={}){if(!feed)return [];const alerts=[];if(!Number.isFinite(new Date(feed.generatedAt).getTime())||now-new Date(feed.generatedAt)>24*3600000)alerts.push({priority:'normal',reason:'published-feed-build-stale',action:'check-deployment-freshness-not-factual-approval'});const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Melbourne',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);for(const event of feed.events){if(/EventCancelled|EventPostponed/.test(event.eventStatus??''))alerts.push({id:event.id,priority:'urgent',reason:'live-published-cancellation',action:'check-public-status-and-booking-actions'});if(event.endDate&&event.endDate<today)alerts.push({id:event.id,priority:'urgent',reason:'live-feed-expired-listing',action:'check-freshness-and-withdrawal'});}return alerts;}
export function detailHealth(receipt={}){const rows=receipt.receipts??[];return {admitted:receipt.admitted??null,pending:receipt.pending??null,complete:receipt.complete===true&&receipt.pending===0&&!rows.some(x=>['failed','backoff'].includes(x.status)),failed:rows.filter(x=>x.status==='failed').length,backoff:rows.filter(x=>x.status==='backoff').length,cached:rows.filter(x=>x.status==='cached').length,fetched:rows.filter(x=>x.status==='fetched').length,unsupportedMethods:'PDF/API/rendered form extraction requires separate explicit adapters; HTML completion is not regional completion'};}
export function detailAlerts(receipt={}){return (receipt.receipts??[]).filter(x=>['failed','backoff'].includes(x.status)).map(x=>({id:x.url,priority:'normal',reason:'detail-retrieval-failed',action:'investigate-detail-retrieval-and-retry',retrievalState:x.status}));}
async function currentCoverage(registry,packet,directory,now){let venues=[],venueError=null,boundaryEvidence=null,boundaryReview=null;try{const folder=fileURLToPath(new URL('../../next/src/content/venues/',import.meta.url));for(const file of (await readdir(folder)).filter(x=>x.endsWith('.json')))venues.push(await readJson(path.join(folder,file)));}catch(e){venueError=e.message;}
 try{boundaryEvidence=(await readJson(path.join(directory,'shire-boundary.json'))).evidence;}catch(e){if(e.code!=='ENOENT')throw e;}try{boundaryReview=await readJson(path.join(directory,'boundary-review.json'));}catch(e){if(e.code!=='ENOENT')throw e;}
 const coverage=sourceCoverage({venues,sources:registry.sources,...packet,boundaryEvidence,boundaryReview},{now});return {...coverage,generatedAt:now.toISOString(),registeredSourceDenominator:registry.sources.length,venueRecordDenominator:venues.length,venueInventoryError:venueError,confirmedShireCandidates:coverage.towns.reduce((n,x)=>n+x.confirmedCandidates,0),unconfirmedShireCandidates:coverage.towns.reduce((n,x)=>n+x.unconfirmedCandidates,0),sourceMethods:registry.sources.map(x=>({id:x.id,methods:x.retrievalMethods??['unspecified'],manualReviewRequired:x.manualReview===true}))};
}
export async function readPublishedCatalog(directory){if(!directory)return {events:[],hash:null};const events=[],snapshots=[];for(const file of (await readdir(directory)).filter(x=>x.endsWith('.json')).sort()){const body=await readFile(path.join(directory,file),'utf8');snapshots.push([file,body]);events.push(JSON.parse(body));}return {events,hash:hash(snapshots)};}
export async function runCycle(registry,directory,{now=new Date(),limit=20,force=false,maxDurationMs=20*60*1000,root,fetcher,detailFetcher,redirectReview,redirectConfigFile,sink,publishedEvents=[],catalogDirectory,monitorPublishedFeed=false,catalogFetcher,steps={},lockOptions={}}={}){
 directory=assertRuntimePath(directory,root);for(const source of registry.sources){if(!/^[a-z0-9][a-z0-9_-]*$/i.test(source.id))throw new Error('Unsafe source identifier');}
 await mkdir(directory,{recursive:true});const actualRoot=await realpath(root??process.env.PI_EVENT_RUNTIME_ROOT??path.resolve('ops/reports/events/intelligence'));assertRuntimePath(await realpath(directory),actualRoot);
 const lock=await acquireRunLock(directory,{now,...lockOptions}),id=randomUUID(),started=Date.now();const runDirectory=path.join(directory,'runs',id),stage=path.join(runDirectory,'stage');const packetFile=path.join(directory,'review-packet.json');let receipt={id,startedAt:now.toISOString(),state:'running',recoveredLock:lock.recovered,publicationChanges:[]};
 try{
  const catalog=await readPublishedCatalog(catalogDirectory);receipt.catalogHashBefore=catalog.hash;
  let liveFeed=null,feedError=null;if(monitorPublishedFeed)try{liveFeed=await refreshPublishedFeed(directory,{now,fetcher:catalogFetcher});receipt.deployment=liveFeed.deployment;}catch(e){feedError=e.message;}
  const monitored=liveFeed?liveFeed.events:[...publishedEvents,...catalog.events];const rechecks=(monitorPublishedFeed||catalogDirectory)?await recheckCatalog(monitored,registry,directory,{now,limit,fetcher:catalogFetcher}):{alerts:[]};
  await mkdir(path.join(stage,'details'),{recursive:true});const backupFile=path.join(runDirectory,'review-packet.before.json'),original=await snapshotPacket(packetFile,backupFile);receipt.packetHashAlgorithm='sha256-raw-bytes';receipt.packetHashBefore=original.hash;receipt.packetBytesBefore=original.byteLength;
  for(const source of registry.sources){const file=path.join(directory,`${source.id}.json`);if(await exists(file))await cp(file,path.join(stage,`${source.id}.json`));}
  for(const name of ['shire-boundary.json','boundary-review.json']){const file=path.join(directory,name);if(await exists(file))await cp(file,path.join(stage,name));}
  if(await exists(path.join(directory,'source-navigation')))await cp(path.join(directory,'source-navigation'),path.join(stage,'source-navigation'),{recursive:true});
  if(await exists(path.join(directory,'details')))await cp(path.join(directory,'details'),path.join(stage,'details'),{recursive:true});if(original.byteLength)await cp(backupFile,path.join(stage,'review-packet.json'));
  const checkpoint=async state=>{receipt.state=state;await atomicJson(path.join(runDirectory,'receipt.json'),receipt);if(Date.now()-started>maxDurationMs)throw new Error('Cycle watchdog deadline exceeded; staged changes held');};
  let adapterConfigError=null;let activeRedirectReview=redirectReview;
  if(redirectConfigFile)try{activeRedirectReview=await loadRedirectConfig(redirectConfigFile,{root:actualRoot,now});receipt.redirectAdapter={state:'enabled',reviewCount:activeRedirectReview.reviews.length};}catch(error){activeRedirectReview=undefined;adapterConfigError=String(error.message).slice(0,300);receipt.redirectAdapter={state:'failed-manual-fallback',error:adapterConfigError,mappingUsed:false};}
  const reviewedEvidenceFetcher=activeRedirectReview?.enabled?createReviewedEvidenceFetcher(activeRedirectReview):undefined;
  await checkpoint('collecting');await (steps.collect??collect)(registry,stage,{now,force,fetcher,evidenceFetcher:reviewedEvidenceFetcher});
  const captures=[];for(const source of registry.sources){const file=path.join(stage,`${source.id}.json`);if(await exists(file)){let capture=await readJson(file);if(capture.evidence&&capture.status!=='failed'){const extracted=extractDetail(capture.evidence);capture={...capture,candidates:extracted.candidates.length?extracted.candidates:capture.candidates,adapter:extracted.adapter,adapterWarnings:extracted.warnings};await atomicJson(file,capture);}captures.push(capture);}}
  let previousLeads=[];try{previousLeads=await readJson(path.join(directory,'discovery-leads.json'));if(!Array.isArray(previousLeads))throw new Error('Prior admitted discovery leads must be an array');}catch(e){if(e.code!=='ENOENT')throw e;}
  const discovered=captures.flatMap(x=>[...(x.leads??[]),...(x.evidence?sourceNavigation(x.evidence).map(link=>({...link,sourceId:x.sourceId,format:'html',retrievalAllowed:true})):[])]),admitted=new Map();
  // Retain previously admitted URLs even when a root no longer links them.
  // Root removal is evidence for review, never permission to drop monitoring.
  for(const lead of [...previousLeads,...discovered]){const source=registry.sources.find(x=>x.id===lead.sourceId);if(!source||lead.format!=='html'||lead.retrievalAllowed!==true)continue;try{const url=safeUrl(lead.url,source.hosts??[new URL(source.url).hostname]);admitted.set(url.href,{...lead,url:url.href});}catch{}}
  const leads=[...admitted.values()];receipt.priorAdmittedLeads=previousLeads.length;receipt.currentAdmittedLeads=leads.length;await atomicJson(path.join(stage,'discovery-leads.json'),leads);
  await checkpoint('details');const detailReceipt=await (steps.details??collectDetails)(registry,leads,stage,{now,limit,fetcher:detailFetcher??reviewedEvidenceFetcher});
  await checkpoint('review');const packet=await (steps.packet??buildPacket)(stage);const coverage=await currentCoverage(registry,packet,stage,now);const report=operationalReport({sources:registry.sources,receipts:captures,candidates:packet.candidates,evidence:packet.evidence},{now});report.details=detailHealth(detailReceipt);report.coverage={registeredSourceDenominator:coverage.registeredSourceDenominator,venueRecordDenominator:coverage.venueRecordDenominator,confirmedShireCandidates:coverage.confirmedShireCandidates,unconfirmedShireCandidates:coverage.unconfirmedShireCandidates,completeness:coverage.completeness,unknowns:coverage.unknowns};report.counts.approvedForPublication=packet.candidates.filter(x=>approvalReady(x,packet.evidence,now).ready).length;report.alerts=[...(adapterConfigError?[{id:"redirect-adapter",priority:"urgent",reason:"adapter-config-failed",action:"refresh-reviewed-redirect-config",error:adapterConfigError}]:[]),...cycleAlerts(report,packet),...detailAlerts(detailReceipt),...publishedAlerts([...publishedEvents,...catalog.events],{now}),...liveFeedAlerts(liveFeed,{now}),...rechecks.alerts,...(feedError?[{priority:'urgent',reason:'published-feed-monitor-failed',action:'inspect-live-feed-retrieval'}]:[])];
  await checkpoint('publishing-private-review');
  const currentPacket=await fileDigest(packetFile);if(currentPacket.hash!==original.hash||currentPacket.exists!==original.exists)throw new Error('Human review packet changed during collection; staged results retained for safe retry');
  // Only the private packet is replaced atomically. Original packet bytes and complete staged captures remain recoverable.
  await atomicJson(packetFile,packet);
  for(const file of (await readdir(stage)).filter(f=>f.endsWith('.json')&&f!=='review-packet.json'))await atomicJson(path.join(directory,file),await readJson(path.join(stage,file)));
  for(const file of await readdir(path.join(stage,'details')))if(file.endsWith('.json'))await atomicJson(path.join(directory,'details',file),await readJson(path.join(stage,'details',file)));
  await atomicJson(path.join(directory,'operational-report.json'),report);
  await atomicJson(path.join(directory,'coverage.json'),coverage);
  await writeFile(path.join(directory,'review.html.tmp'),reviewHtml(packet.candidates,packet.evidence,{health:report,coverage,'detail-receipt':detailReceipt}));await rename(path.join(directory,'review.html.tmp'),path.join(directory,'review.html'));
  const outbox=await deliverAlerts(directory,reconcileAlerts(await loadOutbox(directory),report.alerts,{now}),{now,sink});
  const dashboard='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>PI private event operations</title><style>body{max-width:72rem;margin:2rem auto;padding:0 1rem;font:16px/1.5 system-ui;background:#faf9f6;color:#17332d}li{margin:1rem 0;overflow-wrap:anywhere}code{font-size:.8rem;overflow-wrap:anywhere}</style><h1>Event operations</h1><p>Review proposals only. No automatic approval or publication.</p><p>'+escape(now.toISOString())+'</p><p>'+report.counts.candidates+' candidates; '+report.counts.awaitingReview+' awaiting review.</p><p>'+report.counts.approvedForPublication+' have verified current James approval. '+(report.counts.approvedForPublication===0?'No new research listing can be published. Continue factual review and approval.':'Publication remains a separate authorised step.')+'</p><h2>Collection and coverage</h2><p>HTML details: '+escape(report.details.admitted)+' admitted; '+escape(report.details.pending)+' pending; '+report.details.failed+' failed; '+report.details.backoff+' waiting for retry; '+report.details.cached+' cached; '+report.details.fetched+' fetched. HTML retrieval complete: '+report.details.complete+'.</p><p>'+escape(report.details.unsupportedMethods)+'</p><p>Registered sources: '+coverage.registeredSourceDenominator+'. Venue records: '+coverage.venueRecordDenominator+'. Confirmed Shire candidates: '+coverage.confirmedShireCandidates+'; unconfirmed: '+coverage.unconfirmedShireCandidates+'. Regional completeness: '+escape(coverage.completeness)+'.</p><ul>'+coverage.unknowns.map(x=>'<li>'+escape(x)+'</li>').join('')+'</ul><h2>Actionable alerts</h2><ul>'+outbox.items.filter(x=>x.state!=='resolved').map(x=>'<li>'+escape(x.alert.priority)+' — '+escape(x.alert.id??x.alert.sourceId)+' — '+escape(x.alert.reason).replaceAll('-',' ')+' ('+escape(x.state)+')<br><code>Alert '+escape(x.key)+' / episode '+x.episode+'</code></li>').join('')+'</ul><p><a href="review.html">Open private review</a></p></html>';
  const dashboardFile=path.join(directory,'operations.html');await writeFile(dashboardFile+'.tmp',dashboard);await rename(dashboardFile+'.tmp',dashboardFile);
  receipt.catalogHashAfter=(await readPublishedCatalog(catalogDirectory)).hash;if(receipt.catalogHashBefore!==receipt.catalogHashAfter)throw new Error('Read-only public catalogue changed during cycle; inspect independent changes');
  receipt={...receipt,state:'complete',completedAt:new Date().toISOString(),counts:report.counts,sourceFailures:captures.filter(x=>x.status==='failed').length,details:detailReceipt,packetHash:(await fileDigest(packetFile)).hash,pendingAlerts:outbox.items.filter(x=>x.state==='pending').length};await atomicJson(path.join(runDirectory,'receipt.json'),receipt);await atomicJson(path.join(directory,'last-cycle.json'),receipt);return receipt;
 }catch(e){receipt={...receipt,state:'failed',failedAt:new Date().toISOString(),error:String(e.message).slice(0,500)};await mkdir(runDirectory,{recursive:true});await atomicJson(path.join(runDirectory,'receipt.json'),receipt);await atomicJson(path.join(directory,'last-cycle.json'),receipt);
  const outbox=await loadOutbox(directory);const key=hash(['system','cycle-failed']);if(!outbox.items.some(x=>x.key===key&&x.state!=='resolved'))outbox.items.push({key,episode:outbox.items.filter(x=>x.key===key).length+1,alert:{priority:'urgent',reason:'cycle-failed',action:'inspect-private-cycle-receipt'},state:'pending',attempts:0,firstSeenAt:now.toISOString(),nextAttemptAt:now.toISOString()});await deliverAlerts(directory,outbox,{now,sink});throw e;
 }finally{await lock.release();}
}
export async function runDaemon(registry,directory,{intervalMs=15*60*1000,signal,...options}={}){
 if(!Number.isFinite(intervalMs)||intervalMs<1000)throw new Error('Daemon interval must be at least one second');
 directory=assertRuntimePath(directory,options.root);await mkdir(directory,{recursive:true});
 while(!signal?.aborted){let lastCycle,error;await atomicJson(path.join(directory,'runner-health.json'),{checkedAt:new Date().toISOString(),status:'running'});try{
  if(options.steps)lastCycle=await runCycle(registry,directory,options);
  else {await new Promise((resolve,reject)=>{const child=spawn(process.execPath,[fileURLToPath(import.meta.url),'--once',directory,String(options.limit??20),...(options.force?['--force']:[])],{stdio:'inherit',env:{...process.env,PI_EVENT_CATALOG_DIRECTORY:options.catalogDirectory??process.env.PI_EVENT_CATALOG_DIRECTORY??''}});const timeout=setTimeout(()=>{child.kill('SIGKILL');},options.maxDurationMs??20*60*1000);child.once('error',e=>{clearTimeout(timeout);reject(e);});child.once('close',(code,termination)=>{clearTimeout(timeout);code===0?resolve():reject(new Error(termination?'Cycle watchdog terminated child; private staging retained':'Cycle child failed with code '+code));});});lastCycle=await readJson(path.join(directory,'last-cycle.json'));}
 }catch(e){error=e.message;const failure={state:'failed',failedAt:new Date().toISOString(),error,publicationChanges:[]};await atomicJson(path.join(directory,'last-cycle.json'),failure);try{const dead=await readJson(path.join(directory,'runner.lock'));failure.owner=dead;await atomicJson(path.join(directory,'watchdog-failure.json'),failure);for(const id of await readdir(path.join(directory,'runs'))){const file=path.join(directory,'runs',id,'receipt.json');const value=await readJson(file);if(!['complete','failed'].includes(value.state))await atomicJson(file,{...value,...failure});}}catch(e){if(e.code!=='ENOENT')throw e;}
  const outbox=await loadOutbox(directory);const key=hash(['system','cycle-failed']);if(!outbox.items.some(x=>x.key===key&&x.state!=='resolved'))outbox.items.push({key,episode:outbox.items.filter(x=>x.key===key).length+1,alert:{priority:'urgent',reason:'cycle-failed',action:'inspect-private-cycle-receipt'},state:'pending',attempts:0,firstSeenAt:new Date().toISOString(),nextAttemptAt:new Date().toISOString()});await deliverAlerts(directory,outbox);}
  await atomicJson(path.join(directory,'runner-health.json'),{checkedAt:new Date().toISOString(),status:error?'failed':'waiting',lastCycle:lastCycle??null,error:error??null,nextRunAt:new Date(Date.now()+intervalMs).toISOString()});
  if(signal?.aborted)break;await new Promise(resolve=>{const timer=setTimeout(done,intervalMs);function done(){clearTimeout(timer);signal?.removeEventListener('abort',done);resolve();}signal?.addEventListener('abort',done,{once:true});});
 }await atomicJson(path.join(directory,'runner-health.json'),{checkedAt:new Date().toISOString(),status:'stopped'});
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 const args=process.argv.slice(2),positional=args.filter(x=>!x.startsWith('--'));const registry=await readJson(new URL('./sources.json',import.meta.url));const directory=positional[0]??process.env.PI_EVENT_RUNTIME_ROOT??'ops/reports/events/intelligence';const limit=Number(process.env.PI_EVENT_DETAIL_LIMIT??positional[1]??20);if(!Number.isInteger(limit)||limit<1||limit>100)throw new Error('Detail limit must be 1–100');const options={redirectConfigFile:process.env.PI_EVENT_REDIRECT_CONFIG,limit,force:args.includes('--force'),catalogDirectory:process.env.PI_EVENT_CATALOG_DIRECTORY,monitorPublishedFeed:process.env.PI_EVENT_MONITOR_PUBLISHED_FEED!=='false'};
 if(args.includes('--daemon')){const controller=new AbortController();process.once('SIGTERM',()=>controller.abort());process.once('SIGINT',()=>controller.abort());await runDaemon(registry,directory,{...options,signal:controller.signal,intervalMs:Number(process.env.PI_EVENT_INTERVAL_MS??900000)});}else console.log(JSON.stringify(await runCycle(registry,directory,options)));
}
