import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile,readFile,mkdir,lstat} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {runCycle} from './runner.mjs';import {loadSourceWorkerConfig} from './source-worker-config.mjs';import {atomicJson,readJson} from './collect.mjs';
const url='https://library.mornpen.vic.gov.au/Whats-On/Events',registry={sources:[{id:'libraries',url,hosts:['library.mornpen.vic.gov.au'],authority:'official',cadenceHours:24}]},now=new Date('2026-10-06T12:00:00Z');
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'pi-worker-config-'));t.after(()=>rm(root,{recursive:true,force:true}));await atomicJson(path.join(root,'review-packet.json'),{version:1,candidates:[{id:'human',kind:'event',fields:{title:'Retain human work'},proofs:{},reviewStatus:'proposed',notes:'Untouched operator note'}],evidence:[]});return root;}
const steps={collect:async(_r,stage)=>atomicJson(path.join(stage,'libraries.json'),{sourceId:'libraries',status:'unchanged',checkedAt:now.toISOString(),lastSuccessAt:now.toISOString(),candidates:[]}),details:async()=>({complete:true,pending:0,receipts:[]})};
const enabled={version:1,enabled:true,jobs:[{enabled:true,id:'libraries-pagination',kind:'library',url,cadenceHours:24}]};
test('Absent and disabled worker configuration preserve actual legacy cycle, notes and absence of queue',async t=>{const root=await fixture(t);const first=await runCycle(registry,root,{root,now,steps});assert.equal(first.state,'complete');const file=path.join(root,'worker-config.json');await atomicJson(file,{version:1,enabled:false});const second=await runCycle(registry,root,{root,now,steps,sourceWorkerConfigFile:file});assert.equal(second.state,'complete');assert.equal(second.counts.sources,first.counts.sources);assert.equal((await readJson(path.join(root,'review-packet.json'))).candidates[0].notes,'Untouched operator note');await assert.rejects(lstat(path.join(root,'source-workers')),/ENOENT/);});
test('Malformed optional configuration is delivered as private failure while healthy collection and human work continue',async t=>{const root=await fixture(t),file=path.join(root,'worker-config.json');await writeFile(file,'{');const receipt=await runCycle(registry,root,{root,now,clock:()=>now,steps,sourceWorkerConfigFile:file});assert.equal(receipt.state,'complete');assert.equal((await readJson(path.join(root,'source-worker-config.json'))).status,'failed');const outbox=await readJson(path.join(root,'alert-outbox.json'));assert.ok(outbox.items.some(row=>row.alert.sourceId==='source-worker-config'&&row.state==='delivered'));assert.equal((await readJson(path.join(root,'review-packet.json'))).candidates[0].notes,'Untouched operator note');assert.ok((await readJson(path.join(root,'review-packet.json'))).candidates.every(c=>!c.approval));});
test('File-configured workers require enabled bounded storage; otherwise legacy collection stays healthy',async t=>{const root=await fixture(t),file=path.join(root,'worker-config.json');await atomicJson(file,enabled);const receipt=await runCycle(registry,root,{root,now,clock:()=>now,steps,sourceWorkerConfigFile:file});assert.equal(receipt.state,'complete');assert.match((await readJson(path.join(root,'source-worker-config.json'))).error,/enabled bounded runtime storage/);await assert.rejects(lstat(path.join(root,'source-workers')),/ENOENT/);});
test('Config loader binds queue to runtime and rejects external paths, executables and oversized manifests',async t=>{const root=await fixture(t),file=path.join(root,'worker-config.json');await atomicJson(file,enabled);assert.equal((await loadSourceWorkerConfig(file,{root})).queueRoot,path.join(root,'source-workers'));const outside=path.join(path.dirname(root),'outside-'+path.basename(root)+'.json');await writeFile(outside,JSON.stringify(enabled));t.after(()=>rm(outside,{force:true}));await assert.rejects(loadSourceWorkerConfig(outside,{root}),/contained/);await atomicJson(file,{...enabled,command:'arbitrary-executable'});await assert.rejects(loadSourceWorkerConfig(file,{root}),/schema/);await writeFile(file,' '.repeat(4097));await assert.rejects(loadSourceWorkerConfig(file,{root}),/4096-byte/);});
test('Post-capture assessment is separate from start time and never backdates source timestamps',async t=>{const root=await fixture(t),captured=new Date(+now+60000),assessed=new Date(+now+120000);const clockSteps={...steps,collect:async(_r,stage)=>atomicJson(path.join(stage,'libraries.json'),{sourceId:'libraries',status:'unchanged',checkedAt:captured.toISOString(),lastSuccessAt:captured.toISOString(),candidates:[]})};const receipt=await runCycle(registry,root,{root,now,steps:clockSteps,assessmentClock:()=>assessed});assert.equal(receipt.startedAt,now.toISOString());assert.equal(receipt.assessmentAt,assessed.toISOString());assert.equal((await readJson(path.join(root,'libraries.json'))).checkedAt,captured.toISOString());const report=await readJson(path.join(root,'operational-report.json'));assert.equal(report.createdAt,assessed.toISOString());assert.equal(report.sourceHealth.find(source=>source.id==='libraries').state,'current');});

