import {admissionDirectory} from './runtime-json-admission.mjs';
import {actualAnchors} from './discovery.mjs';
import {queuedCapture,inspectWorkerHealth} from './worker-queue.mjs';
import {spawn} from 'node:child_process';import {randomUUID,createHash} from 'node:crypto';import {readFile,mkdir,readdir} from 'node:fs/promises';import path from 'node:path';
import {runCycleCore as runCycle} from './runner.mjs';import {collect,readJson,atomicJson} from './collect.mjs';import {fetchEvidence,safeUrl,hash} from './data.mjs';import {extractDetail} from './details.mjs';
const LIBRARY='https://library.mornpen.vic.gov.au/Whats-On/Events';
const PDFS=new Map([['westernport-writes-programme','https://westernportwrites.com.au/wp-content/uploads/2026/08/WPW2026-Festival-Program_-Final-1008-2.pdf'],['mount-martha-term-four','https://mountmarthahouse.com.au/wp-content/uploads/2026/09/Term-Four-2026-Digital-Program-1.pdf']]);
function libraryPageUrl(value){try{const u=safeUrl(value,['library.mornpen.vic.gov.au']);return u.pathname==='/Whats-On/Events'&&!u.hash;}catch{return false;}}
const readMaybe=async f=>{try{return await readJson(f);}catch(e){if(e.code==='ENOENT')return null;throw e;}};
function jobSource(job,registry){const url=job.kind==='library'?LIBRARY:PDFS.get(job.id);if(!/^[a-z][a-z0-9-]{0,63}$/.test(job.id)||!url||job.url!==url)throw new Error('Explicit worker source mismatch');const host=new URL(url).hostname;const parent=registry.sources.find(s=>s.authority==='official'&&(s.hosts??[new URL(s.url).hostname]).includes(host));if(!parent)throw new Error('Worker host lacks existing official source admission');if(job.kind==='library'&&parent.id!=='libraries')throw new Error('Library source identity mismatch');if(!Number.isFinite(job.cadenceHours)||job.cadenceHours<0.25||job.cadenceHours>168)throw new Error('Bounded source cadence required');return {...parent,id:job.id,url,hosts:[host],cadenceHours:job.cadenceHours,manualReview:true,retrievalMethods:[job.kind==='library'?'normal-public-form':'hash-bound-pdf-census'],allowPdf:job.kind==='pdf'};}
export async function supervisedProgram(program,args,{cwd,env={},timeoutMs=165000,signal}={}){
 if(timeoutMs<10||timeoutMs>180000)throw new Error('Worker watchdog budget');
 if(signal?.aborted)throw Error('Source worker cancelled before launch');
 const child=spawn(program,args,{cwd,env:{...process.env,...env},stdio:['ignore','ignore','pipe'],detached:process.platform!=='win32'});let stderr='',expired=false,interrupted=false;child.stderr.on('data',b=>{stderr=(stderr+b.toString()).slice(-2000);});
 const interrupt=()=>{interrupted=true;if(child.exitCode===null){if(process.platform==='win32')child.kill('SIGKILL');else process.kill(-child.pid,'SIGKILL');}};signal?.addEventListener('abort',interrupt,{once:true});
 const timer=setTimeout(()=>{expired=true;if(child.exitCode===null){if(process.platform==='win32')child.kill('SIGKILL');else process.kill(-child.pid,'SIGKILL');}},timeoutMs);
 const code=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('close',resolve);}).finally(()=>{clearTimeout(timer);signal?.removeEventListener('abort',interrupt);});if(interrupted)throw Error('Source worker cancelled; capture held');if(expired||code!==0)throw new Error(expired?'Source worker watchdog expired':'Source worker failed: '+stderr);return {code};
}
async function validateLibrary(output,now){const binding=await readMaybe(path.join(output,'capture-binding.json'));const lower=binding?new Date(binding.queuedAt):null;const upper=binding?new Date(binding.completedAt):now;const latest=await readJson(path.join(output,'live-library','latest.json'));if((binding&&binding.nonce!==latest.runId)||!/^[a-f0-9-]{36}$/.test(latest.runId)||latest.relativePath!=='runs/'+latest.runId)throw new Error('Worker run path mismatch');const run=path.join(output,'live-library','runs',latest.runId),receipt=await readJson(path.join(run,'receipt.json')),supervisor=await readJson(path.join(run,'supervisor.json'));const started=new Date(receipt.startedAt);if(!Number.isFinite(+now)||!Number.isFinite(+upper)||binding&&(!Number.isFinite(+lower)||lower>upper||upper>now)||!Number.isFinite(+started)||started>(binding?upper:now))throw new Error('Library capture time binding invalid');if(latest.status!=='complete'||!receipt.complete||receipt.runId!==latest.runId||supervisor.runId!==latest.runId||supervisor.status!=='complete'||receipt.pages.length<1||receipt.pages.length>20||!receipt.pages.at(-1).nextDisabled)throw new Error('Incomplete library capture held');const pages=[];
 for(const row of receipt.pages){const captured=await readJson(path.join(run,'page-'+row.page+'.json')),e=captured.evidence;const age=now-new Date(e.retrievedAt);if(row.runId!==receipt.runId||e.runId!==receipt.runId||e.sourceId!=='libraries'||!libraryPageUrl(e.url)||row.url!==e.url||row.page!==pages.length+1||e.id!==row.evidenceId||e.page!==row.page||(lower&&new Date(e.retrievedAt)<lower)||new Date(e.retrievedAt)>upper||new Date(receipt.startedAt)<(lower??new Date(0))||new Date(e.retrievedAt)<new Date(receipt.startedAt)||e.hash!==hash(e.body)||e.hash!==row.hash||!Number.isFinite(age)||age<0||age>24*3600000||Buffer.byteLength(e.body)>2000000)throw new Error('Library capture evidence mismatch/stale/future');pages.push(e);}
 return {receipt,pages,run};}
export async function validatePdf(evidence,source,output,now){const binding=await readMaybe(path.join(output,'capture-binding.json'));const time=new Date(evidence.retrievedAt),lower=binding?new Date(binding.queuedAt):null,upper=binding?new Date(binding.completedAt):null;if(!Number.isFinite(+now)||binding&&(!Number.isFinite(+lower)||!Number.isFinite(+upper)||lower>upper||upper>now)||evidence.sourceId!==source.id||evidence.url!==source.url||!/^application\/pdf(?:;|$)/i.test(evidence.contentType??'')||evidence.authority!=='official'||typeof evidence.base64!=='string'||evidence.base64.length>27000000||!Number.isFinite(+time)||time>now||now-time>24*3600000||(binding&&(time<lower||time>upper)))throw Error('PDF source/time/content binding mismatch');const bytes=Buffer.from(evidence.base64,'base64');if(bytes.length>20000000||bytes.subarray(0,5).toString()!=='%PDF-'||bytes.toString('base64')!==evidence.base64||createHash('sha256').update(bytes).digest('hex')!==evidence.hash||evidence.id!==hash(source.id+evidence.hash))throw Error('PDF raw signature/hash/identity binding mismatch');return evidence;}
function pdfCandidates(result,derived){return result.drafts.filter(d=>d.proposedDates?.length&&['dated-session','dated-session-multisegment','dated-session-historical','explicit-date-no-time','explicit-dated-session'].includes(d.classification)).flatMap(d=>{const dates=d.proposedDates;return dates.map(date=>{const fields={title:d.proposedTitle,officialEventUrl:derived.url,status:'unknown',...(date?{startDate:date}:{})};return {id:hash('pdf:'+derived.sourceId+':'+d.id+':'+(date??'undated')).slice(0,24),kind:'event',fields,proofs:Object.fromEntries(Object.entries(fields).map(([key,value])=>[key,{value,evidenceId:derived.id,quote:d.quote,verified:false,location:{physicalPage:d.physicalPage,region:d.region},method:'captured-pdf-region-census'}])),reviewStatus:'proposed',classification:d.classification,uncertainties:d.uncertainties,sourceReview:{required:true,reason:'PDF visual/factual/date/geography verification required'},publicationChanges:[]};});});}
export async function runCycleWithSourceWorkers(registry,directory,{config,execute=supervisedProgram,pdfFetcher=fetchEvidence,clock=()=>new Date(),allowExternalQueue=false,...options}={}){
 if(!config?.enabled)return runCycle(registry,directory,options);
 let jobs=[],sources=[],configError=null;
 try{if(config.configurationError)throw Error(config.configurationError);if(config.queueRoot&&!allowExternalQueue){const normalize=p=>process.platform==='win32'?path.resolve(p).toLowerCase():path.resolve(p);if(normalize(config.queueRoot)!==normalize(path.join(directory,'source-workers')))throw new Error('Source worker queue must be the runtime source-workers directory');}if(!Array.isArray(config.jobs)||config.jobs.length>3)throw new Error('Explicit bounded worker jobs required');jobs=config.jobs.filter(j=>j.enabled===true);if(jobs.length&&!config.queueRoot&&execute===supervisedProgram)throw new Error('Isolated source worker queue is required; in-process browser execution is disabled');sources=jobs.map(j=>jobSource(j,registry));if(new Set(sources.map(s=>s.id)).size!==sources.length||sources.some(s=>registry.sources.some(r=>r.id===s.id)))throw new Error('Worker source identity collision');if(!config.queueRoot&&jobs.some(j=>j.kind==='library')&&typeof config.libraryProgram!=='string')throw new Error('Library executable not configured');if(!config.queueRoot&&jobs.some(j=>j.kind==='pdf')&&[config.pythonExecutable,config.pdfProgram,config.censusFile].some(v=>typeof v!=='string'||!v))throw new Error('PDF executable/census not configured');}
 catch(error){jobs=[];sources=[];configError=error.message;}
 if(!configError&&!jobs.length)return runCycle(registry,directory,options);
 const configSource={id:'source-worker-config',url:registry.sources[0]?.url??LIBRARY,cadenceHours:24,manualReview:true,monitorOnly:true};if(registry.sources.some(s=>s.id===configSource.id))throw new Error('Reserved worker config identity');
 const serviceSource=config.queueRoot&&!configError&&jobs.length?{...configSource,id:'source-worker-service'}:null;const augmented={...registry,sources:[...registry.sources,...sources,configSource,...(serviceSource?[serviceSource]:[])]};const now=options.now??clock();
 const collectStep=async(_all,stage,collectOptions)=>{
  await (options.steps?.collect??collect)(registry,stage,collectOptions);
  await atomicJson(path.join(stage,'source-worker-config.json'),{sourceId:'source-worker-config',status:configError?'failed':'unchanged',checkedAt:now.toISOString(),lastSuccessAt:configError?null:now.toISOString(),error:configError?'Optional source worker configuration failed: '+configError:null,reviewRequired:true});
  if(serviceSource){let health,error;try{health=await inspectWorkerHealth(config.queueRoot,{now:clock()});}catch(e){error=e.message;}await atomicJson(path.join(stage,'source-worker-service.json'),{sourceId:serviceSource.id,status:error?'failed':'unchanged',checkedAt:clock().toISOString(),lastSuccessAt:error?null:clock().toISOString(),error:error??null,workerHeartbeat:health??null,monitorOnly:true});}
  for(let i=0;i<jobs.length;i++){const job=jobs[i],source=sources[i],file=path.join(stage,source.id+'.json');const previous=await readMaybe(file);if(job.kind==='library')for(const evidence of previous?.pageEvidence??[]){await atomicJson(path.join(stage,'worker-library-page-'+evidence.page+'.json'),{evidence,candidates:extractDetail(evidence).candidates,reviewRequired:true});}const age=previous?.status!=='failed'&&previous?.lastSuccessAt?now-new Date(previous.lastSuccessAt):Infinity;const failedAge=previous?.status==='failed'?now-new Date(previous.checkedAt):Infinity;if(!options.force&&((age>=0&&age<source.cadenceHours*3600000)||(failedAge>=0&&failedAge<3600000)))continue;
   const output=path.join(stage,'source-workers',source.id,randomUUID());await admissionDirectory(output);let capture;
   try{
    if(job.kind==='library'){
     if(config.queueRoot)await queuedCapture(config.queueRoot,{kind:'library',sourceId:'libraries',url:source.url},{output,now:clock()});else await execute(config.nodeExecutable??process.execPath,[config.libraryProgram],{cwd:output,env:{PI_ADAPTER_OUTPUT_DIRECTORY:output,XDG_CONFIG_HOME:'/tmp/pi-worker-config',XDG_CACHE_HOME:'/tmp/pi-worker-cache'},timeoutMs:165000});
     const validated=await validateLibrary(output,clock()),leads=new Map();for(const e of validated.pages){const extracted=extractDetail(e);await atomicJson(path.join(stage,'worker-library-page-'+e.page+'.json'),{evidence:e,candidates:extracted.candidates,reviewRequired:true});for(const lead of extracted.leads??[])leads.set(lead.url,{...lead,sourceId:'libraries',format:'html',retrievalAllowed:true});}
     // Parse explicit event detail links from all captured pages through admitted URL guards.
     for(const e of validated.pages)for(const href of actualAnchors(e.body)){let u;try{u=safeUrl(new URL(href,e.url).href,['library.mornpen.vic.gov.au']);}catch{continue;}if(u.pathname.startsWith('/Whats-On/Events/'))leads.set(u.href,{id:hash(u.href).slice(0,24),url:u.href,originalUrl:href,sourceId:'libraries',format:'html',retrievalAllowed:true,requiresReview:true});}
     const rootFile=path.join(stage,'libraries.json'),rootCapture=await readJson(rootFile);rootCapture.leads=[...(rootCapture.leads??[]),...leads.values()];await atomicJson(rootFile,rootCapture);capture={sourceId:source.id,status:'changed',checkedAt:clock().toISOString(),lastSuccessAt:clock().toISOString(),pagination:validated.receipt,pageEvidence:validated.pages,leadsAdded:leads.size,workerOutput:output,reviewRequired:true};
    }else{
     if(config.queueRoot)await queuedCapture(config.queueRoot,{kind:'pdf',sourceId:source.id,url:source.url},{output,now:clock()});
     const evidence=config.queueRoot?await readJson(path.join(output,'snapshot.json')):await pdfFetcher(source,{now:clock(),maxBytes:20000000});await validatePdf(evidence,source,output,clock());await atomicJson(path.join(output,'snapshot.json'),evidence);await atomicJson(path.join(stage,source.id+'-raw.json'),{evidence,candidates:[],reviewRequired:true});
     if(!config.queueRoot)await execute(config.pythonExecutable,[config.pdfProgram,path.join(output,'snapshot.json'),job.censusKey,config.censusFile,path.join(output,'drafts.json')],{cwd:output,timeoutMs:60000});const result=await readJson(path.join(output,'drafts.json'));if(result.state==='source-changed')throw new Error('PDF bytes changed; previous manual census invalidated');if(result.state!=='complete'||result.parentHash!==evidence.hash)throw new Error('PDF census incomplete or unbound');
     const body=result.drafts.map(d=>'PAGE '+d.physicalPage+' '+d.quote).join('\n');const derived={id:hash(evidence.id+body),sourceId:source.id,url:evidence.url,retrievedAt:evidence.retrievedAt,hash:hash(body),body,contentType:'application/pdf-derived-text',authority:'official',parentEvidenceId:evidence.id,parentHash:evidence.hash};capture={sourceId:source.id,status:'changed',checkedAt:clock().toISOString(),lastSuccessAt:clock().toISOString(),evidence:derived,candidates:pdfCandidates(result,derived),programmeReviewRows:result.drafts,programmeRowDenominator:result.drafts.length,programmeReviewNote:'Programme claim rows include unresolved timetable, FULL, conflicts, services and directory leads; not an event count or factual verification.',workerOutput:output,reviewRequired:true};
    }
   }catch(error){capture={...previous,sourceId:source.id,status:'failed',error:error.message,checkedAt:clock().toISOString(),lastSuccessAt:previous?.lastSuccessAt??null,workerOutput:output,reviewRequired:true};if(/PDF bytes changed/.test(error.message)){delete capture.evidence;capture.candidates=[];capture.programmeReviewRows=[];capture.censusInvalidated=true;}}
   await atomicJson(file,capture);
  }
 };
 return runCycle(augmented,directory,{...options,now,assessmentClock:clock,steps:{...options.steps,collect:collectStep}});
}


