import test from 'node:test';import assert from 'node:assert/strict';import {verifyCandidate} from './verify.mjs';import {candidateRevision} from './data.mjs';
const now=new Date('2026-10-04T04:00:00Z');
function fixture(){const fields={title:'Art day',venueName:'Gallery',officialEventUrl:'https://example.com/art',status:'scheduled',startDate:'2026-10-10'};const body=Object.values(fields).join(' ');const evidence={id:'e',body,authority:'official',retrievedAt:now.toISOString(),lineage:'organiser'};const candidate={id:'art-day-2026',kind:'event',fields,geography:{shireConfirmed:true,evidenceId:'e',quote:'Gallery',verified:true,verifiedBy:'James'},proofs:Object.fromEntries(Object.entries(fields).map(([key,value])=>[key,{value,quote:value,evidenceId:'e',verified:true,verifiedBy:'James'}]))};return {candidate,evidence};}
test('current explicit human-verified fields pass; extraction alone cannot',()=>{const {candidate,evidence}=fixture();assert.equal(verifyCandidate(candidate,[evidence],{now}).ready,true);candidate.proofs.startDate.verified=false;assert.equal(verifyCandidate(candidate,[evidence],{now}).ready,false);});
test('stale year, conflicts, copied-source lineage and unsafe bookings remain visible',()=>{const {candidate,evidence}=fixture();candidate.fields.startDate='2025-10-10';candidate.conflicts=[{resolved:false}];candidate.fields.bookingUrl='http://localhost';const result=verifyCandidate(candidate,[evidence,{...evidence,id:'copy'}],{now});assert.equal(result.ready,false);assert.equal(result.independentSources,1);assert.ok(result.errors.includes('past-event'));assert.ok(result.errors.includes('unresolved-conflict'));assert.ok(result.errors.includes('unsafe-booking-url'));});
test('sold out and cancellation are distinct; cancelled candidate cannot publish',()=>{const {candidate,evidence}=fixture();candidate.fields.status='cancelled';assert.equal(verifyCandidate(candidate,[evidence],{now}).ready,false);});
test('changing content invalidates its approval digest',()=>{const {candidate}=fixture();const revision=candidateRevision(candidate);candidate.summary='Changed';assert.notEqual(candidateRevision(candidate),revision);});
test('future evidence and unlocated quotations fail closed',()=>{const {candidate,evidence}=fixture();evidence.retrievedAt='2027-01-01T00:00:00Z';candidate.proofs.title.quote='invented';assert.equal(verifyCandidate(candidate,[evidence],{now}).ready,false);});

test('geography and booking require fresh located human confirmation',()=>{const {candidate,evidence}=fixture();candidate.geography.verified=false;assert.ok(verifyCandidate(candidate,[evidence],{now}).errors.includes('scope-not-verified'));candidate.geography.verified=true;candidate.fields.bookingUrl='https://example.com/book';candidate.proofs.bookingUrl={verified:true};assert.ok(verifyCandidate(candidate,[evidence],{now}).errors.includes('booking-unverified'));});

test('impossible dates and ambiguous timestamps are rejected rather than normalised',()=>{for(const date of ['2027-02-30','2026-10-10T10:00:00']){const {candidate,evidence}=fixture();candidate.fields.startDate=date;candidate.proofs.startDate.value=date;candidate.proofs.startDate.quote=date;evidence.body+=' '+date;assert.ok(verifyCandidate(candidate,[evidence],{now}).errors.includes('invalid-date'));}});

test('offers cannot use past or impossible validity dates',()=>{for(const end of ['2026-10-01','2027-02-30']){const {candidate,evidence}=fixture();candidate.kind='offer';candidate.fields.endDate=end;candidate.fields.terms='Entry conditions apply';candidate.proofs.endDate={value:end,quote:end,evidenceId:'e',verified:true,verifiedBy:'James'};candidate.proofs.terms={value:candidate.fields.terms,quote:candidate.fields.terms,evidenceId:'e',verified:true,verifiedBy:'James'};evidence.body+=' '+end+' '+candidate.fields.terms;assert.equal(verifyCandidate(candidate,[evidence],{now}).ready,false);}});

test('closing dates and bounded recurrence need their own located official proofs',()=>{const {candidate,evidence}=fixture();candidate.fields.endDate='2026-10-11';assert.equal(verifyCandidate(candidate,[evidence],{now}).fields.endDate.score,0);delete candidate.fields.endDate;candidate.series={id:'art-weekly',frequency:'weekly',validFrom:'2026-10-10',validUntil:'2026-10-31',daysOfWeek:[6],exceptions:[]};assert.equal(verifyCandidate(candidate,[evidence],{now}).fields.series.score,0);});

test('supplied coordinates need their own official located proof and boundary evidence cannot be omitted when requested',()=>{const {candidate,evidence}=fixture();candidate.fields.coordinates={lat:-38,lng:145};assert.equal(verifyCandidate(candidate,[evidence],{now}).fields.coordinates.score,0);candidate.geography.boundaryEvidenceId='missing-boundary';assert.ok(verifyCandidate(candidate,[evidence],{now}).errors.some(e=>e.startsWith('scope-boundary-invalid')));});
test('a bounded ongoing series is assessed through its confirmed final local day',()=>{const {candidate,evidence}=fixture();candidate.fields.startDate='2026-09-01';candidate.proofs.startDate={value:'2026-09-01',quote:'2026-09-01',evidenceId:'e',verified:true,verifiedBy:'James'};evidence.body+=' 2026-09-01';candidate.series={id:'weekly',frequency:'weekly',validFrom:'2026-09-01',validUntil:'2026-10-31',daysOfWeek:[2],exceptions:[]};const result=verifyCandidate(candidate,[evidence],{now});assert.ok(!result.errors.includes('past-event'));assert.equal(result.fields.series.score,0);candidate.series.validUntil='2026-09-30';assert.ok(verifyCandidate(candidate,[evidence],{now}).errors.includes('past-event'));});

test('moved series sessions require their own Shire proof rather than inheriting the original venue geography',()=>{const {candidate,evidence}=fixture();candidate.series={id:'weekly',frequency:'weekly',validFrom:'2026-10-10',validUntil:'2026-10-31',daysOfWeek:[6],exceptions:[{date:'2026-10-17',status:'moved',venueName:'Different venue'}]};assert.ok(verifyCandidate(candidate,[evidence],{now}).errors.includes('scope-moved-occurrence-unverified: 2026-10-17'));evidence.body+=' Different venue, Mornington';candidate.geography.occurrences={'2026-10-17':{shireConfirmed:true,evidenceId:'e',quote:'Different venue, Mornington',verifiedBy:'James',verified:true}};assert.ok(!verifyCandidate(candidate,[evidence],{now}).errors.some(e=>e.startsWith('scope-moved')));candidate.geography.occurrences['2026-10-17'].verified=false;assert.ok(verifyCandidate(candidate,[evidence],{now}).errors.some(e=>e.startsWith('scope-moved')));});
