import {acquireRunLock} from './runner.mjs';
import {randomUUID} from 'node:crypto';import {mkdir,open,rename,statfs} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {queueRoot,processQueuedJob,recoverInterrupted,workerSources,boundedJson} from './worker-queue.mjs';import {supervisedProgram} from './source-workers.mjs';import {boundedWorkerPerform,assertWorkerScratch} from './worker-scratch.mjs';import {fetchEvidence} from './data.mjs';import {atomicJson,readJson} from './collect.mjs';
const app=path.dirname(fileURLToPath(import.meta.url));
export async function performSourceJob(job,output,{execute=supervisedProgram,fetcher=fetchEvidence,signal}={}){if(job.kind==='library'){await execute(process.execPath,[process.env.PI_LIBRARY_PROGRAM??'/app/adapter-staging/live-library.mjs','--run='+job.nonce],{cwd:output,env:{PI_ADAPTER_OUTPUT_DIRECTORY:output,XDG_CONFIG_HOME:'/tmp/pi-source-config',XDG_CACHE_HOME:'/tmp/pi-source-cache'},timeoutMs:165000,signal});}else{const source={id:job.sourceId,url:job.url,hosts:[new URL(job.url).hostname],authority:'official',allowPdf:true};const evidence=await fetcher(source,{now:new Date(),maxBytes:20000000,signal});await atomicJson(path.join(output,'snapshot.json'),evidence);await execute(process.env.PI_PYTHON_EXECUTABLE??'/opt/worker-python/bin/python',[process.env.PI_PDF_PROGRAM??'/app/adapter-staging/runner-integration/pdf-child.py',path.join(output,'snapshot.json'),job.sourceId==='westernport-writes-programme'?'westernport':'mountMartha',process.env.PI_PDF_CENSUS??'/app/adapter-staging/pdf-census/programme-row-census.json',path.join(output,'drafts.json')],{cwd:output,timeoutMs:60000,signal});}}
export async function writeWorkerHeartbeat(root,receipt,{renameFile=rename}={}){if(receipt.version!==1||!/^[a-f0-9-]{36}$/.test(receipt.serviceId)||!['idle','running','stopped'].includes(receipt.status)||!Number.isFinite(+new Date(receipt.checkedAt))||Object.keys(receipt).some(key=>!['version','serviceId','status','checkedAt'].includes(key)))throw Error('Worker heartbeat schema');const text=JSON.stringify(receipt)+'\n';if(Buffer.byteLength(text)>4096)throw Error('Worker heartbeat byte budget');const disk=await statfs(root);if(Number(disk.bavail)*Number(disk.bsize)<536870912+4096)throw Error('Worker heartbeat cannot retain free reserve');const file=path.join(root,'worker-health.json'),temp=file+'.owned-'+randomUUID()+'.tmp',handle=await open(temp,'wx');try{await handle.writeFile(text);await handle.sync();}finally{await handle.close();}for(let attempt=0;;attempt++)try{await renameFile(temp,file);return;}catch(error){if(!['EPERM','EACCES','EBUSY'].includes(error.code)||attempt>=7)throw error;await new Promise(resolve=>setTimeout(resolve,Math.min(10*2**attempt,80)));}}
async function runWorkerServiceInternal(root,{signal,perform=performSourceJob,pollMs=1000,healthWriter=writeWorkerHeartbeat,scratchRoot}={}){root=await queueRoot(root);if(scratchRoot)await assertWorkerScratch(scratchRoot);const serviceId=randomUUID();try{const h=await boundedJson(path.join(root,'worker-health.json'));if(['idle','running'].includes(h.status)&&Date.now()-new Date(h.checkedAt)<30000)throw Error('Recent active worker identity exists; wait for heartbeat expiry');}catch(e){if(e.code!=='ENOENT')throw e;}await recoverInterrupted(root,serviceId);let status='idle';let heartbeatChain=Promise.resolve();const heartbeat=()=>{const receipt={version:1,serviceId,status,checkedAt:new Date().toISOString()};heartbeatChain=heartbeatChain.catch(()=>{}).then(()=>healthWriter(root,receipt));return heartbeatChain;};await heartbeat();const timer=setInterval(()=>heartbeat().catch(()=>{}),5000);try{while(!signal?.aborted){status='running';const result=await processQueuedJob(root,{serviceId,perform:(job,output)=>scratchRoot?boundedWorkerPerform(job,output,{scratchRoot,perform:(ownedJob,scratch)=>perform(ownedJob,scratch,{signal})}):perform(job,output,{signal})});status='idle';await heartbeat();if(!result)await new Promise(r=>setTimeout(r,pollMs));}}finally{clearInterval(timer);status='stopped';await heartbeat();}}
export async function runWorkerService(root,options={}){if(!options.scratchRoot&&!(options.fixtureOnly===true&&typeof options.perform==='function'))throw Error('Bounded worker scratch required for real service');root=await queueRoot(root);const control=path.join(root,'.service-control');await mkdir(control,{recursive:true});const lock=await acquireRunLock(control);try{return await runWorkerServiceInternal(root,options);}finally{await lock.release();}}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const controller=new AbortController();process.once('SIGTERM',()=>controller.abort());process.once('SIGINT',()=>controller.abort());await runWorkerService(process.env.PI_SOURCE_QUEUE_ROOT??'/data/source-workers',{signal:controller.signal,scratchRoot:'/worker-scratch'});}


