import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,rm,mkdir,readFile,symlink} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {atomicJson,readJson} from './collect.mjs';import {queueRoot,validateJob,queuedCapture,processQueuedJob,recoverInterrupted,workerSources} from './worker-queue.mjs';import {runCycleWithSourceWorkers} from './source-workers.mjs';
const now=new Date(),source={kind:'library',sourceId:'libraries',url:workerSources.libraries};
async function setup(t){const d=await mkdtemp(path.join(os.tmpdir(),'pi-worker-queue-'));t.after(()=>rm(d,{recursive:true,force:true}));const root=path.join(d,'queue');await queueRoot(root);const serviceId=randomUUID();await atomicJson(path.join(root,'worker-health.json'),{serviceId,status:'idle',checkedAt:now.toISOString()});return {d,root,serviceId};}
const job=()=>({version:1,nonce:randomUUID(),...source,queuedAt:now.toISOString(),expiresAt:new Date(+now+20000).toISOString()});
test('File queue returns only completed exact nonce/source capture and concurrent workers claim once',async t=>{const {d,root,serviceId}=await setup(t),output=path.join(d,'output');let calls=0;const pending=queuedCapture(root,source,{output,now,timeoutMs:2000,pollMs:10});await new Promise(r=>setTimeout(r,40));const perform=async(j,out)=>{calls++;await new Promise(r=>setTimeout(r,50));await atomicJson(path.join(out,'fixture.json'),{nonce:j.nonce});};const results=await Promise.all([processQueuedJob(root,{serviceId,perform,now}),processQueuedJob(root,{serviceId,perform,now})]);const receipt=await pending;assert.equal(calls,1);assert.equal(results.filter(Boolean).length,1);assert.equal(receipt.status,'complete');assert.equal((await readJson(path.join(output,'fixture.json'))).nonce,receipt.nonce);});
test('Stopped/absent worker and malformed source commands fail before source capture',async t=>{const {root}=await setup(t);assert.throws(()=>validateJob({...job(),url:'https://127.0.0.1/contact'}),/mismatch/);assert.throws(()=>validateJob({...job(),command:'curl evil'}),/Unexpected/);assert.throws(()=>validateJob({...job(),expiresAt:'2999-01-01'}),/unbounded/);await atomicJson(path.join(root,'worker-health.json'),{serviceId:randomUUID(),status:'stopped',checkedAt:now.toISOString()});await assert.rejects(queuedCapture(root,source,{now}),/unavailable/);});
test('Worker cannot mark an over-budget capture complete',{timeout:10000},async t=>{const {root,serviceId}=await setup(t),j=job();await atomicJson(path.join(root,'pending',j.nonce+'.json'),j);const {truncate}=await import('node:fs/promises');const receipt=await processQueuedJob(root,{serviceId,now,perform:async(_j,out)=>{const file=path.join(out,'oversized.bin');await writeFile(file,'');await truncate(file,45000001);}});assert.equal(receipt.status,'failed');assert.match(receipt.error,/capture budget exceeded/);assert.equal((await readJson(path.join(root,'results',j.nonce+'.json'))).status,'failed');});
test('failed durable capture sync retains scratch evidence and refuses a complete receipt',async t=>{const {root,serviceId}=await setup(t),j=job();await atomicJson(path.join(root,'pending',j.nonce+'.json'),j);let released=false;const receipt=await processQueuedJob(root,{serviceId,now,syncCapture:async()=>{throw Error('synthetic directory sync failure');},perform:async(_j,out)=>{await writeFile(path.join(out,'capture.txt'),'evidence');return {releaseScratch:async()=>{released=true;}};}});assert.equal(receipt.status,'failed');assert.match(receipt.error,/sync failure/);assert.equal(released,false);assert.equal(await readFile(path.join(root,'captures',j.nonce,'capture.txt'),'utf8'),'evidence');assert.equal((await readJson(path.join(root,'results',j.nonce+'.json'))).status,'failed');});
test('Worker failure is durable and collector timeout is bounded, no incomplete output copied',async t=>{const {d,root,serviceId}=await setup(t);const pending=assert.rejects(queuedCapture(root,source,{output:path.join(d,'no-output'),now,timeoutMs:2000,pollMs:10}),/worker failed: fixture failed/);await new Promise(r=>setTimeout(r,30));const receipt=await processQueuedJob(root,{serviceId,now,perform:async()=>{throw Error('fixture failed');}});await pending;assert.equal(receipt.status,'failed');await assert.rejects(readFile(path.join(d,'no-output','fixture.json')),/ENOENT/);const start=Date.now();await assert.rejects(queuedCapture(root,source,{output:path.join(d,'timeout'),now,timeoutMs:50,pollMs:10}),/timeout/);assert.ok(Date.now()-start<1000);});
test('Restart never reuses old complete receipt as interrupted job success',async t=>{const {root,serviceId}=await setup(t),j=job();await atomicJson(path.join(root,'processing',j.nonce+'.json'),j);await atomicJson(path.join(root,'results',j.nonce+'.json'),{version:1,nonce:j.nonce,serviceId,status:'running',sourceId:j.sourceId,url:j.url});const completed=job();await atomicJson(path.join(root,'processing',completed.nonce+'.json'),completed);await atomicJson(path.join(root,'results',completed.nonce+'.json'),{nonce:completed.nonce,status:'complete',serviceId});await recoverInterrupted(root,randomUUID());assert.equal((await readJson(path.join(root,'results',j.nonce+'.json'))).status,'failed');assert.equal((await readJson(path.join(root,'results',completed.nonce+'.json'))).status,'complete');});
test('Unavailable optional worker preserves healthy actual legacy cycle with source failure alert',async t=>{const {d,root}=await setup(t);await atomicJson(path.join(root,'worker-health.json'),{serviceId:randomUUID(),status:'stopped',checkedAt:now.toISOString()});const directory=path.join(d,'runtime'),registry={sources:[{id:'libraries',url:source.url,authority:'official',hosts:['library.mornpen.vic.gov.au']}]};const result=await runCycleWithSourceWorkers(registry,directory,{root:directory,allowExternalQueue:true,now,clock:()=>now,config:{enabled:true,queueRoot:root,jobs:[{enabled:true,id:'libraries-pagination',kind:'library',url:source.url,cadenceHours:24}]},steps:{collect:async(r,s)=>atomicJson(path.join(s,'libraries.json'),{sourceId:'libraries',status:'unchanged',lastSuccessAt:now.toISOString(),candidates:[]}),details:async()=>({complete:true,receipts:[]})}});assert.equal(result.state,'complete');assert.equal((await readJson(path.join(directory,'libraries-pagination.json'))).status,'failed');assert.ok((await readJson(path.join(directory,'alert-outbox.json'))).items.some(i=>i.alert.sourceId==='libraries-pagination'&&i.state==='delivered'));});
import {runWorkerService} from './worker-service.mjs';
test('real worker-service API refuses to start without bounded scratch',async t=>{const {root}=await setup(t);await assert.rejects(runWorkerService(root),/Bounded worker scratch required/);});
test('Worker heartbeat writes serialize during active task and graceful stop, preserving terminal stopped receipt',async t=>{const {root}=await setup(t);await atomicJson(path.join(root,'worker-health.json'),{status:'stopped'});const controller=new AbortController();const j=job();await atomicJson(path.join(root,'pending',j.nonce+'.json'),j);const service=runWorkerService(root,{fixtureOnly:true,signal:controller.signal,pollMs:5,perform:async()=>{await new Promise(r=>setTimeout(r,5100));controller.abort();}});await service;assert.equal((await readJson(path.join(root,'worker-health.json'))).status,'stopped');assert.equal((await readJson(path.join(root,'results',j.nonce+'.json'))).status,'complete');});
import {queueCapacity} from './worker-queue.mjs';
test('Retained private capture capacity holds further work without deleting any prior evidence',async t=>{const {root}=await setup(t),capture=path.join(root,'captures',randomUUID());await mkdir(capture);await atomicJson(path.join(capture,'proof.json'),{evidence:'retained'});await assert.rejects(queueCapacity(root,{maxCaptures:1}),/capacity reached/);assert.deepEqual(await readJson(path.join(capture,'proof.json')),{evidence:'retained'});});
test('Stopped service remains visible when library capture is cached and not due',async t=>{const {d,root}=await setup(t);await atomicJson(path.join(root,'worker-health.json'),{serviceId:randomUUID(),status:'stopped',checkedAt:now.toISOString()});const directory=path.join(d,'cached-runtime');await mkdir(directory);await atomicJson(path.join(directory,'libraries-pagination.json'),{sourceId:'libraries-pagination',status:'changed',lastSuccessAt:now.toISOString(),checkedAt:now.toISOString(),leadsAdded:68});const registry={sources:[{id:'libraries',url:source.url,authority:'official',hosts:['library.mornpen.vic.gov.au']}]};await runCycleWithSourceWorkers(registry,directory,{root:directory,allowExternalQueue:true,now,clock:()=>now,config:{enabled:true,queueRoot:root,jobs:[{enabled:true,id:'libraries-pagination',kind:'library',url:source.url,cadenceHours:24}]},steps:{collect:async(r,s)=>atomicJson(path.join(s,'libraries.json'),{sourceId:'libraries',status:'unchanged',lastSuccessAt:now.toISOString(),candidates:[]}),details:async()=>({complete:true,receipts:[]})}});assert.equal((await readJson(path.join(directory,'libraries-pagination.json'))).leadsAdded,68);assert.ok((await readJson(path.join(directory,'alert-outbox.json'))).items.some(i=>i.alert.sourceId==='source-worker-service'&&i.state==='delivered'));});
test('Low physical storage reserve refuses jobs and retains prior captures',async t=>{const {root}=await setup(t);await assert.rejects(queueCapacity(root,{reserveBytes:Number.MAX_SAFE_INTEGER}),/reserve exhausted/);assert.equal((await queueCapacity(root)).captures,0);});

import {writeFile,readdir} from 'node:fs/promises';import {supervisedProgram} from './source-workers.mjs';
test('Physical queue accounting holds many small retained files and reserves a whole next capture',async t=>{const {root}=await setup(t),capture=path.join(root,'captures',randomUUID());await mkdir(capture);for(let i=0;i<20;i++)await writeFile(path.join(capture,String(i)),'.');await assert.rejects(queueCapacity(root,{maxBytes:50000,newJob:false}),/capacity reached/);assert.equal((await readdir(capture)).length,20);await assert.rejects(queueCapacity(root,{maxBytes:30000000}),/reservation unavailable/);});
test('Concurrent next-job reservation counts pending work rather than only existing capture bytes',async t=>{const {root}=await setup(t),pending=job();await atomicJson(path.join(root,'pending',pending.nonce+'.json'),pending);await assert.rejects(queueCapacity(root,{maxBytes:70000000}),/reservation unavailable/);assert.equal((await readJson(path.join(root,'pending',pending.nonce+'.json'))).nonce,pending.nonce);});
test('Linux rejects differently cased intermediate symlink path instead of comparing paths case-insensitively',{skip:process.platform!=='linux'},async t=>{const {d}=await setup(t),actual=path.join(d,'parent'),alias=path.join(d,'PARENT');await mkdir(actual);await symlink(actual,alias);await assert.rejects(queueRoot(path.join(alias,'new-queue')),/symlink/);});
test('Owned child cancellation terminates promptly and reports held capture',async()=>{const controller=new AbortController(),start=Date.now();const promise=supervisedProgram(process.execPath,['-e','setInterval(()=>{},1000)'],{timeoutMs:2000,signal:controller.signal});setTimeout(()=>controller.abort(),50);await assert.rejects(promise,/cancelled/);assert.ok(Date.now()-start<1500);});
test('A second service cannot race an active service identity',async t=>{const {root}=await setup(t);await atomicJson(path.join(root,'worker-health.json'),{status:'stopped'});const controller=new AbortController(),first=runWorkerService(root,{fixtureOnly:true,perform:async()=>{},signal:controller.signal,pollMs:10});for(let i=0;i<30;i++){if((await readJson(path.join(root,'worker-health.json'))).status==='idle')break;await new Promise(r=>setTimeout(r,10));}try{await assert.rejects(runWorkerService(root,{fixtureOnly:true,perform:async()=>{},pollMs:10}),/already active/);}finally{controller.abort();await first;}assert.equal((await readJson(path.join(root,'worker-health.json'))).status,'stopped');});

import {writeWorkerHeartbeat} from './worker-service.mjs';import {rename} from 'node:fs/promises';
test('Heartbeat retries only owned finalization on transient sharing denial and keeps exact final receipt',async t=>{const {root,serviceId}=await setup(t),receipt={version:1,serviceId,status:'idle',checkedAt:new Date().toISOString()};let attempts=0;await writeWorkerHeartbeat(root,receipt,{renameFile:async(source,destination)=>{if(++attempts<3)throw Object.assign(Error('synthetic Windows sharing denial'),{code:'EPERM'});return rename(source,destination);}});assert.equal(attempts,3);assert.deepEqual(await readJson(path.join(root,'worker-health.json')),receipt);});
