import test from 'node:test';
import assert from 'node:assert/strict';
import {Site,DIST,routesContaining} from './harness.mjs';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
const site=await Site.open();test.after(()=>site.close());
const ok=[{match:'/rest/v1/',status:201,body:{}},{match:'/storage/v1/',status:200,body:{Key:'submissions/test-photo.png'}}];
async function fill(page,selector,values){for(const [key,value]of Object.entries(values))await page.type(`${selector} [name="${key}"]`,value);}
test('retired pages reach their intended destination without breaking old links',async()=>{
 const r=await site.reader();try{for(const [from,to,type]of [['/pass/','/dispatch/'],['/editorial-approach/','/about/'],['/how-we-check/','/about/'],['/accessibility/','/contact/','accessibility'],['/corrections/','/contact/','correction'],['/partners/claim/','/partners/update/']]){await r.load(from);await r.waitFor(()=>!document.querySelector('meta[http-equiv="refresh"]'),'redirect pending');assert.equal(new URL(r.page.url()).pathname,to);if(type)assert.equal(await r.page.$eval('details[open]',e=>e.dataset.contactReason),type);}}finally{await r.close();}
});
test('Contact accords one enquiry type per form and saves a note once',async()=>{
 const r=await site.reader({supabase:ok});try{await r.load('/contact/?type=general');const s='[data-public-intake="general"]';await fill(r.page,s,{name:'Test reader',email:'test@example.invalid',message:'A local story suggestion for testing.'});await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-public-intake="general"] [data-intake-status]').textContent.includes('received'),'contact not received');const calls=r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('/rest/v1/submissions'));assert.equal(calls.length,1);assert.match(JSON.parse(calls[0].body).title,/CONTACT \(general\)/);await r.page.click('#accessibility summary');await r.waitFor(()=>document.querySelector('#accessibility').open,'accessibility closed');assert.equal(await r.page.$$eval('details[open]',els=>els.length),1);assert.equal(await r.page.$eval('#accessibility [name=enquiry_type]',e=>e.value),'accessibility');}finally{await r.close();}
});
test('failed listing submission retains input and permits a successful retry',async()=>{
 const r=await site.reader({supabase:[{match:'/rest/v1/',method:'POST',status:500,body:{message:'test failure'}}]});try{await r.load('/partners/update/');const s='[data-public-intake="listing-update"]';await fill(r.page,s,{business_name:'Test business',name:'Test operator',email:'test@example.invalid',message:'Update opening hours and our booking link.',website:'https://example.com',social:'https://example.com/social',notes:'Two changes in the same request.'});await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-intake-status]').dataset.error==='true','failure not shown');assert.equal(await r.page.$eval('[name=business_name]',e=>e.value),'Test business');r.setSupabase(ok);await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-intake-status]').textContent.includes('received'),'retry failed');const calls=r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('venue_change_requests'));assert.equal(calls.length,2);const row=JSON.parse(calls[1].body);assert.equal(row.change_type,'other');assert.match(row.proposed_change,/Two changes/);assert.match(row.proposed_change,/Social links/);}finally{await r.close();}
});
test('new business uses its own free intake and correction preserves its dedicated queue',async()=>{
 const r=await site.reader({supabase:ok});try{await r.load('/partners/add/');let s='[data-public-intake="new-business"]';await fill(r.page,s,{business_name:'Test unlisted business',location:'Mornington',name:'Test operator',email:'test@example.invalid',message:'A new local business for consideration.'});await r.page.select(`${s} [name=category]`,'food');await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-intake-status]').textContent.includes('Business received'),'new business failed');assert.match(JSON.parse(r.supabaseCalls().find(c=>c.method==='POST'&&c.url.includes('submissions')).body).title,/BUSINESS SUBMISSION/);await r.load('/contact/?type=correction');s='[data-public-intake="correction"]';await fill(r.page,s,{page:'/eat/test/',message:'The hours listed are out of date.',proposed_correction:'Open from noon on Sunday.',evidence:'The official venue website gives these hours.'});await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-public-intake="correction"] [data-intake-status]').textContent.includes('Correction received'),'correction failed');assert.equal(r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('/corrections')).length,1);assert.equal(r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('/correction_reporters')).length,0);}finally{await r.close();}
});
test('plans paginate matching results and keep the primary trip action',async()=>{
 const r=await site.reader();try{await r.load('/explore/plans/');const context=await r.page.$eval('[data-plan-index-data]',e=>Object.entries(JSON.parse(e.textContent).contexts).sort((a,b)=>b[1].length-a[1].length)[0]);await r.page.click(`[data-plan-context="${context[0]}"]`);const before=await r.page.$$eval('[data-plan-row]:not([hidden])',e=>e.length);assert.ok(before<=6);if(context[1].length>6){await r.page.click('[data-plan-more]');assert.equal(await r.page.$$eval('[data-plan-row]:not([hidden])',e=>e.length),Math.min(12,context[1].length));}assert.equal(await r.page.$eval('#all-plans-heading',e=>e.textContent),'Explore plans');assert.equal(await r.page.$$eval('[data-plan-row] [data-plan-fork]',e=>e.every(b=>b.textContent.trim()==='Make this my trip')),true);assert.doesNotMatch(await r.page.$eval('main',e=>e.textContent),/ask pi|All \d+ plans|full catalogue/i);}finally{await r.close();}
});
test('Note is exactly three sections and all public pages fit narrow screens',async()=>{
 const r=await site.reader();try{await r.load('/dispatch/');assert.equal(await r.page.$$eval('.note-page > section',e=>e.length),3);assert.equal(await r.page.$$eval('.note-page form',e=>e.length),2);assert.equal(await r.page.$$eval('.note-inside li',e=>e.length),4);assert.doesNotMatch(await r.page.$eval('main',e=>e.textContent),/Example format|Foxeys|Seasonal intelligence|promises we keep/);for(const route of ['/dispatch/','/about/','/contact/?type=general','/partners/','/partners/add/','/partners/update/','/partners/enquire/','/explore/plans/']){await r.load(route);for(const width of [390,1280]){await r.page.setViewport({width,height:844});assert.ok(await r.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${route} overflow at ${width}`);}}}finally{await r.close();}
});
test('retired routes are omitted from sitemap while new business paths are present',()=>{const xml=readFileSync(join(DIST,'sitemap.xml'),'utf8');for(const route of ['pass','editorial-approach','how-we-check','corrections','accessibility'])assert.ok(!xml.includes(`.au/${route}/</loc>`),route);for(const route of ['partners/add','partners/update','partners/enquire'])assert.ok(xml.includes(`.au/${route}/</loc>`),route);});


test('photo upload failure never sends listing and retry attaches uploaded path',async()=>{
 const r=await site.reader({supabase:[{match:'/storage/v1/',method:'POST',status:500,body:{message:'upload failed'}},...ok]});try{await r.load('/partners/update/');const s='[data-public-intake="listing-update"]';await fill(r.page,s,{business_name:'Photo test',name:'Test operator',email:'test@example.invalid',message:'Please update our gallery with this photo.'});await r.page.$eval('[name=photos]',el=>{const dt=new DataTransfer();dt.items.add(new File(['image bytes'],'photo.png',{type:'image/png'}));el.files=dt.files;});await r.page.click('[name=photo_rights]');await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-intake-status]').textContent.includes('photo could not'),'upload failure missing');assert.equal(r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('venue_change_requests')).length,0);r.setSupabase(ok);await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-intake-status]').textContent.includes('received'),'photo retry failed');const row=JSON.parse(r.supabaseCalls().find(c=>c.method==='POST'&&c.url.includes('venue_change_requests')).body);assert.match(row.proposed_change,/Photos \(submissions storage\): submissions\//);}finally{await r.close();}
});

test('correction partial receipt does not duplicate the correction on retry',async()=>{
 const r=await site.reader({supabase:[{match:'/correction_reporters',method:'POST',status:500,body:{message:'contact failed'}},...ok]});try{await r.load('/contact/?type=correction');const s='[data-public-intake="correction"]';await fill(r.page,s,{name:'Test reader',email:'test@example.invalid',page:'/eat/test/',message:'The opening hours are incorrect.',proposed_correction:'Open from noon.',evidence:'Official venue hours.'});await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-public-intake="correction"] [data-intake-status]').textContent.includes('could not be saved'),'partial receipt missing');await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-public-intake="correction"] [data-intake-status]').textContent.includes('already filed'),'retry receipt missing');assert.equal(r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('/corrections')).length,1);}finally{await r.close();}
});
test('missing dedicated correction queue falls back privately but generic errors do not',async()=>{
 for(const code of ['PGRST205','XX000']){const r=await site.reader({supabase:[{match:'/rest/v1/corrections',method:'POST',status:code==='PGRST205'?404:500,body:{code,message:'test queue failure'}},...ok]});try{await r.load('/contact/?type=correction');const s='[data-public-intake="correction"]';await fill(r.page,s,{page:'/eat/test/',message:'The opening hours are incorrect.',proposed_correction:'Open from noon.',evidence:'Official venue hours.'});await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-public-intake="correction"] [data-intake-status]').textContent!=='Sending…','submission pending');const fallback=r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('/submissions'));assert.equal(fallback.length,code==='PGRST205'?1:0);if(fallback.length){const row=JSON.parse(fallback[0].body);assert.match(row.body,/Intake type: correction/);assert.match(row.title,/CORRECTION: PI-/);assert.equal(row.submitter_email,'');}}finally{await r.close();}}
});
test('enhance enquiry preselects interest and handles missing queue or contact failure honestly',async()=>{
 for(const mode of ['missing','partial']){const r=await site.reader({supabase:[{match:mode==='missing'?'/rest/v1/partner_enquiries':'/rest/v1/partner_enquiry_contacts',method:'POST',status:mode==='missing'?404:500,body:{code:mode==='missing'?'PGRST205':'XX000',message:'test failure'}},...ok]});try{await r.load('/partners/enquire/?interest=featured-profile');const s='[data-partner-enquiry-form]';assert.equal(await r.page.$eval('[name=interest]',e=>e.value),'featured-profile');await fill(r.page,s,{business_name:'Test business',contact_name:'Test operator',email:'test@example.invalid',notes:'Please explain the enhanced page option.'});await r.page.select('[name=business_category]','other');await r.page.evaluate(()=>{const now=Date.now.bind(Date);Date.now=()=>now()+5000;});await r.page.click(`${s} [type=submit]`);await r.waitFor(()=>document.querySelector('[data-partner-enquiry-status]').getAttribute('data-status-kind')!=='info','enquiry pending');const fallback=r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('/submissions'));assert.equal(fallback.length,mode==='missing'?1:0);const status=await r.page.$eval('[data-partner-enquiry-status]',e=>({kind:e.dataset.statusKind,text:e.textContent}));assert.equal(status.kind,mode==='missing'?'success':'error');if(mode==='partial'){assert.match(status.text,/contact details did not save/);await r.page.click(s+' [type=submit]');await r.waitFor(()=>document.querySelector('[data-partner-enquiry-status]').textContent.includes('already recorded'),'duplicate protection missing');assert.equal(r.supabaseCalls().filter(c=>c.method==='POST'&&c.url.includes('/partner_enquiries')).length,1);}else{const row=JSON.parse(fallback[0].body);assert.match(row.body,/Intake type: partner-enquiry/);assert.equal(row.submitter_email,'test@example.invalid');assert.ok(!row.body.includes('test@example.invalid'));}}finally{await r.close();}}
});
test('venue intent is consented, emitted once per action and excludes personal payloads',async()=>{
 const route=routesContaining('data-evt="website_click"',1)[0];assert.ok(route,'venue intent route missing');
 const r=await site.reader();try{await r.page.evaluateOnNewDocument(()=>{localStorage.setItem('pi-consent-v1',JSON.stringify({analytics:true,version:1}));window.__intent=[];window.gtag=(...args)=>window.__intent.push(args);});await r.load(route);await r.waitFor(()=>window.__intent.some(e=>e[1]==='venue_view'),'venue view missing');await r.page.evaluate(()=>{document.dispatchEvent(new Event('astro:page-load'));for(const name of ['website_click','directions_click']){const a=document.querySelector(`[data-evt="${name}"]`);a.addEventListener('click',e=>e.preventDefault());a.click();}});const events=await r.page.evaluate(()=>window.__intent.filter(e=>['venue_view','website_click','directions_click'].includes(e[1])));for(const name of ['venue_view','website_click','directions_click'])assert.equal(events.filter(e=>e[1]===name).length,1,name);for(const e of events){assert.equal(e[2].pi_consent,'granted');assert.equal(e[2].entity_type,'venue');assert.ok(e[2].entity_slug);assert.doesNotMatch(JSON.stringify(e[2]),/@|email|booking_url|website_url/);}await r.page.evaluate(()=>{localStorage.setItem('pi-consent-v1',JSON.stringify({analytics:false,version:1}));document.querySelector('[data-evt="website_click"]').click();});assert.equal(await r.page.evaluate(()=>window.__intent.filter(e=>e[1]==='website_click').length),1);}finally{await r.close();}
});
