import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {fileURLToPath} from 'node:url';import {stripTypeScriptTypes} from 'node:module';import {build} from 'esbuild';import {currentFreePrice,feedHasCurrentFreeEntry} from '../src/lib/event-discovery.mjs';
import {hasLegacyExceptions} from '../src/lib/intelligence-series.mjs';
const now=new Date('2026-10-09T22:00:00Z'),price={label:'Free',sourceUrl:'https://example.com/synthetic-price',checkedAt:'2026-10-09T21:00:00Z',validUntil:'2026-10-09T23:00:00Z'};
test('reader free-entry filter requires current source price rather than raw feed free boolean',()=>{assert.equal(feedHasCurrentFreeEntry({f:true},now),false);assert.equal(feedHasCurrentFreeEntry({f:true,fp:price},now),true);assert.equal(feedHasCurrentFreeEntry({f:true,fp:price},new Date(price.validUntil)),false);for(const label of ['Free for children','Paid / Free entry','Complimentary with admission'])assert.equal(currentFreePrice({verifiedPrice:{...price,label}},now),null);});
test('actual browser matchesFilters excludes expired free price at the reader clock',()=>{const source=readFileSync(new URL('../src/pages/whats-on/index.astro',import.meta.url),'utf8');const fragment=source.match(/const matchesFilters = ([^]*?\n    \};)/)[1];const expression=stripTypeScriptTypes(fragment).replace('new Date()','clock');const run=new Function('filters','feedHasCurrentFreeEntry','hasLegacyExceptions','clock','return '+expression)(()=>({free:true}),feedHasCurrentFreeEntry,hasLegacyExceptions,now);assert.equal(run({f:true}),false);assert.equal(run({f:true,fp:price}),true);const later=new Function('filters','feedHasCurrentFreeEntry','hasLegacyExceptions','clock','return '+expression)(()=>({free:true}),feedHasCurrentFreeEntry,hasLegacyExceptions,new Date(price.validUntil));assert.equal(later({f:true,fp:price}),false);assert.doesNotMatch(source,/value\.free && !entry\.f/);});
const bundle=await build({entryPoints:[fileURLToPath(new URL('../src/lib/events.ts',import.meta.url))],bundle:true,write:false,format:'esm',platform:'node',define:{'import.meta.env.PUBLIC_EVENT_OCCURRENCE_MODEL':'"off"'}});const {eventPriceLabel,eventHasKnownPrice}=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
test('actual detail price display refuses raw and expired free fallback',()=>{const raw={priceTier:'free',freePaid:'Free',lens:['free']};assert.equal(eventPriceLabel(raw,now),'Check organiser for pricing');assert.equal(eventHasKnownPrice(raw,now),false);assert.equal(eventPriceLabel({...raw,verifiedPrice:price},now),'Free');assert.equal(eventHasKnownPrice({...raw,verifiedPrice:price},now),true);assert.equal(eventPriceLabel({...raw,verifiedPrice:price},new Date(price.validUntil)),'Check organiser for pricing');assert.equal(eventHasKnownPrice({...raw,verifiedPrice:price},new Date(price.validUntil)),false);});
test('actual upcoming route omits unverified raw freePaid classification',()=>{const source=readFileSync(new URL('../src/pages/whats-on/upcoming.json.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/freePaid:\s*e\.data\.freePaid/);});

test('actual calendar expiry scheduler withdraws Free-filter results at verified price expiry',()=>{const source=readFileSync(new URL('../src/pages/whats-on/index.astro',import.meta.url),'utf8');let fragment=source.slice(source.indexOf('    function scheduleFreeExpiry'),source.indexOf('    let feedPromise'));fragment=stripTypeScriptTypes(fragment);let instant=now.getTime(),callback,delay,applied=0;class Clock extends Date {constructor(...args){super(...(args.length?args:[instant]));}static now(){return instant;}}const run=new Function('currentFreePrice','Date','setTimeout','clearTimeout','daysEl','filters','applyScope','activeScope','activeCustomRange', 'let freeExpiryTimer=null;'+fragment+'return scheduleFreeExpiry;')(currentFreePrice,Clock,(fn,ms)=>{callback=fn;delay=ms;return 1;},()=>{}, {isConnected:true},()=>({free:true}),()=>{applied++;},'weekend',null);run([{f:true,fp:price}]);assert.equal(delay,3600001);instant=Date.parse(price.validUntil)+1;callback();assert.equal(applied,1);});

test('legacy event card and static event facets do not promise perpetual Free classification',()=>{assert.doesNotMatch(readFileSync(new URL('../src/components/EventCard.astro',import.meta.url),'utf8'),/data-free=/);const facets=readFileSync(new URL('../src/lib/facets.ts',import.meta.url),'utf8');const eventPart=facets.slice(facets.indexOf('function facetsForEvent('),facets.indexOf('function facetsForItinerary('));assert.doesNotMatch(eventPart,/emit\(out, 'price'/);});

const facetBundle=await build({entryPoints:[fileURLToPath(new URL('../src/lib/facets.ts',import.meta.url))],bundle:true,write:false,format:'esm',platform:'node'});const {getFacets}=await import('data:text/javascript;base64,'+Buffer.from(facetBundle.outputFiles[0].text).toString('base64'));
test('actual event facet projection omits static price promises for raw and verified prices',()=>{for(const data of [{priceTier:'free',freePaid:'Free'},{priceTier:'free',verifiedPrice:price},{priceTier:'under-50'}])assert.equal(getFacets('event',data).price,undefined);});
