import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {captureEventInventory,assertInventoryUnchanged,conflictsWithInventory} from './event-editorial-inventory.mjs';
test('actual Astro JSON inventory detects omitted legacy duplicate and later source drift',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'pi-inventory-'));try{const data={eventId:'legacy',title:'Tech class',venueName:'Rosebud Library',startDate:'2026-10-13',officialEventUrl:'https://official.example/class'};await writeFile(path.join(root,'legacy.json'),JSON.stringify(data));const snapshot=await captureEventInventory({root});assert.equal(snapshot.entries.length,1);assert.equal(conflictsWithInventory({...data,eventId:'discovered'},snapshot).length,1);assert.equal(conflictsWithInventory({...data,eventId:'discovered',startDate:'2026-10-14'},snapshot).length,0);await writeFile(path.join(root,'extra.json'),JSON.stringify({...data,eventId:'other'}));await assert.rejects(assertInventoryUnchanged(snapshot),/changed/);}finally{await rm(root,{recursive:true,force:true});}});
test('human identity holds and recurring ambiguity cannot be overridden',()=>{const data={eventId:'held',status:'review',title:'Session',venueName:'Library',startDate:'2026-10-13',officialEventUrl:'https://official.example/class'};const snapshot={fingerprint:'test',entries:[{file:'held.json',data}]};assert.equal(conflictsWithInventory(data,snapshot).length,1);data.recurrence='weekly';assert.equal(conflictsWithInventory({...data,eventId:'new',startDate:'2026-12-10'},snapshot).length,1);});

test('ordinary machine refresh permitted but human holds and withdrawals remain protected',()=>{const base={eventId:'refresh',status:'published',intelligence:{approvalMode:'automated',approvedBy:'PI editorial policy'}};const snapshot=data=>({fingerprint:'test',entries:[{file:'existing.json',data}]});assert.deepEqual(conflictsWithInventory(base,snapshot(base)),[]);for(const change of [{cancelled:true},{postponed:true},{sourceReview:{required:true}},{reviewHold:{actor:'James'}},{factualReviewHold:true},{reviewStatus:'held'},{reviewStatus:'rejected'},{reviewStatus:'hold'},{reviewStatus:'archived'},{reviewStatus:'withdrawn'}])assert.equal(conflictsWithInventory(base,snapshot({...base,...change})).length,1);});

test('empty directory nesting is bounded independently of JSON byte count',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'pi-inventory-depth-'));try{let nested=root;for(let i=0;i<18;i++){nested=path.join(nested,'d');await mkdir(nested);}await assert.rejects(captureEventInventory({root}),/depth budget/);}finally{await rm(root,{recursive:true,force:true});}});

test('inventory bounded read refuses deterministic concurrent growth and named replacement',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'pi-inventory-race-'));t.after(()=>rm(dir,{recursive:true,force:true}));const file=path.join(dir,'event.json');await writeFile(file,'{}');await assert.rejects(captureEventInventory({root:dir,checkpoint:async()=>writeFile(file,'{} ')}),/grew|changed/);await writeFile(file,'{}');await assert.rejects(captureEventInventory({root:dir,checkpoint:async()=>{await rm(file);await writeFile(file,'{}');}}),/changed/);});
