import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {fileURLToPath} from 'node:url';import {approvedEventContent} from '../src/lib/event-publication.mjs';
const result=await build({entryPoints:[fileURLToPath(new URL('../src/pages/whats-on/_data.ts',import.meta.url))],bundle:true,write:false,format:'esm',platform:'node',define:{'import.meta.env.PUBLIC_EVENT_OCCURRENCE_MODEL':'"off"'},plugins:[{name:'fixture-content',setup(build){build.onResolve({filter:/^astro:content$/},()=>({path:'astro:content',namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export async function getCollection(name, filter) {const entries=globalThis.__piLoaderFixtures ?? []; return filter ? entries.filter(filter) : entries;}',loader:'js'}));}}]});
const {loadLiveEvents,feedFor}=await import('data:text/javascript;base64,'+Buffer.from(result.outputFiles[0].text).toString('base64'));
const now=new Date('2026-10-09T22:00:00Z');
function fixture(extra={}){return {id:extra.slug??'synthetic-loader',data:{slug:'synthetic-loader',title:'Synthetic loader fixture',status:'published',summary:'Synthetic only',suburb:'Mornington',place:{id:'mornington'},venueName:'Synthetic venue',startDate:new Date('2026-10-10'),endDate:new Date('2026-10-10'),...extra}};}
function approved(extra={}){const e=fixture(extra);e.data.intelligence={revision:'fixture-only',approvedBy:'James',approvedAt:'2026-10-09T10:00:00Z',reviewedAt:'2026-10-09T10:00:00Z',factScore:100,evidenceIds:['synthetic'],geography:{shireConfirmed:true,verifiedBy:'James',evidenceId:'synthetic-location',checkedAt:'2026-10-09T10:00:00Z'}};e.data.intelligence.approvedContent=approvedEventContent(e.data);return e;}
async function load(entries,options){globalThis.__piLoaderFixtures=entries;try{return await loadLiveEvents(now,options);}finally{delete globalThis.__piLoaderFixtures;}}
test('actual calendar loader and feed exclude unknown, border and conflicting Shire locations',async()=>{const entries=[fixture({slug:'unknown',suburb:undefined,place:undefined}),fixture({slug:'border',suburb:'Pearcedale',place:'pearcedale'}),fixture({slug:'conflict',suburb:'Seaford',place:'mornington'}),fixture()];const loaded=await load(entries);assert.deepEqual(loaded.map(e=>e.slug),['synthetic-loader']);assert.equal(feedFor(loaded).length,1);});
test('actual calendar loader requires fresh reviewed import geography and supplied-clock approval',async()=>{const valid=approved(),missing=approved({slug:'missing'}),future=approved({slug:'future'}),stale=approved({slug:'stale'});delete missing.data.intelligence.geography;missing.data.intelligence.approvedContent=approvedEventContent(missing.data);future.data.intelligence.approvedAt='2026-10-11T00:00:00Z';stale.data.intelligence.geography.checkedAt='2026-09-01';stale.data.intelligence.approvedContent=approvedEventContent(stale.data);assert.deepEqual((await load([missing,future,stale,valid])).map(e=>e.slug),['synthetic-loader']);});
test('actual loader retains published/current and explicit cancellation-option semantics within Shire',async()=>{const cancelled=fixture({slug:'cancelled',cancelled:true}),draft=fixture({slug:'draft',status:'review'});assert.deepEqual(await load([cancelled,draft]),[]);assert.deepEqual((await load([cancelled,draft],{includeCancelled:true})).map(e=>e.slug),['cancelled']);});
