import test from 'node:test';import assert from 'node:assert/strict';
import {publicPlanningCatalog,projectSavedEvent,gateRemoteRecommendations} from './event-planning.mjs';
import {pickRelatedEventsForPlace} from './related.ts';
import {approvedEventContent} from './event-publication.mjs';
const now=new Date('2026-10-04T00:00:00Z');
const entry=(slug,changes={})=>({id:slug,data:{slug,title:'Current '+slug,status:'published',startDate:new Date('2026-10-09'),endDate:new Date('2026-10-09'),suburb:'Mornington',place:{id:'mornington'},venueName:'Town venue',recurrence:'one-off',bookingStatus:'available',lastVerifiedAt:'2026-10-03',summary:'Official current notes',coordinates:{lat:-38.2,lng:145.04},...changes}});
test('Related actual consumer refuses draft, cancelled, stale source and outside Shire references, selects current effective dates',()=>{const events=[entry('later',{startDate:new Date('2026-10-15'),endDate:new Date('2026-10-15')}),entry('draft',{status:'draft'}),entry('cancelled',{cancelled:true}),entry('unchecked',{sourceUpdatedAt:'2026-10-04',lastVerifiedAt:'2026-10-01'}),entry('outside',{suburb:'Frankston',place:{id:'mornington'}}),entry('current')];const selected=pickRelatedEventsForPlace('mornington',events,{from:now,limit:4});assert.deepEqual(selected.map(x=>x.data.slug),['current','later']);});
test('Reader saves retain personal identity and notes when withdrawn but remove trip/calendar/booking and coordinates',()=>{const saved={kind:'event',slug:'cancelled',title:'Old saved title',href:'https://organiser.example/book',note:'My own plans',meta:{personal:'keep'}};const catalog=publicPlanningCatalog([entry('cancelled',{cancelled:true}),entry('draft',{status:'draft'})],now);assert.equal(catalog.length,1);const projected=projectSavedEvent(saved,catalog,{now});assert.equal(projected.title,'Old saved title');assert.equal(projected.eventStatus,'Cancelled');assert.equal(projected.note,'My own plans');assert.deepEqual(projected.meta,{personal:'keep'});assert.equal(projected.eventAvailable,false);assert.equal(projected.calendarAllowed,false);assert.equal(projected.bookingAllowed,false);assert.equal(projected.lat,null);assert.equal(projected.href,'/whats-on/cancelled/');const unknown=projectSavedEvent({...saved,slug:'removed'},catalog,{now});assert.equal(unknown.href,'/whats-on/');assert.equal(unknown.eventAvailable,false);});
test('Current save uses canonical source title/date/location and withdraws at supplied later clock without mutating storage',()=>{const saved={kind:'event',slug:'current',title:'Stale title',href:'/stale/',note:'Retain'},catalog=publicPlanningCatalog([entry('current')],now);const projected=projectSavedEvent(saved,catalog,{now});assert.equal(projected.eventAvailable,true);assert.equal(projected.title,'Current current');assert.equal(projected.href,'/whats-on/current/');assert.equal(projected.lat,null);assert.match(projected.dek,/Official current notes/);assert.equal(saved.title,'Stale title');assert.equal(projectSavedEvent(saved,catalog,{now:new Date('2026-10-11')}).eventAvailable,false);});
test('Remote event recommendations cannot invent dates, prices or bookings and unknown/withdrawn events are rejected',()=>{const catalog=publicPlanningCatalog([entry('current'),entry('cancelled',{cancelled:true})],now),recs=[{kind:'event',slug:'current',title:'Invented remote title',price_band:'$1',why:'Tomorrow free',booking_url:'https://unsafe.example/book'},{href:'/whats-on/cancelled/',kind:'venue'},{kind:'event',slug:'missing'},{href:'https://attacker.example/whats-on/current/',kind:'event'},{href:'javascript:alert(1)',kind:'venue'},{href:'/eat/montalto/',kind:'venue',title:'Existing venue'}];const selected=gateRemoteRecommendations(recs,catalog,{now});assert.equal(selected.length,2);assert.equal(selected[0].title,'Current current');assert.equal(selected[0].price_band,null);assert.equal(selected[0].booking_url,undefined);assert.equal(selected[0].href,'/whats-on/current/');assert.notEqual(selected[0].why,'Tomorrow free');assert.equal(selected[1].title,'Existing venue');});
test('Browser catalogue and remote event payload exclude private CMS fields and arbitrary remote facts',()=>{const catalog=publicPlanningCatalog([entry('current',{internalNotes:'PRIVATE-NOTES',editorialProvenance:{unpublished:'PRIVATE-PROVENANCE'},unknownPrivateField:'PRIVATE-UNKNOWN'})],now),encoded=JSON.stringify(catalog);assert.ok(!encoded.includes('PRIVATE-'));assert.equal(catalog[0].data.title,'Current current');const result=gateRemoteRecommendations([{kind:'event',slug:'current',price:'Invented price',bookingUrl:'https://invented.example',internalNotes:'PRIVATE-REMOTE',dates:'Tomorrow'}],catalog,{now})[0];assert.equal(result.price,undefined);assert.equal(result.bookingUrl,undefined);assert.equal(result.dates,undefined);assert.equal(result.internalNotes,undefined);});
test('Remote verified prices expire under the supplied clock and carry exact expiry for browser withdrawal',()=>{const price={label:'$25',sourceUrl:'https://example.org/price',checkedAt:'2026-10-03T00:00:00Z',validUntil:'2026-10-04T00:01:00Z'},catalog=publicPlanningCatalog([entry('current',{verifiedPrice:price})],now),input=[{kind:'event',slug:'current'}];const current=gateRemoteRecommendations(input,catalog,{now})[0];assert.equal(current.price_band,'$25');assert.equal(current.price_expires_at,'2026-10-04T00:01:00.000Z');assert.equal(gateRemoteRecommendations(input,catalog,{now:new Date('2026-10-04T00:02:00Z')})[0].price_band,null);});


test('Saved coordinates require matching fresh explicit proof, with legacy details preserved without a point',()=>{const saved={kind:'event',slug:'verified-point',note:'Retain my plan'};function approved(mutate=()=>{}){const record=entry('verified-point',{intelligence:{revision:'synthetic-coordinate-fixture',approvedBy:'James',approvedAt:'2026-10-03',reviewedAt:'2026-10-03',factScore:100,evidenceIds:['synthetic-geo','synthetic-point'],geography:{shireConfirmed:true,verifiedBy:'James',checkedAt:'2026-10-03',evidenceId:'synthetic-geo',coordinateCheckedAt:'2026-10-03T00:00:00Z',coordinateEvidenceId:'synthetic-point',coordinateSourceUrl:'https://example.org/venue',coordinates:{lat:-38.2,lng:145.04}}}});mutate(record.data);record.data.intelligence.approvedContent=approvedEventContent(record.data);return publicPlanningCatalog([record],now);}const legacy=projectSavedEvent({...saved,slug:'current'},publicPlanningCatalog([entry('current')],now),{now});assert.equal(legacy.eventAvailable,true);assert.equal(legacy.lat,null);assert.equal(legacy.lng,null);const verified=projectSavedEvent(saved,approved(),{now});assert.equal(verified.lat,-38.2);assert.equal(verified.lng,145.04);assert.equal(verified.note,'Retain my plan');for(const mutate of [data=>delete data.intelligence.geography.coordinateEvidenceId,data=>delete data.intelligence.geography.coordinateCheckedAt,data=>data.intelligence.geography.coordinateCheckedAt='2026-09-20',data=>data.intelligence.geography.coordinateCheckedAt='2026-10-05',data=>data.intelligence.geography.coordinates.lng=145.1,data=>data.intelligence.geography.checkedAt='2026-09-20',data=>data.intelligence.geography.coordinateSourceUrl='javascript:alert(1)']){const result=projectSavedEvent(saved,approved(mutate),{now});assert.equal(result.lat,null);assert.equal(result.lng,null);assert.equal(result.note,'Retain my plan');}});

test('Withdrawn catalogues serialize compact idempotent tombstones without closed venue media or history',()=>{const closed=entry('withdrawn-control',{cancelled:true,venueName:'Closed Venue Marker',heroImage:{src:'/images/Closed-Venue-Marker.webp'},summary:'Closed Venue Marker history',coordinates:{lat:-38.2,lng:145.04},internalNotes:'private',cancellationNote:'Closed Venue Marker closure'});const catalog=publicPlanningCatalog([closed],now);assert.equal(catalog.length,1);assert.deepEqual(Object.keys(catalog[0].data).sort(),['detailHref','eventStatus','planningTombstone','slug']);assert.ok(!JSON.stringify(catalog).includes('Closed Venue Marker'));assert.ok(!JSON.stringify(catalog).includes('Closed-Venue-Marker'));assert.deepEqual(publicPlanningCatalog(catalog,now),catalog);const saved={kind:'event',slug:'withdrawn-control',title:'My saved title',note:'My private note',image_url:'/images/old.webp'};const projected=projectSavedEvent(saved,catalog,{now});assert.equal(projected.title,'My saved title');assert.equal(projected.note,'My private note');assert.equal(projected.eventStatus,'Cancelled');assert.equal(projected.image_url,'');assert.equal(projected.href,'/whats-on/withdrawn-control/');assert.equal(projected.eventAvailable,false);assert.equal(projected.lat,null);assert.equal(projected.bookingAllowed,false);assert.equal(projected.calendarAllowed,false);});
