import test from 'node:test';
import assert from 'node:assert/strict';
import {eventMapItems} from './event-map.mjs';
const now = new Date('2026-10-04T11:00:00Z');
function fixture() { const data = {title:'Synthetic mapped session',venueName:'Verified gallery',suburb:'Mornington',coordinates:{lat:-38.22,lng:145.04},intelligence:{geography:{shireConfirmed:true,verifiedBy:'James',evidenceId:'geo-fixture',checkedAt:'2026-10-03T11:00:00Z',coordinates:{lat:-38.22,lng:145.04},coordinateCheckedAt:'2026-10-03T00:00:00Z',coordinateEvidenceId:'coordinates-fixture',coordinateSourceUrl:'https://example.com/venue'}}};return {event:{data},originalEvent:{data:structuredClone(data)},slug:'synthetic-session',href:'/whats-on/synthetic-session/',day:'2026-10-10',dateLabel:'Sat 10 October',kind:'event',occurrence:{endsAt:'2026-10-10T12:00:00Z'}}; }
test('map projection carries effective session, explicit coordinates and honest content kind',()=>{const p=fixture();const [pin]=eventMapItems([p],{now});assert.equal(pin.title,p.event.data.title);assert.equal(pin.lat,-38.22);assert.equal(pin.href,p.href);assert.deepEqual(pin.meta,['Event','Sat 10 October','Mornington']);p.kind='offer';assert.equal(eventMapItems([p],{now})[0].meta[0],'Offer');});
test('unknown, expired, future, altered and invalid coordinates do not become pins',()=>{for(const mutate of [p=>delete p.event.data.intelligence,p=>p.event.data.intelligence.geography.shireConfirmed=false,p=>p.event.data.intelligence.geography.verifiedBy='Crawler',p=>p.event.data.intelligence.geography.checkedAt='2026-09-01',p=>p.event.data.intelligence.geography.checkedAt='2026-10-05',p=>delete p.event.data.intelligence.geography.coordinateEvidenceId,p=>p.event.data.coordinates.lng=NaN,p=>p.event.data.coordinates.lat=-38.3,p=>p.event.data.intelligence.geography.coordinateSourceUrl='javascript:alert(1)']){const p=fixture();mutate(p);assert.deepEqual(eventMapItems([p],{now}),[]);}});
test('moved sessions cannot reuse the original venue coordinate evidence',()=>{const p=fixture();p.event.data.venueName='Different gallery';assert.deepEqual(eventMapItems([p],{now}),[]);});

test('zero latitude or longitude cannot locate a Shire event even when a matching receipt is present',()=>{assert.equal(eventMapItems([fixture()],{now}).length,1);for(const key of ['lat','lng']){const promotion=fixture();promotion.event.data.coordinates[key]=0;promotion.event.data.intelligence.geography.coordinates[key]=0;assert.deepEqual(eventMapItems([promotion],{now}),[]);}});
test('coordinate evidence has its own clock and the earliest pin expiry wins',()=>{const p=fixture();p.event.data.intelligence.geography.coordinateCheckedAt='2026-09-28T11:00:00Z';assert.equal(eventMapItems([p],{now})[0].expiresAt,'2026-10-05T11:00:00.000Z');assert.deepEqual(eventMapItems([p],{now:new Date('2026-10-05T11:00:00Z')}),[]);for(const value of [undefined,'invalid','2026-10-05T00:00:00Z','2026-09-27T11:00:00Z']){p.event.data.intelligence.geography.coordinateCheckedAt=value;assert.deepEqual(eventMapItems([p],{now}),[]);}p.event.data.intelligence.geography.coordinateCheckedAt='2026-10-04T00:00:00Z';p.event.data.expiresAt='2026-10-04T12:00:00Z';assert.equal(eventMapItems([p],{now})[0].expiresAt,'2026-10-04T12:00:00.000Z');});
