import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';
import { selectEventPromotions, eventPromotionEntries, refreshEventPromotions, installEventPromotionRefresh } from './event-discovery.mjs';
import { approvedEventContent, publicEventData } from './event-publication.mjs';
const now = new Date('2026-10-09T22:00:00Z');
const options = {now};
function fixture(extra={}) {return {id:'synthetic-session',data:{slug:'synthetic-session',title:'Synthetic session',status:'published',venueName:'Synthetic venue',suburb:'Mornington',place:{id:'mornington'},venue:{id:'synthetic-venue'},startDate:new Date('2026-10-10'),endDate:new Date('2026-10-10'),startTime:'10:00',endTime:'17:00',summary:'Synthetic fixture only',...extra}};}
function approved(extra={}) {const e=fixture({...extra,intelligence:{revision:'fixture-revision',approvedBy:'James',approvedAt:'2026-10-09T10:00:00Z',reviewedAt:'2026-10-09T10:00:00Z',factScore:100,evidenceIds:['fixture-evidence'],geography:{shireConfirmed:true,verifiedBy:'James',evidenceId:'fixture-location',checkedAt:'2026-10-09T10:00:00Z'}}});e.data.intelligence.approvedContent=approvedEventContent(e.data);return e;}

test('eligible projection preserves editorial order, window, identity and explicit filters',()=>{const a=fixture(),b=fixture({slug:'second',title:'Second'});const result=selectEventPromotions([b,a],{...options,limit:1,placeId:'mornington',venueId:'synthetic-venue'});assert.equal(result[0].slug,'second');assert.equal(result[0].day,'2026-10-10');assert.equal(result[0].href,'/whats-on/second/');assert.equal(result[0].originalEvent,b);assert.deepEqual(selectEventPromotions([a],{...options,placeId:'rye'}),[]);assert.deepEqual(selectEventPromotions([a],{...options,venueId:'another'}),[]);assert.deepEqual(selectEventPromotions([a],{...options,windowStart:new Date('2026-10-12'),windowDays:2}),[]);});
test('all disqualifying public dispositions fail closed independent of feature flags',()=>{for(const extra of [{status:'review'},{status:'scheduled'},{status:'archived'},{cancelled:true},{skipThis:true},{bookingStatus:'sold-out'},{bookingStatus:'closed'},{postponed:true},{expiresAt:'2026-10-09'},{sourceUpdatedAt:'2026-10-09',lastVerifiedAt:'2026-10-08'},{startDate:new Date('2026-09-01'),endDate:new Date('2026-09-01')}])assert.deepEqual(selectEventPromotions([fixture(extra)],options),[],JSON.stringify(extra));});
test('title text cannot establish Shire scope; unknown, conflicts and border towns omitted',()=>{for(const extra of [{place:undefined,suburb:undefined,title:'Mornington session'},{place:'frankston',suburb:'Frankston'},{place:'mornington',suburb:'Seaford'},{place:'pearcedale',suburb:'Pearcedale'}])assert.deepEqual(selectEventPromotions([fixture(extra)],options),[]);});
test('import approvals require immutable approved content and fresh James geography proof',()=>{assert.equal(selectEventPromotions([approved()],options).length,1);for(const mutate of [e=>delete e.data.intelligence.approvedContent,e=>e.data.title='Changed after approval',e=>delete e.data.intelligence.geography,e=>e.data.intelligence.geography.verifiedBy='Collector',e=>e.data.intelligence.geography.checkedAt='2026-09-01',e=>e.data.intelligence.geography.checkedAt='2026-10-11',e=>e.data.intelligence.approvedBy='Collector']){const e=approved();mutate(e);assert.deepEqual(selectEventPromotions([e],options),[]);}});
test('serialized browser catalog and repeated effective projection retain original approval binding',()=>{const a=approved();const p=selectEventPromotions([a],options)[0];assert.equal(selectEventPromotions(JSON.parse(JSON.stringify([a])),options).length,1);assert.equal(selectEventPromotions([p.event],options).length,1);p.event.data.title='consumer tamper';assert.equal(selectEventPromotions([p.event],options)[0].event.data.title,a.data.title);assert.equal(eventPromotionEntries([a],options)[0].data._promotionDay,'2026-10-10');});
test('content kind labels preserve separate session/validity meanings',()=>{for(const kind of ['event','experience','offer']){const [p]=selectEventPromotions([fixture({contentKind:kind})],options);assert.equal(p.kind,kind);if(kind==='offer')assert.match(p.dateLabel,/Offer valid/);if(kind==='experience')assert.match(p.dateLabel,/Experience session/);}});
test('series projection selects actual rescheduled day and omits unknown moved destinations',()=>{const sessions=[{id:'fixture',originalDate:'2026-10-09',date:'2026-10-10',status:'rescheduled',startTime:'12:00',endTime:'17:00',venueName:'Synthetic venue',sourceUrl:'https://example.com/session'}];const e=approved({recurrence:'weekly',seriesOccurrences:sessions});const [p]=selectEventPromotions([e],options);assert.equal(p.day,'2026-10-10');assert.equal(p.event.data.startTime,'12:00');assert.equal(p.event.data.postponedFrom,'2026-10-09');e.data.seriesOccurrences[0].venueName='Other venue';e.data.intelligence.approvedContent=approvedEventContent(e.data);assert.deepEqual(selectEventPromotions([e],options),[]);});
test('all cancelled later sessions cannot be promoted using an old series start',()=>{const e=approved({recurrence:'weekly',seriesOccurrences:[{id:'fixture',originalDate:'2026-10-10',date:'2026-10-10',status:'cancelled',venueName:'Synthetic venue'}]});assert.deepEqual(selectEventPromotions([e],options),[]);});
test('invalid bounds and malformed clock/date fail without throwing',()=>{for(const o of [{now:'bad'},{...options,windowStart:'bad'},{...options,windowDays:0},{...options,windowDays:400},{...options,limit:0}])assert.deepEqual(selectEventPromotions([fixture()],o),[]);assert.deepEqual(selectEventPromotions([fixture({startDate:'bad'})],options),[]);});
test('browser recheck removes ended promotions and empty sections rather than silently changing their dates',()=>{let removed=false,section={hidden:false,querySelectorAll:q=>q==='[data-event-promotion]'&&!removed?[{}]:[]};const e=fixture();const node={getAttribute:k=>k==='data-event-promotion'?JSON.stringify(e):'2026-10-10',remove:()=>{removed=true;}};const root={querySelectorAll:q=>q==='[data-event-promotion]'?[node]:[section]};refreshEventPromotions(root,now);assert.equal(removed,false);refreshEventPromotions(root,new Date('2026-10-11T10:00:00Z'));assert.equal(removed,true);assert.equal(section.hidden,true);});
test('browser recheck hides the swipe hint when a lunchtime pick ends but retains a later pick',()=>{const hint={hidden:false},nodes=[];for(const [slug,endTime] of [['lunch','13:00'],['afternoon','17:00']]){const event=fixture({slug,endTime});const node={getAttribute:k=>k==='data-event-promotion'?JSON.stringify(event):'2026-10-10',remove:()=>{nodes.splice(nodes.indexOf(node),1);}};nodes.push(node);}const section={hidden:false,querySelectorAll:q=>q==='[data-event-promotion]'?nodes:q==='[data-event-promotion-multi-hint]'?[hint]:[]};const root={querySelectorAll:q=>q==='[data-event-promotion]'?[...nodes]:[section]};refreshEventPromotions(root,new Date('2026-10-10T01:59:00Z'));assert.equal(nodes.length,2);assert.equal(hint.hidden,false);refreshEventPromotions(root,new Date('2026-10-10T02:01:00Z'));assert.equal(nodes.length,1);assert.equal(hint.hidden,true);assert.equal(section.hidden,false);});

// Execute the actual homepage selection code with its real pure dependencies;
// only the feature switch is replaced to prove safety even when it is off.
let home = stripTypeScriptTypes(readFileSync(new URL('../components/v5/home/home-data.ts',import.meta.url),'utf8'));
home=home.replace(/import \{ USE_OCCURRENCE_MODEL \} from '[^']+';/,"const USE_OCCURRENCE_MODEL=false;");
home=home.replace(/from '([^']+)'/g,(_,path)=>`from '${new URL(path+(path.endsWith('.mjs')?'':'.ts'),new URL('../components/v5/home/home-data.ts',import.meta.url)).href}'`);
const {selectWeekendPicks,pickDateISO}=await import('data:text/javascript;base64,'+Buffer.from(home).toString('base64'));
test('actual homepage selector honours editorial order only among eligible approved weekend sessions',()=>{const a=fixture(),b=fixture({slug:'second'}),cancel=fixture({slug:'cancelled',cancelled:true});const picks=[{data:{weekendStart:new Date('2026-10-10'),picks:[{eventSlug:'cancelled',position:0},{eventSlug:'second',position:1,editorVerdict:'Fixture verdict'},{eventSlug:a.id,position:2}]}}];const result=selectWeekendPicks(picks,[a,b,cancel],now);assert.deepEqual(result.picks.map(p=>p.event.data.slug),['second','synthetic-session']);assert.equal(pickDateISO(result.picks[0].event,now),'2026-10-10');});
test('actual homepage refuses post-approval public content drift even with occurrence flag off',()=>{const e=approved();e.data.summary='Changed without approval';assert.equal(selectWeekendPicks([], [e],now).picks.length,0);});


test('public browser payload excludes unknown internal fields and still validates approval',()=>{const e=approved();e.data.internalNotes='PRIVATE';e.data.provenance={secret:'PRIVATE'};e.data.cmsDraft='PRIVATE';const entry={id:e.id,data:publicEventData(e.data)};assert.doesNotMatch(JSON.stringify(entry),/PRIVATE|internalNotes|cmsDraft/);assert.equal(selectEventPromotions([entry],options).length,1);});
test('freshness installer has one timer/listener set across duplicate components and navigation',()=>{const documentListeners=new Map(),windowListeners=new Map();let active=0;const document={querySelectorAll:()=>[],addEventListener:(k,f)=>documentListeners.set(k,f),removeEventListener:k=>documentListeners.delete(k)};const window={addEventListener:(k,f)=>windowListeners.set(k,f),removeEventListener:k=>windowListeners.delete(k),setInterval:()=>{active++;return 1;},clearInterval:()=>active--};const first=installEventPromotionRefresh(window,document);assert.equal(installEventPromotionRefresh(window,document),first);assert.equal(active,1);assert.equal(documentListeners.size,2);documentListeners.get('astro:before-swap')();assert.equal(active,0);documentListeners.get('astro:page-load')();assert.equal(active,1);first.dispose();assert.equal(active,0);assert.equal(documentListeners.size,0);assert.equal(windowListeners.size,0);});
test('actual EventStrip frontmatter filters raw props before its cap and label projection',()=>{let source=readFileSync(new URL('../components/EventStrip.astro',import.meta.url),'utf8').split('---')[1];source=stripTypeScriptTypes(source).replace(/^import[^;]*;s*/gm,'');const visible=new Function('Astro','selectEventPromotions',source+'; return visible;')({props:{events:[fixture({cancelled:true}),fixture({contentKind:'offer'})],now,limit:1}},selectEventPromotions);assert.equal(visible.length,1);assert.equal(visible[0].kind,'offer');assert.match(visible[0].dateLabel,/Offer valid/);});
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
for(const type of ['eat','wine','stay'])test('actual '+type+' venue selector rejects wrong venue and unpublished events',async()=>{const text=readFileSync(new URL('../pages/'+type+'/[slug].astro',import.meta.url),'utf8');const expression=text.match(/const venueEvents = ([^]*?);/)[1];const result=await new AsyncFunction('getCollection','eventPromotionEntries','slug', 'return '+expression.replace('new Date()','new Date("2026-10-09T22:00:00Z")'))(async()=>[fixture({slug:'wrong',venue:'other'}),fixture({slug:'draft',status:'review'}),fixture()],eventPromotionEntries,'synthetic-venue');assert.deepEqual(result.map(e=>e.data.slug),['synthetic-session']);});
test('actual place selector omits unknown/out-of-place records and uses bounded current sessions',()=>{const text=readFileSync(new URL('../pages/explore/places/[slug].astro',import.meta.url),'utf8');const expression=text.match(/const eventsForMap = ([^]*?);/)[1];const result=new Function('eventPromotionEntries','allEvents','placeSlug','return '+expression.replace('new Date()','new Date("2026-10-09T22:00:00Z")'))(eventPromotionEntries,[fixture({slug:'wrong',place:'rye',suburb:'Rye'}),fixture({slug:'expired',expiresAt:'2026-10-01'}),fixture()],'mornington');assert.deepEqual(result.map(e=>e.data.slug),['synthetic-session']);});
test('actual Journal contextual selector uses explicit references, never title substring',async()=>{const text=readFileSync(new URL('../pages/journal/[slug].astro',import.meta.url),'utf8');let fragment=text.slice(text.indexOf('const contextPlaceIds'),text.indexOf('const allItineraries'));fragment=stripTypeScriptTypes(fragment).replace('new Date()','new Date("2026-10-09T22:00:00Z")');const run=new AsyncFunction('article','getCollection','selectEventPromotions',fragment+'return relatedEvents;');const collection=async()=>[fixture()];assert.equal((await run({data:{title:'Mornington',relatedPlaces:[],relatedVenues:[]}},collection,selectEventPromotions)).length,0);assert.equal((await run({data:{relatedPlaces:[{id:'mornington'}]}},collection,selectEventPromotions)).length,1);});
