import test from 'node:test';
import assert from 'node:assert/strict';
import { editorialFixture } from '../../../ops/event-intelligence/editorial-fixtures.mjs';
import { buildEditorialManifest } from '../../../ops/event-intelligence/editorial-automation.mjs';
import { approvedEventContent, publicEventData, hasAutomatedEditorialApproval, isPublicEventRecord } from './event-publication.mjs';
function fixture(){const f=editorialFixture(); const manifest=buildEditorialManifest([{candidate:f.candidate,evidence:f.evidence,bundle:f.bundle}],f.context);return {now:f.now,manifest,record:manifest.records[0]};}
test('only trusted generated manifest admits automatic receipt; installed baseline stays disabled',()=>{const {record,manifest,now}=fixture(); assert.equal(hasAutomatedEditorialApproval(record,now,manifest),true); assert.equal(hasAutomatedEditorialApproval(record,now),false); assert.equal(isPublicEventRecord({...record,status:'published'},now),false); assert.equal(hasAutomatedEditorialApproval(record,now,{...manifest,entries:[]}),false); assert.equal(hasAutomatedEditorialApproval(record,now,{...manifest,entries:[...manifest.entries,...manifest.entries]}),false);});
test('content, automation metadata, dates and source binding drift fail closed',()=>{for(const mutate of [r=>r.intelligence.factScore=500,r=>r.intelligence.evidenceIds=['unrelated'],r=>r.title+=' edit',r=>r.intelligence.automation.score=1,r=>r.intelligence.automation.criticalChecks.status=false,r=>r.intelligence.automation.evidenceBindings[0].hash='a'.repeat(64),r=>r.intelligence.revision='other',r=>r.intelligence.approvedBy='James',r=>r.intelligence.approvedAt='2020-01-01',r=>r.expiresAt='2030-01-01']){const {record,manifest,now}=fixture();mutate(record);record.intelligence.approvedContent=approvedEventContent(record);assert.equal(hasAutomatedEditorialApproval(record,now,manifest),false);}});
test('Astro Date coercion and browser payload preserve approval; expiry withdraws',()=>{const {record,manifest,now}=fixture();const original=approvedEventContent(record); for(const key of ['startDate','endDate','lastCheckedDate','lastVerifiedAt','expiresAt'])record[key]=new Date(record[key]);for(const key of ['checkedAt','expiresAt'])record.intelligence.automation[key]=new Date(record.intelligence.automation[key]);for(const b of record.intelligence.automation.evidenceBindings)b.retrievedAt=new Date(b.retrievedAt);assert.equal(approvedEventContent(record),original);assert.equal(hasAutomatedEditorialApproval(publicEventData(record),now,manifest),true);assert.equal(hasAutomatedEditorialApproval(record,record.expiresAt,manifest),false);});
