type ThemeDef = {
  key: string;
  title: string;
  tags: string[];
  formats?: string[];
};
export const themeDefs: ThemeDef[] = [
  {
    key: "food-and-wine",
    title: "Food & wine",
    tags: [
      "eat",
      "wine",
      "food",
      "food-wine",
      "food-guide",
      "long-lunch",
      "cellar-door",
      "cellar-doors",
      "winery-dining",
      "wineries",
      "chardonnay",
      "pinot-noir",
      "alba",
      "truffle",
      "mushrooms",
      "produce",
      "seafood",
      "market",
      "markets",
      "red-hill-market",
      "pub",
      "pubs",
      "beer",
      "bakery",
      "cafes",
      "coffee",
      "breakfast",
      "dining",
      "restaurants",
      "fine-dining",
      "hatted",
      "hatted-restaurants",
      "michelin",
      "casual",
      "cook-in",
      "evening",
    ],
    formats: ["long-lunch-list", "cellar-door-dispatch"],
  },
  {
    key: "towns-and-places",
    title: "Towns & places",
    tags: [
      "area-guide",
      "sub-regions",
      "overview",
      "sorrento",
      "flinders",
      "red-hill",
      "mornington",
      "main-ridge",
      "merricks",
      "balnarring",
      "portsea",
      "cape-schanck",
      "dromana",
      "rye",
      "mount-martha",
      "bayside",
      "shoreham",
      "moorooduc",
      "hastings",
      "arthurs-seat",
      "point-nepean",
      "fort-nepean",
      "st-andrews-beach",
      "back-beaches",
      "ocean-coast",
      "two-bays",
      "bay",
    ],
  },
  {
    key: "seasons",
    title: "The seasons",
    tags: [
      "autumn",
      "winter",
      "spring",
      "summer",
      "seasonal",
      "solstice",
      "fire",
      "fireplace",
      "may-planning",
      "june-planning",
      "july-planning",
      "anzac-day",
      "kings-birthday",
      "mothers-day",
      "lavender",
    ],
  },
  {
    key: "walks-and-outdoors",
    title: "Walks & outdoors",
    tags: [
      "walk",
      "walks",
      "walking",
      "walking-track",
      "hikes",
      "hiking",
      "boardwalk",
      "national-park",
      "beach",
      "beaches",
      "coastal",
      "swim",
      "swimming",
      "outdoors",
      "golf",
      "public-golf",
      "sport",
      "wildlife",
      "gardens",
      "photography",
      "views",
      "lighthouse",
      "sunset",
      "waterfront",
      "ashcombe-maze",
      "cable-car",
      "gondola",
    ],
    formats: ["trail-guide"],
  },
  {
    key: "with-kids",
    title: "With kids",
    tags: [
      "family",
      "families",
      "family-friendly",
      "family-saturday",
      "kids",
      "school-holidays",
    ],
  },
  {
    key: "dog-friendly",
    title: "Dog-friendly",
    tags: [
      "dogs",
      "dog-friendly",
      "pet-friendly",
      "pets",
      "pet-shops",
      "vet",
      "grooming",
      "boarding",
    ],
  },
  {
    key: "hot-springs-and-wellness",
    title: "Hot springs & wellness",
    tags: [
      "hot-springs",
      "hotsprings",
      "peninsula-hot-springs",
      "wellness",
      "spa",
      "retreats",
    ],
  },
  {
    key: "stays-and-weekends",
    title: "Stays & weekends",
    tags: [
      "stay",
      "accommodation",
      "boutique-hotels",
      "luxury-hotels",
      "luxury",
      "villa",
      "cottage",
      "glamping",
      "winery-stay",
      "weekend",
      "weekend-escape",
      "weekend-pick",
      "weekend-picker",
      "weekly",
      "rainy-day",
      "day-trip",
      "planning",
      "free",
      "budget",
      "no-booking",
      "walk-in",
      "things-to-do",
      "couples",
      "romance",
      "weddings",
      "first-timers",
      "insider-picks",
      "locals",
    ],
    formats: ["weekend-picker", "stay-notes"],
  },
];
